/** One record per work. Period is the only primary navigation hierarchy.
 * Contributions are joint unless an individual contribution is documented.
 * Simulations are never evidence of experimental performance. */
export const periods = [
  { id:'past', title:'Past', subtitle:'Foundations', time:'2020–2025', description:'From relationships in networks to the geometry of learning.' },
  { id:'now', title:'Now', subtitle:'Active work', time:'2026', description:'What should change, what should stay, and who gets to decide?' },
  { id:'frontier', title:'Frontier', subtitle:'Direction', time:'Looking ahead', description:'Intelligence that can act in a world we can inspect and revise.' }
];
const paper = (label,url,scope) => ({label,url,scope,kind:'Primary paper'});
const code = (label,url,scope) => ({label,url,scope,kind:'Source repository'});
const guide = (...steps) => steps.map(([title,text])=>({title,text}));
export const works = [
 { id:'interaction-dynamics', period:'past', year:'2020', status:'Published research', title:'Interaction dynamics',
  fullTitle:'Interaction dynamics between hate and counter users on Twitter',
  question:'What disappears when we count posts instead of conversations?',
  summary:'Look at who replies to whom—not just how much each group posts.',
  role:'Co-author; accompanying analysis notebooks are in my repository.',
  contribution:'Joint empirical study of lexical, linguistic and psycholinguistic characteristics of users in tweet–reply conversations.',
  demonstrated:'The research analyses paired interactions. The fictional network here explains that unit of analysis; its counts are not findings from the paper.',
  application:'Two groups can produce the same volume of posts while participating in very different conversations.',
  limitation:'Descriptive interaction patterns do not establish that counterspeech causes a change in another person’s beliefs or behaviour. No real users or posts appear in this demo.',
  mechanism:'interaction', predecessor:[], successors:['spectral-bounds'], currentExperiment:null,
  nextQuestion:'Which structure is lost when a system is reduced to an aggregate?',
  sources:[paper('Published paper','https://doi.org/10.1145/3371158.3371172','Publication record; no numerical paper results are reproduced here.'),code('Analysis notebooks','https://github.com/KumarNavish/Twitter-Hate-and-counter-speakers','Repository README describes the lexical, linguistic and psycholinguistic analysis.')],
  guide:guide(['Count the posts','Both fictional groups contribute eight messages. A total alone cannot show the interaction pattern.'],['Reveal the pairs','Follow the arrows. Replies can concentrate on one account even when the group totals match.'],['Change the pattern','Redistribute the same eight replies across four accounts. The aggregate stays unchanged.'],['Keep the distinction','Pair-level observation makes the difference visible. It does not by itself establish a causal effect.'])
 },
 { id:'spectral-bounds', period:'past', year:'2021', status:'Published · Linear Algebra and its Applications', title:'Extremal spectral bounds',
  fullTitle:'Bounds for the extremal eigenvalues of gain Laplacian matrices',
  question:'How much of a network must change before its relationships agree?',
  summary:'Turn a spectral warning into a lower bound on structural repair.',
  role:'Co-author with M. Rajesh Kannan and Shivaramakrishna Pragada.',
  contribution:'Joint work on extremal gain-Laplacian bounds, including relationships to frustration and gain-dependent spectral estimates.',
  demonstrated:'The paper connects the smallest Laplacian eigenvalue to frustration and develops extremal bounds. This signed-graph example computes a simple Rayleigh lower bound and an exact small-graph repair count.',
  application:'Detecting a contradiction is different from knowing how much of the network must be revised.',
  limitation:'The example uses four vertices and ±1 gains. Exhaustive search is feasible here, not a general scalable repair algorithm. The displayed Rayleigh bound is a basic illustration, not the paper’s full family of bounds.',
  mechanism:'bounds', predecessor:['interaction-dynamics'], successors:['gain-graphs'], currentExperiment:null,
  nextQuestion:'How can graph structure be compared independently of vertex degree?',
  sources:[paper('Paper and publication record','https://arxiv.org/abs/2102.07560','Abstract and gain-Laplacian definition; published DOI 10.1016/j.laa.2021.05.009.'),code('Accompanying experiments','https://github.com/KumarNavish/gain-extremal-bounds','Original linked experiment repository; this browser calculation is separate.')],
  guide:guide(['A consistent network','A plus edge asks its endpoints to agree; a minus edge asks them to oppose. All-plus is consistent.'],['Introduce a conflict','Flip an edge. A cycle can now ask for an impossible combination of agreements.'],['Measure the repair','The eigenvalue supplies a lower bound. Exhaustive enumeration gives the actual minimum number of edges to remove in this tiny graph.'],['Repair, then recheck','Remove the conflicting edges. The remaining graph is balanced and its smallest Laplacian eigenvalue returns to zero.'])
 },
 { id:'gain-graphs', period:'past', year:'2022', status:'Published · American Journal of Combinatorics', title:'Normalized gain Laplacians',
  fullTitle:'Normalized Laplacians for gain graphs',
  question:'Can every pair agree while the whole network contradicts itself?',
  summary:'Change one relationship. Watch the inconsistency enter the spectrum.',
  role:'Co-author with M. Rajesh Kannan and Shivaramakrishna Pragada.',
  contribution:'Joint development and analysis of normalized gain Laplacians: spectral bounds, equality cases, balance, bipartiteness and edge interlacing.',
  demonstrated:'The work establishes a normalized spectral framework and structural relationships for complex unit gain graphs. The triangle below is an exactly computed special case, not a new theorem.',
  application:'Imagine three devices that specify relative orientations. Following their instructions around a loop must bring you back to your starting orientation.',
  limitation:'This orientation network is an interpretation of the mathematical structure, not a validated sensor-repair application. A spectrum detects a structural issue; it does not uniquely identify the faulty edge.',
  mechanism:'gain', predecessor:['spectral-bounds'], successors:['natural-gradient'], currentExperiment:null,
  nextQuestion:'What can the geometry of a system tell us about how it may change?',
  sources:[paper('Paper and journal record','https://arxiv.org/abs/2009.13788','Normalized Laplacian framework; journal publication in 2022 (preprint first posted in 2020).')],
  guide:guide(['Three local agreements','Each device asks the next to face the same direction. Following the loop returns to the start.'],['Change one relationship','Make the closing relationship demand a 120° turn. The loop no longer closes consistently.'],['Read the global signal','That edge changes two conjugate entries of the normalized Laplacian. Its smallest eigenvalue moves above zero.'],['Repair the relationship','Restore the closing angle to zero. The loop closes and the smallest eigenvalue returns to zero.'])
 },
 { id:'urban-microregions', period:'past', year:'2022–2023', status:'NeurIPS 2022 workshop · 2023 preprint', title:'Urban micro-regions',
  fullTitle:'Modelling the performance of delivery vehicles across urban micro-regions to accelerate the transition to cargo-bike logistics',
  question:'Why should the same delivery take different time on the next street?',
  summary:'Change the street context. See parking, travel and walking add up.',
  role:'Co-author with Max Schrader and six other collaborators.',
  contribution:'Joint introduction of delivery datasets and initial service-time modelling using H3 micro-regions and aggregated OpenStreetMap context.',
  demonstrated:'The study identifies urban context as a predictor of delivery performance. This schematic uses transparent illustrative arithmetic, not the paper’s fitted model or real city measurements.',
  application:'A single city-wide average can hide the local conditions that matter for delivery planning.',
  limitation:'The hexagons are not geographic H3 cells. The times do not justify a real fleet decision; payload, routing, weather and operating constraints are omitted.',
  mechanism:'urban', predecessor:['interaction-dynamics'], successors:['spatial-world'], currentExperiment:null,
  nextQuestion:'How should intelligent systems retain the context of the physical world?',
  sources:[paper('Workshop paper','https://arxiv.org/abs/2301.12887','Abstract: two datasets, H3 cells, OpenStreetMap context and initial service-time modelling.'),code('Green Last Mile','https://github.com/KumarNavish/green-last-mile','Related spatial-modelling project linked from the previous portfolio.')],
  guide:guide(['One delivery','Begin with the same parcel and route length. Transport time alone is not the whole task.'],['Enter a dense street','Parking search and the walk from a parked vehicle change the service time.'],['Change the neighbourhood','Select another hexagon. The balance changes because the local context changes.'],['Keep the components','Compare travel, parking and walking separately before making an operational judgement.'])
 },
 { id:'natural-gradient', period:'past', year:'2025', status:'Preprint', title:'Natural-gradient guarantees',
  fullTitle:'Optimization Guarantees for Square-Root Natural-Gradient Variational Inference',
  question:'When does a fast way to learn also come with a convergence guarantee?',
  summary:'Fit a distribution, not just a point—and expose the update geometry.',
  role:'First author with Thomas Möllenhoff, Mohammad Emtiyaz Khan and Aurelien Lucchi.',
  contribution:'Convergence analysis of natural-gradient flow and square-root natural-gradient Gaussian variational inference, under the paper’s assumptions.',
  demonstrated:'The paper proves convergence results under strongly concave log-likelihood conditions and additional regularity and step-size assumptions. It does not invent natural gradients or claim an unconditional guarantee.',
  application:'An approximate posterior carries both an estimate and uncertainty. The update must improve that distribution while preserving its valid structure.',
  limitation:'This diagonal quadratic example implements Algorithm 1 with exact derivatives. It is not a replay of the paper’s experiments, and its error curve is not evidence of a universal speed advantage.',
  mechanism:'natural', predecessor:['gain-graphs'], successors:['experience-replay'], currentExperiment:null,
  nextQuestion:'What happens when one learning update must also preserve earlier capabilities?',
  sources:[paper('Preprint','https://arxiv.org/abs/2507.07853','Author list and scope.'),paper('Algorithm 1 and assumptions','https://arxiv.org/html/2507.07853v1#S3.SS4','Square-root update; Sections 4–5 contain conditions and convergence results.')],
  guide:guide(['An uncertain estimate','The wide ellipse is a Gaussian approximation. The dashed ellipse is the target posterior in this analytic example.'],['Update mean and shape','Take a square-root natural-gradient step. The mean and covariance change together.'],['Follow the actual error','Run more steps. The plotted KL divergence is computed from the two Gaussian distributions, not a scripted curve.'],['Separate example from theorem','The example illustrates the update. The paper’s contribution is a convergence analysis under stated assumptions.'])
 },
 { id:'experience-replay', period:'now', year:'2026', status:'Active research', title:'Experience Replay',
  fullTitle:'Experience Replay Through the Lens of Optimization',
  question:'Which memories actually protect an earlier capability?',
  summary:'Learn something new. Lose an old skill. Choose the missing correction.',
  role:'Research with Aurelien Lucchi; replay viewed through constrained correction matching.',
  contribution:'Investigating which corrections a finite memory buffer can express, and how to measure the mismatch that remains.',
  demonstrated:'The browser computes a two-parameter learning example. The current manuscript record could not be independently retrieved during this update; no unpublished performance or acceptance claim is made here.',
  application:'A system that learns after deployment must choose useful memories, not merely retain a large archive.',
  limitation:'The toy tasks are partly incompatible. Reducing old-task error can increase new-task error. Matching a correction does not prove that real-world forgetting is solved.',
  mechanism:'replay', predecessor:['natural-gradient'], successors:['rank-feasibility','tic-lm'],
  currentExperiment:'The live example asks whether the selected memories span the desired correction. It is not a reported research experiment.',
  nextQuestion:'When is the needed repair outside the adaptation space itself?',
  sources:[paper('Linked manuscript record','https://openreview.net/forum?id=4z7il66fFb','Link preserved from the prior site. Current contents and review status were not independently retrieved.')],
  guide:guide(['Learn two old skills','The model predicts 1 for each earlier skill. Its shared parameters are (1, 1).'],['Learn a new task','The new target asks their sum to be 4. Moving to (2, 2) fits it—but damages both earlier skills.'],['Replay an incomplete memory','Remembering only skill A can correct only the first parameter. Skill B’s missing correction remains visible.'],['Add the missing memory','Include both skills. The desired correction becomes expressible, but preserving the old tasks still costs some fit on the new task.'])
 },
 { id:'rank-feasibility', period:'now', year:'2026', status:'Active research', title:'Rank Feasibility',
  fullTitle:'Rank Feasibility in Continual PEFT',
  question:'What if the model cannot express the repair it needs?',
  summary:'Increase the available rank. Separate possible from affordable.',
  role:'Research with Aurelien Lucchi; feasibility of task-wise low-rank corrections.',
  contribution:'Investigating whether an adaptation space can express a required correction before treating the failure as an optimization problem.',
  demonstrated:'The demo exactly computes the best rank-r approximation to a diagonal repair matrix. This standard linear-algebra example explains the question; it is not a novelty claim or a complete model of LoRA training.',
  application:'More optimization cannot make a rank-one matrix express three independent correction directions.',
  limitation:'Real task constraints need not require a unique full matrix. Feasibility in a nonlinear model and the cost of preserving current learning need separate evidence. Manuscript contents and current review status were not independently retrieved.',
  mechanism:'rank', predecessor:['experience-replay'], successors:['tic-lm'],
  currentExperiment:'Illustrative required correction diag(1, 0.7, 0.35), with an explicitly defined quadratic preservation cost.',
  nextQuestion:'Which repairs remain relevant as the task itself changes over time?',
  sources:[paper('Linked manuscript record','https://openreview.net/forum?id=CwmHHYCbjK','Link preserved from the prior site; no current acceptance or experimental-result claim.')],
  guide:guide(['Three changes are needed','The target repair has three independent directions. Each bar is one singular value.'],['Restrict the adapter','Rank one can express only one of those directions. The remaining matrix error cannot be trained away within that rank limit.'],['Expand the available rank','Rank three can express this entire repair. Expressibility is now satisfied.'],['Check the other cost','The complete repair also changes the current task. Increase or tighten its cost budget: possible does not automatically mean acceptable.'])
 },
 { id:'tic-lm', period:'now', year:'2026', status:'Replication / ongoing investigation', title:'TiC-LM replication',
  fullTitle:'Time-continual language modelling: studying the value of old data',
  question:'When does remembering yesterday make today’s answer worse?',
  summary:'Advance time. Watch the same historical data become stale.',
  role:'Replication and investigation using the TiC-LM benchmark—not an author of the original benchmark.',
  contribution:'Studying the trade-off between preserving stable knowledge and adapting to changing information. No independently validated replication result is claimed on this page.',
  demonstrated:'Li and colleagues introduced TiC-LM and report domain-dependent replay trade-offs. The browser illustrates a bias–variance mechanism with an analytic estimator; it does not train a language model.',
  application:'Old observations reduce noise when the world is stable. They can introduce bias when the quantity being estimated changes.',
  limitation:'The adaptive setting uses the known drift of this toy world—an oracle unavailable in general. It is not a proposed practical algorithm or a claim that all historical replay is harmful.',
  mechanism:'time', predecessor:['experience-replay','rank-feasibility'], successors:['spatial-world'],
  currentExperiment:'Toy mean-estimation example: four new observations, sixteen old observations and controllable mean drift.',
  nextQuestion:'Can a system retain history while understanding which parts of its world have changed?',
  sources:[paper('Original TiC-LM · Li et al.','https://aclanthology.org/2025.acl-long.1551/','Original benchmark and results; Navish Kumar is not in the author list.'),code('Original benchmark code','https://github.com/apple/ml-tic-lm','Original authors’ implementation, not this browser example.')],
  guide:guide(['A stable world','Old and new observations estimate the same quantity. Combining them reduces noise.'],['Time moves forward','The present changes while the historical records stay fixed. The old data now pull toward an outdated value.'],['Measure the trade-off','With enough drift, that bias outweighs the reduction in noise. The same replay fraction now increases expected error.'],['Change the allocation','Use the known toy drift to choose the error-minimizing fraction. This is an oracle illustration, not a deployable solution.'])
 },
 { id:'casepath', period:'now', year:'2026', status:'System in development', title:'CasePath',
  fullTitle:'CasePath — inspectable evidence, actions and replay',
  question:'A plausible answer. But is the system allowed to act?',
  summary:'Find the contradiction. Refuse the action. Correct only what depends on it.',
  role:'Systems and product development; evidence, authority and replay as separate concerns.',
  contribution:'Building an inspectable claims workbench that separates original sources, observations, model proposals, accepted actions and journal projections.',
  demonstrated:'The standalone repository documents deterministic claim handling and replay with synthetic development cases. The interaction here is a smaller browser illustration, not the actual application or a model-quality evaluation.',
  application:'An interpretation can be plausible while the evidence needed to authorize its proposed action is still unresolved.',
  limitation:'Synthetic example only. No real claim, payment, insurance advice or legal determination. The original source is immutable; a human-reviewed correction is recorded separately. The current repository explicitly disclaims the older hosted release.',
  mechanism:'case', predecessor:['experience-replay'], successors:['spatial-world'],
  currentExperiment:'A deliberately contradictory date tests whether the action gate and dependency replay behave correctly.',
  nextQuestion:'Can the same separation between interpretation, state and authority govern richer environments?',
  sources:[code('Current standalone CasePath','https://github.com/KumarNavish/casepath','README: supported product mechanics, synthetic data, authority separation, limitations and old-hosted-release disclaimer.')],
  guide:guide(['Read the original','The fictional source says 12 May. The policy record ends on 31 May. The original message stays unchanged.'],['Meet the contradiction','A stored model interpretation says 12 June but proposes payment. A plausible proposal cannot settle the contradictory date.'],['Attempt the action','Try the action gate. It refuses because source and interpretation disagree. No payment is sent.'],['Correct and replay','Record the reviewed date. Recompute date → coverage → admissibility; keep the independent invoice check intact. A human decision is now admissible.'])
 },
 { id:'spatial-world', period:'frontier', year:'Frontier', status:'Working interface prototype · research direction', title:'GenAI × spatial computing',
  fullTitle:'Language as persistent, inspectable world state',
  question:'What if a sentence changed your world instead of generating another picture?',
  summary:'Create a laboratory. Move one object. Keep the rest of the world.',
  role:'Exploring persistent spatial interfaces and situated systems.',
  contribution:'A local prototype with 3D coordinates, object identity, direct manipulation, revision history, explicit relations and deterministic path planning.',
  demonstrated:'This page renders and edits a persistent 3D scene. A small command grammar—not a generative model—interprets supported text. Optional speech uses the browser’s speech-recognition service.',
  application:'“Move the microscope closer to the window” should revise one object in the same scene, not discard and regenerate the environment.',
  limitation:'Not general language understanding, production VR, autonomous intelligence or a completed research result. Geometry is procedural. Speech support varies and may transmit audio to the browser vendor; typed commands stay local.',
  mechanism:'world', predecessor:['urban-microregions','tic-lm','casepath'], successors:[],
  currentExperiment:'Can people understand what changed by inspecting persistent objects, relations and state diffs?',
  nextQuestion:'How should learned interpretation be connected to reliable action in a persistent spatial environment?',
  sources:[],
  guide:guide(['Create a world','Create a mountain laboratory at sunset. Put a microscope beside a robotic arm.'],['Edit the same world','Move the microscope closer to the window. The object keeps its identity; the arm does not move.'],['Inspect the change','Rotate the camera, select an object and inspect its coordinates. The revision log records precisely what changed.'],['Act within the world','Send the agent to the microscope. A deterministic grid planner routes it around the workbench. Undo restores the previous state.'])
 }
];
export const byId = Object.fromEntries(works.map(work=>[work.id,work]));
export const checkedAt = '2026-09-13';
