import {esc} from './render.mjs?v=scroll-4.2.2';
import {mountProjectScene} from './studio.mjs?v=scroll-4.2.2';
import {gainTriangle,signedGraph,edges,replayExample,rankExample,timeExample,posteriorExample,urbanExample,interactionExample,newCase,refreshCase,caseAction} from './mechanisms.mjs?v=scroll-4.2.2';
const C={ink:'#263b3d',accent:'#087e79',soft:'#d9ece8',muted:'#829596',line:'#cbd9d8',error:'#b74f3c',pale:'#f7f9f8'};
const f=(n,d=3)=>Number(n).toFixed(d), svg=(body,view='0 0 640 360')=>`<svg class="graphic" viewBox="${view}" role="img">${body}</svg>`;
const line=(x1,y1,x2,y2,color=C.line,width=2,extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${extra}/>`;
const text=(x,y,s,cls='node-label',extra='')=>`<text x="${x}" y="${y}" class="${cls}" ${extra}>${esc(s)}</text>`;
const metric=(label,value,unit='')=>`<div class="metric"><dt>${esc(label)}</dt><dd>${esc(value)}${unit?`<small>${esc(unit)}</small>`:''}</dd></div>`;
const reading=(title,description,values)=>`<h3>${esc(title)}</h3><p>${esc(description)}</p><dl class="metrics">${values}</dl>`;
function shell(root,controls,foot,math=''){
 root.innerHTML=`<div class="lab-layout"><div class="lab-visual"><div class="reference-visual" data-viz></div></div><aside class="lab-reading" data-reading aria-live="polite"></aside></div><div class="controls">${controls}</div><p class="lab-footnote">${foot}</p>${math?`<details class="math-details"><summary>See the calculation</summary><div class="math-body" data-math>${math}</div></details>`:''}`;
 return {viz:root.querySelector('[data-viz]'),read:root.querySelector('[data-reading]'),math:root.querySelector('[data-math]')};
}
const range=(id,label,min,max,value,step=1,unit='')=>`<label class="control" for="${id}"><span class="range-label">${label}<output id="${id}-value">${value}${unit}</output></span><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const button=(id,label,cls='button secondary')=>`<button type="button" class="${cls}" data-action="${id}">${label}</button>`;
function bind(root,selector,event,fn){root.querySelectorAll(selector).forEach(el=>el.addEventListener(event,fn));}
function spectrum(values,max=4){return `<g transform="translate(0,278)">${line(50,30,590,30)}${Array.from({length:max+1},(_,i)=>text(50+i*540/max,60,i,'tiny-label','text-anchor="middle"')).join('')}${values.map((v,i)=>`<circle cx="${50+v*540/max}" cy="${30-(values.filter((x,j)=>j<i&&Math.abs(x-v)<.03).length)*14}" r="6" fill="${i===0?C.accent:C.muted}"/>`).join('')}${text(50,0,'Laplacian eigenvalues','tiny-label')}</g>`;}
function gain(root,explore){
 let theta=0;const ui=shell(root,range('angle','Closing relationship',-180,180,0,1,'°')+button('repair','Repair the relationship'),'A three-device orientation analogy. The spectral values are exact for this cycle; this is not an experiment on a sensor network.','');
 const angle=root.querySelector('#angle');
 function draw(){const s=gainTriangle(theta);root.dataset.state=JSON.stringify(s);angle.value=theta;root.querySelector('#angle-value').value=`${theta}°`;const pts=[[145,70],[490,70],[318,232]];
 ui.viz.innerHTML=svg(`<title>A three-node gain graph and its normalized Laplacian spectrum</title>${line(...pts[0],...pts[1],C.accent,3)}${line(...pts[1],...pts[2],C.accent,3)}${line(...pts[2],...pts[0],s.balanced?C.accent:C.error,4)}${pts.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="31" fill="white" stroke="${C.line}" stroke-width="2"/>${line(x-10,y,x+12,y,C.accent,3)}<path d="M${x+5} ${y-6}l8 6-8 6" fill="none" stroke="${C.accent}" stroke-width="2"/>${text(x,y+53,['Device A','Device B','Device C'][i],'node-label','text-anchor="middle"')}`).join('')}${text(318,52,'0°','value-label','text-anchor="middle"')}${text(444,171,'0°','value-label')}${text(138,169,`${theta}°`,s.balanced?'accent-label':'error-label')}${text(318,147,s.balanced?'The loop closes.':'The loop cannot close.','strong-label','text-anchor="middle"')}${spectrum(s.eigenvalues,2)}`);
 ui.read.innerHTML=reading(s.balanced?'All relationships agree.':'Locally simple. Globally impossible.',s.balanced?'Following the three relationships brings the orientation back to where it started.':'Following the loop brings the orientation back rotated. No set of device orientations can satisfy every edge.',metric('Smallest eigenvalue',f(s.eigenvalues[0]))+metric('Closure mismatch',`${Math.abs(theta)}°`));
 const matrix=s.matrix.map(row=>row.join('    ')).join('\n');
 let details=root.querySelector('[data-math]');if(!details){root.insertAdjacentHTML('beforeend','<details class="math-details"><summary>See the calculation</summary><div class="math-body" data-math></div></details>');details=root.querySelector('[data-math]');}
 details.innerHTML=`<p>For this degree-two cycle, L = I − A/2. Changing the closing edge changes two conjugate matrix entries.</p><pre class="formula">${esc(matrix)}</pre><p>λₖ = 1 − cos((θ + 2πk)/3), k = 0, 1, 2. At zero mismatch the smallest eigenvalue is zero. The paper establishes a wider normalized spectral framework, not just this example.</p>`;
 }
 angle.addEventListener('input',()=>{theta=+angle.value;explore('Follow the closing edge, then the leftmost spectral point.');draw();});bind(root,'[data-action="repair"]','click',()=>{theta=0;explore('The relationship is repaired. The zero eigenvalue returns.');draw();});draw();return{stage:i=>{theta=i===0||i===3?0:120;draw();},reset:()=>{theta=0;draw();}};
}
function bounds(root,explore){
 let signs=[1,1,1,1,1,1],removed=[];const ui=shell(root,`<div class="control"><span>Change a relationship</span><div class="edge-buttons">${edges.map(([a,b],i)=>button(`edge-${i}`,`${'ABCD'[a]}–${'ABCD'[b]} +`,'small-button')).join('')}</div></div>`+button('repair','Remove a minimum repair'),'Four nodes, six signed relationships. The exact repair is found by checking all eight distinct sign assignments—not by a scalable solver.','<p>For a sign vector x ∈ {−1,+1}ⁿ, xᵀLx = 4 × (number of unsatisfied edges). Rayleigh’s inequality gives frustration ≥ ⌈n λ_min / 4⌉. This basic bound is an illustration, not a reproduction of all the stronger bound families in the paper.</p>');
 function draw(){const s=signedGraph(signs,removed);root.dataset.state=JSON.stringify({...s,signs,removed});const pts=[[180,60],[450,60],[180,230],[450,230]];
 ui.viz.innerHTML=svg(`<title>Signed relationships, required repair, and spectrum</title>${edges.map(([a,b],i)=>{const p=pts[a],q=pts[b];return line(...p,...q,removed.includes(i)?C.line:signs[i]===1?C.accent:C.error,removed.includes(i)?2:3,removed.includes(i)?'stroke-dasharray="6 6"':'')+text((p[0]+q[0])/2+(i===2?-22:i===3?22:0),(p[1]+q[1])/2-8,removed.includes(i)?'removed':signs[i]===1?'+':'−','strong-label','text-anchor="middle"');}).join('')}${pts.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="24" fill="white" stroke="${C.line}"/>${text(x,y+6,'ABCD'[i],'strong-label','text-anchor="middle"')}`).join('')}${spectrum(s.eigenvalues,6)}`,'0 0 640 360');
 ui.read.innerHTML=reading(s.frustration?'Some agreements must give.':'A consistent assignment exists.',s.frustration?'No assignment can satisfy all the signs. The spectrum gives a certified lower bound; enumeration gives the actual repair.':'Every remaining relationship can be satisfied simultaneously. Zero is restored to the spectrum.',metric('Spectral lower bound',s.lowerBound,'edges')+metric('Exact minimum repair',s.frustration,'edges')+metric('Smallest eigenvalue',f(s.minimum)));
 edges.forEach(([a,b],i)=>{const btt=root.querySelector(`[data-action="edge-${i}"]`);btt.textContent=`${'ABCD'[a]}–${'ABCD'[b]} ${signs[i]>0?'+':'−'}`;btt.setAttribute('aria-pressed',String(signs[i]<0));});
 }
 edges.forEach((_,i)=>bind(root,`[data-action="edge-${i}"]`,'click',()=>{signs[i]*=-1;removed=[];explore('One local relationship changes. Recheck what the whole network can satisfy.');draw();}));bind(root,'[data-action="repair"]','click',()=>{removed=signedGraph(signs).repair;explore('Only a minimum set of edges was removed. Dashed relationships are no longer imposed.');draw();});draw();return{stage:i=>{signs=i===0?[1,1,1,1,1,1]:[-1,1,1,1,1,1];removed=i===3?signedGraph(signs).repair:[];draw();},reset:()=>{signs=[1,1,1,1,1,1];removed=[];draw();}};
}
function interaction(root,explore){
 let paired=false,distributed=false;const ui=shell(root,button('pairs','Reveal the pairs')+button('pattern','Redistribute the same messages'),'All users, edges and counts here are fictional. Pair-level analysis is descriptive: an observed interaction pattern is not evidence that counterspeech caused a behavioural change.','<p>Recipient counts are sums of edge weights. Concentrated: [6, 1, 1, 0]. Distributed: [2, 2, 2, 2]. Both sum to eight, so an aggregate count cannot distinguish them.</p>');
 function draw(){const s=interactionExample(distributed);root.dataset.state=JSON.stringify({...s,paired,distributed});ui.viz.innerHTML=svg(`<title>Equal message totals can hide unequal pair-level interactions</title>${text(120,30,'Fictional group A','node-label','text-anchor="middle"')}${text(520,30,'Fictional group B','node-label','text-anchor="middle"')}${paired?s.pairs.map(([a,b,n])=>line(146,85+a*66,494,85+b*66,C.accent,2+n*2)+text(305,85+(a+b)*33-8,n,'tiny-label','text-anchor="middle"')).join(''):line(165,183,475,183,C.accent,12)}${paired?[0,1,2,3].map(i=>`<circle cx="120" cy="${85+i*66}" r="22" fill="white" stroke="${C.line}"/><circle cx="520" cy="${85+i*66}" r="22" fill="white" stroke="${C.line}"/>${text(120,91+i*66,`A${i+1}`,'node-label','text-anchor="middle"')}${text(520,91+i*66,`B${i+1}`,'node-label','text-anchor="middle"')}${text(565,91+i*66,s.recipientCounts[i],'value-label')}`).join(''):`<circle cx="120" cy="183" r="42" fill="white" stroke="${C.line}"/><circle cx="520" cy="183" r="42" fill="white" stroke="${C.line}"/>${text(120,190,'8','strong-label','text-anchor="middle"')}${text(520,190,'8','strong-label','text-anchor="middle"')}${text(320,157,'8 messages','strong-label','text-anchor="middle"')}`}${text(320,345,paired?'Line width shows the number of messages.':'What does this total leave out?','tiny-label','text-anchor="middle"')}`);
 ui.read.innerHTML=reading(paired?(distributed?'Same total. Different relationships.':'One account receives most replies.'):'The total hides the structure.',paired?'Changing who interacts with whom changes the picture without changing the aggregate.':'Eight messages tells us how much activity occurred. It does not tell us how that activity was distributed.',metric('Messages',8)+metric('Largest recipient share',paired?`${Math.max(...s.recipientCounts)/8*100}%`:'Hidden')+metric('Recipients reached',paired?s.distinctRecipients:'Hidden'));
 root.querySelector('[data-action="pairs"]').textContent=paired?'Hide the pairs':'Reveal the pairs';
 }
 bind(root,'[data-action="pairs"]','click',()=>{paired=!paired;explore('Compare the same interactions with and without their pair structure.');draw();});bind(root,'[data-action="pattern"]','click',()=>{distributed=!distributed;paired=true;explore('The message total is unchanged. The recipient pattern is not.');draw();});draw();return{stage:i=>{paired=i>0;distributed=i>1;draw();},reset:()=>{paired=false;distributed=false;draw();}};
}
function replay(root,explore){
 let phase='old',memories=[true,false],strength=.8;const ui=shell(root,`<div class="toggle-group">${button('old','Old skills')}${button('new','Learn new task')}${button('replay','Apply replay')}</div><div class="control"><span>Available memories</span><div><label class="check"><input id="memory-a" type="checkbox" checked> Skill A</label><label class="check"><input id="memory-b" type="checkbox"> Skill B</label></div></div>`+range('strength','Correction strength',0,1,.8,.05),'A two-parameter quadratic example, not a trained language model or a benchmark result. Recovering an old skill has a visible cost on the new task.','<p>Old loss = ½[(θ₁−1)²+(θ₂−1)²]. New loss = ½(θ₁+θ₂−4)². From (2,2), the intended replay correction is (−s,−s). A memory for skill A can change only θ₁; a memory for B can change only θ₂. Missing correction is the Euclidean norm of the unavailable part.</p>');
 function draw(){const s=replayExample(phase,memories,strength);root.dataset.state=JSON.stringify({...s,phase,memories,strength});ui.viz.innerHTML=`<div class="viz-caption">Predictions of the same model</div>${[['Earlier skill A',s.theta[0],1,2.4],['Earlier skill B',s.theta[1],1,2.4],['New task: A + B',s.theta[0]+s.theta[1],4,4.8]].map(([label,value,target,max])=>`<div class="skill-row"><span class="skill-label">${label}</span><div class="skill-track"><div class="skill-fill" style="width:${value/max*100}%"></div><span class="skill-target" style="left:${target/max*100}%"></span></div><span class="skill-number">${f(value,2)}</span></div>`).join('')}<p class="legend"><span class="legend-mark"></span> Model prediction <span class="legend-target"></span> Task target</p><div class="status-line ${s.oldLoss>.1?'warning':''}">${phase==='old'?'Both earlier skills are at their target.':phase==='new'?'The new task is fitted. Both earlier skills have moved off target.':memories.every(Boolean)?'Both correction directions are available. The new-task fit now changes.':'A missing memory leaves a missing direction of correction.'}</div>`;
 ui.read.innerHTML=reading(phase==='old'?'A good starting point.':phase==='new'?'Learning can be destructive.':s.missing>0?'The buffer cannot express it all.':'Correction is possible—not free.',phase==='replay'?'The residual measures the requested correction that these memories cannot supply. It is not a claim of zero forgetting.':'The same parameters serve the old skills and the new task. Changing one affects the others.',metric('Old-task error',f(s.oldLoss))+metric('New-task error',f(s.newLoss))+metric('Missing correction',phase==='replay'?f(s.missing):'—'));
 root.querySelector('#memory-a').checked=memories[0];root.querySelector('#memory-b').checked=memories[1];root.querySelector('#strength').value=strength;root.querySelector('#strength-value').value=f(strength,2);['old','new','replay'].forEach(p=>root.querySelector(`[data-action="${p}"]`).setAttribute('aria-pressed',String(phase===p)));
 }
 ['old','new','replay'].forEach(p=>bind(root,`[data-action="${p}"]`,'click',()=>{phase=p;explore();draw();}));['a','b'].forEach((a,i)=>bind(root,`#memory-${a}`,'change',e=>{memories[i]=e.target.checked;phase='replay';explore('The available memories determine which correction directions can be realized.');draw();}));bind(root,'#strength','input',e=>{strength=+e.target.value;phase='replay';explore('A stronger correction protects old skills but moves away from the new target.');draw();});draw();return{stage:i=>{phase=i===0?'old':i===1?'new':'replay';memories=[true,i===3];draw();},reset:()=>{phase='old';memories=[true,false];strength=.8;draw();}};
}
function rank(root,explore){
 let r=1,budget=.15;const ui=shell(root,range('rank','Adapter rank',1,3,1)+range('budget','Current-task cost budget',0,.7,.15,.01),'A best rank-r matrix approximation illustrates expressibility. This standard example is not presented as a new theorem or as a validation of an unpublished continual-learning method.','<p>Required repair D = diag(1, 0.7, 0.35). Its best rank-r approximation keeps the r largest singular values. The residual is the Frobenius norm of the discarded part. Current-task cost is ½ Σⱼ(aⱼ Dᵣ,ⱼⱼ)² with a=(0.1,0.8,2). A 3×r and r×3 factorization stores 6r parameters; at high rank it need not save storage.</p>');
 function matrix(vals,target=false){return `<div class="matrix">${Array.from({length:9},(_,i)=>{const j=Math.floor(i/3),diag=j===i%3;return `<span class="${diag?(target||vals[j]?'active':'missing'):''}">${diag?f(vals[j],2):'0'}</span>`;}).join('')}</div>`;}
 function draw(){const s=rankExample(r,budget);root.dataset.state=JSON.stringify(s);ui.viz.innerHTML=`<div class="matrix-pair"><div><p class="viz-caption">Required repair</p>${matrix(s.singular,true)}</div><span class="matrix-arrow" aria-hidden="true">→</span><div><p class="viz-caption">Available at rank ${r}</p>${matrix(s.kept)}</div></div><div class="rank-modes">${s.singular.map((v,i)=>`<div><span>Direction ${i+1}</span><div style="height:${v*70}px;background:${i<r?C.accent:C.line}"></div><strong>${v}</strong></div>`).join('')}</div><div class="status-line ${!s.expressible||!s.affordable?'warning':''}">${!s.expressible?'Impossible at this rank: a nonzero residual remains.':!s.affordable?'Expressible, but beyond the current-task cost budget.':'Expressible and within this illustrative cost budget.'}</div>`;
 ui.read.innerHTML=reading(!s.expressible?'Optimization cannot add a missing direction.':!s.affordable?'Possible is not yet acceptable.':'Both conditions are met.',!s.expressible?'Even the best rank-limited approximation cannot represent the entire repair. More optimizer steps cannot remove this rank constraint.':'Increasing rank removes the expressibility barrier. The separate cost constraint still has to be checked.',metric('Irreducible repair error',f(s.residual))+metric('Current-task cost',f(s.cost))+metric('Factor parameters',s.parameters));
 root.querySelector('#rank').value=r;root.querySelector('#rank-value').value=r;root.querySelector('#budget').value=budget;root.querySelector('#budget-value').value=f(budget,2);
 }
 bind(root,'#rank','input',e=>{r=+e.target.value;explore('Compare the missing matrix entries with the remaining error.');draw();});bind(root,'#budget','input',e=>{budget=+e.target.value;explore('This changes what is acceptable, not what the adapter can express.');draw();});draw();return{stage:i=>{r=i<2?1:3;budget=.15;draw();},reset:()=>{r=1;budget=.15;draw();}};
}
function time(root,explore){
 let month=0,fraction=.5,stable=false;const ui=shell(root,range('month','Time',0,10,0)+range('fraction','Historical replay fraction',0,100,50,1,'%')+`<label class="check"><input id="stable" type="checkbox"> Keep the world stable</label>`+button('oracle','Use toy-optimal allocation'),'A noisy-mean estimation example, not TiC-LM measurements. The original benchmark is credited below; this portfolio entry concerns replication. The optimal-allocation button has access to the toy’s true drift.','<p>Four new and sixteen historical observations have unit noise variance. With old-data fraction α and drift δ, mean-squared error = (αδ)² + (1−α)²/4 + α²/16. New-only error is 1/4. The oracle optimum α* = (1/4)/(δ²+1/4+1/16) assumes the drift is known.</p>');
 function draw(){const s=timeExample(month,fraction,stable);root.dataset.state=JSON.stringify({...s,stable});ui.viz.innerHTML=`<div class="time-strip">${Array.from({length:11},(_,i)=>`<div class="month ${i>month?'future':''} ${i===month?'current':''} ${i<month&&s.drift>0?'stale':''}"><span>${i===month?'Now':i<month?'Past':'Later'}</span><strong>${i}</strong></div>`).join('')}</div>${svg(`<title>Historical bias and expected error as time progresses</title>${line(65,86,580,86)}${text(65,48,'Historical mean stays fixed','tiny-label')}${text(580,48,'Present moves','tiny-label','text-anchor="end"')}<circle cx="65" cy="86" r="9" fill="${C.muted}"/><circle cx="${65+s.drift/1.75*490}" cy="86" r="10" fill="${C.accent}"/><circle cx="${65+(1-fraction)*s.drift/1.75*490}" cy="86" r="6" fill="${C.error}"/>${text(65,137,`Historical pull: ${f(s.bias)} units`,'node-label')}${text(65,197,'New observations only','node-label')}<rect x="65" y="213" width="${.25/3.4*480}" height="24" rx="3" fill="${C.muted}"/>${text(110,231,'.250','tiny-label')}${text(65,274,'With historical replay','node-label')}<rect x="65" y="290" width="${Math.max(2,s.error/3.4*480)}" height="24" rx="3" fill="${s.benefit>=0?C.accent:C.error}"/>${text(75+Math.max(2,s.error/3.4*480),309,f(s.error),'value-label')}`,'0 0 640 345')}`;
 ui.read.innerHTML=reading(s.benefit>=0?'Memory reduces the error.':'The same memory now hurts.',s.benefit>=0?'Historical observations reduce noise enough to justify their bias at this time.':'The history still describes the past. Its bias now outweighs the reduction in noise.',metric('Expected error',f(s.error))+metric('Change vs new-only',`${s.benefit>0?'−':'+'}${f(Math.abs(s.benefit))}`)+metric('World drift',f(s.drift)));
 root.querySelector('#month').value=month;root.querySelector('#month-value').value=month;root.querySelector('#fraction').value=Math.round(fraction*100);root.querySelector('#fraction-value').value=`${f(fraction*100,1)}%`;root.querySelector('#stable').checked=stable;
 }
 bind(root,'#month','input',e=>{month=+e.target.value;explore('The past stays fixed while the present advances.');draw();});bind(root,'#fraction','input',e=>{fraction=+e.target.value/100;explore('Balance reduced noise against the bias introduced by old observations.');draw();});bind(root,'#stable','change',e=>{stable=e.target.checked;explore('Stable and changing domains should not be treated as the same case.');draw();});bind(root,'[data-action="oracle"]','click',()=>{fraction=timeExample(month,fraction,stable).optimalFraction;explore('This uses the known toy drift. Estimating that drift reliably is a separate problem.');draw();});draw();return{stage:i=>{month=[0,5,10,10][i];stable=false;fraction=i===3?timeExample(10).optimalFraction:.5;draw();},reset:()=>{month=0;fraction=.5;stable=false;draw();}};
}
function natural(root,explore){
 let steps=0,method='natural';const ui=shell(root,range('iterations','Optimization steps',0,80,0)+button('step','Take one step')+`<label class="control" for="geometry"><span>Update geometry</span><select id="geometry"><option value="natural">Square-root natural gradient</option><option value="euclidean">Euclidean square-root gradient</option></select></label>`,'An exact diagonal Gaussian target, with analytic gradients and a fixed step size of 0.07. Both methods use the same starting state. This example is not a general speed comparison.','<p>Target mean μ=(1,−0.5), precision h=(1,7). The diagonal specialization of Algorithm 1 uses m′ⱼ=mⱼ−ρcⱼ²hⱼ(mⱼ−μⱼ), c′ⱼ=cⱼ−(ρ/2)cⱼ(hⱼcⱼ²−1). Both updates use the old c. KL = ½Σ[hⱼ(mⱼ−μⱼ)²+hⱼcⱼ²−log(hⱼcⱼ²)−1].</p>');
 function draw(){const s=posteriorExample(steps,method);root.dataset.state=JSON.stringify({steps,method,kl:s.kl,m:s.m,c:s.c,path:s.path});const px=x=>70+(x+4)/8*500,py=y=>32+(3-y)/6*238;
 ui.viz.innerHTML=svg(`<title>Actual Gaussian approximation and computed KL divergence</title>${[-2,0,2].map(y=>line(70,py(y),570,py(y),C.line,1)).join('')}${[-2,0,2].map(x=>line(px(x),32,px(x),270,C.line,1)).join('')}<ellipse cx="${px(1)}" cy="${py(-.5)}" rx="${2*62.5}" ry="${2/Math.sqrt(7)*238/6}" fill="none" stroke="${C.muted}" stroke-dasharray="5 5" stroke-width="2"/><path d="${s.path.map((p,i)=>`${i?'L':'M'}${px(p.m[0])},${py(p.m[1])}`).join(' ')}" fill="none" stroke="${C.accent}" stroke-width="2"/><ellipse cx="${px(s.m[0])}" cy="${py(s.m[1])}" rx="${s.c[0]*125}" ry="${s.c[1]*238/3}" fill="${C.soft}" fill-opacity=".55" stroke="${C.accent}" stroke-width="2"/><circle cx="${px(s.m[0])}" cy="${py(s.m[1])}" r="4" fill="${C.accent}"/>${text(72,300,'Solid: approximation · Dashed: target · Ellipses: two standard deviations','tiny-label')}${line(70,367,570,367)}<path d="${s.loss.map((v,i)=>`${i?'L':'M'}${70+i/80*500},${355-v/10*37}`).join(' ')}" stroke="${C.accent}" fill="none" stroke-width="2"/>${text(70,394,'KL divergence across computed steps','tiny-label')}${text(568,394,`${steps} / 80`,'tiny-label','text-anchor="end"')}`,'0 0 640 414');
 ui.read.innerHTML=reading(steps?'Mean and uncertainty move together.':'Start away from the target.',steps?'The surface and its KL error come from the update equations. The guarantee in the paper depends on its assumptions, not the smoothness of this picture.':'The approximation must adjust both where it is centred and how uncertain it is.',metric('KL divergence',f(s.kl))+metric('Mean',`${f(s.m[0],2)}, ${f(s.m[1],2)}`)+metric('Standard deviations',`${f(s.c[0],2)}, ${f(s.c[1],2)}`));
 root.querySelector('#iterations').value=steps;root.querySelector('#iterations-value').value=steps;root.querySelector('#geometry').value=method;
 }
 bind(root,'#iterations','input',e=>{steps=+e.target.value;explore('Each position recomputes the actual optimization trajectory.');draw();});bind(root,'[data-action="step"]','click',()=>{steps=Math.min(80,steps+1);explore();draw();});bind(root,'#geometry','change',e=>{method=e.target.value;explore('The target and starting point are fixed. Only the update geometry changes.');draw();});draw();return{stage:i=>{steps=[0,1,20,60][i];method='natural';draw();},reset:()=>{steps=0;method='natural';draw();}};
}
function urban(root,explore){
 let region=0,parking=0;const ui=shell(root,`<label class="control" for="region"><span>Neighbourhood</span><select id="region"><option value="0">Dense centre</option><option value="1">Residential streets</option><option value="2">Outer district</option></select></label>`+range('parking','Van parking search',0,10,0,.5,' min'),'A schematic neighbourhood and invented service times—not a map, a routing forecast, or measurements from the paper. Vehicle choice also depends on capacity, distance and operational constraints not modelled here.','<p>Service time = travel + parking + final walk. Travel = 60 × distance / speed. The chosen scenarios hold route length equal between vehicles, then use explicit, illustrative speeds and stop overheads. No city-wide average is substituted for local conditions.</p>');
 function draw(){const s=urbanExample(region,parking);root.dataset.state=JSON.stringify({...s,region});const centers=[[195,88],[320,88],[445,88],[132,197],[257,197],[382,197],[507,197]],selected=[1,4,6][region];
 ui.viz.innerHTML=svg(`<title>A schematic micro-region and service-time components</title>${centers.map(([x,y],i)=>{const points=Array.from({length:6},(_,j)=>[x+66*Math.cos((30+j*60)*Math.PI/180),y+66*Math.sin((30+j*60)*Math.PI/180)].join(',')).join(' ');return `<polygon points="${points}" fill="${i===selected?C.soft:'#edf1ef'}" stroke="white" stroke-width="6"/>${i===selected?text(x,y+6,'Selected','accent-label','text-anchor="middle"'):''}`;}).join('')}${text(320,290,s.name,'strong-label','text-anchor="middle"')}`,'0 0 640 310')+`<div>${[['Delivery van',s.van,s.vanTotal],['Cargo bike',s.bike,s.bikeTotal]].map(([name,parts,total])=>`<div class="service-row"><span>${name}</span><div class="service-bar">${parts.map((t,i)=>`<span title="${['Travel','Parking','Walk'][i]}: ${f(t,1)} minutes" style="width:${t/23*100}%;background:${[C.accent,C.muted,C.line][i]}"></span>`).join('')}</div><strong>${f(total,1)} min</strong></div>`).join('')}<p class="legend">Dark: travel · Medium: parking · Light: final walk</p></div>`;
 ui.read.innerHTML=reading(s.vanTotal<s.bikeTotal?'Here, the van is faster.':'Here, the bike is faster.','Change the parking time or neighbourhood. The components—not the vehicle label alone—determine the result.',metric('Van service time',f(s.vanTotal,1),'minutes')+metric('Bike service time',f(s.bikeTotal,1),'minutes')+metric('Route length',f(s.distance,1),'km'));
 root.querySelector('#region').value=region;root.querySelector('#parking').value=parking;root.querySelector('#parking-value').value=`${f(parking,1)} min`;
 }
 bind(root,'#region','change',e=>{region=+e.target.value;parking=[7,3,1][region];explore('Local context changes the balance between travel and stop overhead.');draw();});bind(root,'#parking','input',e=>{parking=+e.target.value;explore('Only parking search changes; the other components stay fixed.');draw();});draw();return{stage:i=>{region=i<2?0:2;parking=[0,7,1,1][i];draw();},reset:()=>{region=0;parking=0;draw();}};
}
function caseDemo(root,explore){
 let s=newCase();refreshCase(s);const ui=shell(root,button('interpret','Read model interpretation')+button('attempt','Attempt the action')+button('correct','Record reviewed correction')+button('untrusted','Try model-only correction','quiet-button')+button('amend','Change the invoice','quiet-button'),'A synthetic, browser-local explanation of authority and selective replay. This does not connect to the CasePath application, send payments, or establish legal or operational correctness.','<p>A cached node is recomputed only if its input signature changes. The gate requires a human-authoritative date matching the original source, coverage within the stated period, a reviewed invoice, and a proposed amount matching that invoice. Source text is never overwritten by a model interpretation.</p>');
 function draw(){root.dataset.state=JSON.stringify(s);const ready=s.nodes.gate.value,conflict=s.parsed&&s.parsed!==s.source.date;ui.viz.innerHTML=`<div class="source-panels"><article class="source-document"><p class="document-label">Original source · unchanged</p><h4>Repair claim</h4><p>${esc(s.source.text)}</p><span class="date-value">12 May 2026</span><p class="document-small">Policy ends 31 May 2026.</p></article><article class="source-document ${conflict?'conflict':''}"><p class="document-label">Stored model interpretation</p><h4>${s.parsed?'Proposes CHF 420':'Not interpreted yet'}</h4><span class="date-value">${s.parsed?'12 June 2026':'—'}</span><p class="document-small">${s.review?`Correction: 12 May · ${s.review.authority==='human'?'human-reviewed':'model only'}`:'Interpretation is not authority.'}</p></article></div><div class="dag">${[['date','Reviewed date'],['coverage','Coverage'],['invoice','Invoice'],['gate','Action gate']].map(([id,label])=>`<div class="dag-node ${s.nodes[id].changed?'changed':''} ${!s.nodes[id].value?'failed':''}"><span>${label}</span><strong>${s.nodes[id].value?'Satisfied':'Unresolved'}</strong><small>v${s.nodes[id].version} · ${s.nodes[id].changed?'recomputed':'retained'}</small></div>`).join('')}</div><div class="status-line ${ready?'':'warning'}">${ready?'A human decision is admissible. No payment has been sent.':s.attempts?'Action refused. A plausible proposal is not permission to act.':'Action blocked until the evidence obligations are resolved.'}</div><div class="journal-heading">Decision journal</div><ol class="journal">${s.events.length?s.events.slice(-4).map(t=>`<li>${esc(t)}</li>`).join(''):'<li>Original source and policy received. No action authorized.</li>'}</ol>`;
 ui.read.innerHTML=reading(ready?'Correct the authority. Replay the dependency.':'The answer is not the permission.',ready?'The reviewed date changes the date and coverage checks. The invoice check keeps its version because its inputs did not change.':'The source and interpretation are separate records. A second model suggestion cannot replace the missing human review.',metric('Action',ready?'Admissible':'Blocked')+metric('Invoice check',`v${s.nodes.invoice.version}`)+metric('Source modified','Never'));
 }
 ['interpret','attempt','correct','untrusted','amend'].forEach(action=>bind(root,`[data-action="${action}"]`,'click',()=>{caseAction(s,action);explore(action==='untrusted'?'The corrected text alone is not enough. Its authority matters.':action==='amend'?'The changed invoice invalidates the amount obligation without changing the source.':'Follow the journal and the node versions.');draw();}));draw();return{stage:i=>{s=newCase();refreshCase(s);if(i>=1)caseAction(s,'interpret');if(i>=2)caseAction(s,'attempt');if(i===3)caseAction(s,'correct');draw();},reset:()=>{s=newCase();refreshCase(s);draw();}};
}
const factories={gain,bounds,interaction,replay,rank,time,natural,urban,case:caseDemo};
export async function mountDemo(work,root,onExplore){if(work.mechanism==='world'){const{mountWorld}=await import('./world.mjs?v=scroll-4.2.2');return mountWorld(root,onExplore);}const factory=factories[work.mechanism];if(!factory)throw new Error(`Unknown mechanism: ${work.mechanism}`);const model=factory(root,onExplore),scene=mountProjectScene(work,root);return {...model,dispose(){model.dispose?.();scene.dispose();}};}
