import {periods,works,byId,checkedAt} from './content.mjs?v=studio-2';
export const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
export const external = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12"/></svg>';
export const back = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M19 12H5m6-6-6 6 6 6"/></svg>';
export const play = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m9 5 10 7-10 7V5Z"/></svg>';
export const workLink = (w,cls='')=>`<a class="${cls}" href="#work/${esc(w.id)}" data-work="${esc(w.id)}">${esc(w.title)}${arrow}</a>`;
export function contact(){return `<section class="contact" id="contact" aria-labelledby="contact-title"><p class="overline">Let’s talk</p><h2 id="contact-title">An idea worth understanding.<br>A system worth building.</h2><a class="contact-link" href="mailto:navish.kumar@unibas.ch">navish.kumar@unibas.ch ${external}</a><p>Research, collaboration, and difficult questions welcome.</p></section>`;}
export function home(){return `<section class="hero" id="top"><div><h1 tabindex="-1">How can a system change<br class="wide-break"> without losing what matters?</h1></div><div class="hero-bio"><p>I’m Navish Kumar, a machine-learning researcher at the University of Basel.</p><p>I study how learning systems change—and build tools that make that change inspectable.</p><a href="#timeline" class="text-link">Explore the work ${arrow}</a></div></section>
<section class="timeline" id="timeline" aria-labelledby="timeline-title"><div class="timeline-intro"><h2 id="timeline-title">A body of work, in motion.</h2><p>Choose an idea. Change something. See what follows.</p></div><nav class="period-nav" aria-label="Timeline periods">${periods.map(p=>`<a href="#${p.id}">${p.title}</a>`).join('')}</nav><div class="periods">${periods.map(p=>`<section class="period" id="${p.id}" aria-labelledby="heading-${p.id}"><header class="period-heading"><span class="timeline-dot" aria-hidden="true"></span><p class="period-time">${p.time}</p><h3 id="heading-${p.id}">${p.title}<span>${p.subtitle}</span></h3><p class="period-description">${p.description}</p></header><ol class="work-list">${works.filter(w=>w.period===p.id).map(w=>`<li><a class="work-row" href="#work/${w.id}" data-work="${w.id}"><span class="work-year">${w.year==='Frontier'?'Prototype / direction':w.year}</span><h4>${esc(w.title)}${arrow}</h4><p>${esc(w.summary)}</p><span class="work-cta">Explore the idea ${arrow}</span></a></li>`).join('')}</ol></section>`).join('')}</div></section>${contact()}`;}
export function detail(w){const p=periods.find(p=>p.id===w.period);return `<div class="work-page" data-work-page="${w.id}"><div class="work-location"><a href="#timeline" data-back class="back-link">${back} Back to timeline</a><p>${p.title}<span>/</span>${p.subtitle}</p></div><header class="work-hero"><p class="work-meta">${esc(w.year)} <span aria-hidden="true">·</span> ${esc(w.status)}</p><h1 tabindex="-1">${esc(w.question)}</h1><p class="formal-title">${esc(w.fullTitle)}</p></header>
<section class="experience" aria-label="Interactive explanation of ${esc(w.title)}"><div class="experience-header"><p>${w.mechanism==='world'?'Persistent spatial prototype':'Live explanation'}<span>${w.mechanism==='world'?'A real scene; a limited command grammar':'Computed locally · illustrative, not paper measurements'}</span></p><div class="experience-actions"><button type="button" class="button play-button" data-play>${play}<span>Play explanation</span></button><button type="button" class="quiet-button" data-reset>Reset</button></div></div><div class="guide-steps" aria-label="Explanation stages">${w.guide.map((g,i)=>`<button type="button" data-stage="${i}" aria-current="${i===0?'step':'false'}"><span class="step-number">${i+1}</span><span>${esc(g.title)}</span></button>`).join('')}</div><div class="guide-copy" aria-live="polite"><strong>${esc(w.guide[0].title)}.</strong> ${esc(w.guide[0].text)}</div><div id="demo-root" class="demo-root" data-mechanism="${w.mechanism}"></div></section>
<section class="contribution" aria-labelledby="contribution-title"><div><p class="overline" id="contribution-title">My part in this work</p><p class="role">${esc(w.role)}</p></div><div><h2>${esc(w.contribution)}</h2><p>${esc(w.application)}</p></div></section>
<section class="evidence-section" aria-label="Evidence and limits"><details><summary>What the work establishes—and what this example does not <span>Read the evidence ${arrow}</span></summary><div class="evidence-body"><div><h3>The record</h3><p>${esc(w.demonstrated)}</p><h3>The boundary</h3><p>${esc(w.limitation)}</p>${w.currentExperiment?`<h3>Current question / example</h3><p>${esc(w.currentExperiment)}</p>`:''}</div><div><h3>Sources and implementation</h3>${w.sources.length?`<ul class="sources">${w.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ${external}</a><p>${esc(s.scope)}</p></li>`).join('')}</ul>`:'<p>A working prototype of a research direction—not a published result. The running implementation is the evidence for the interface mechanics only.</p>'}<a class="text-link" href="https://github.com/KumarNavish/KumarNavish.github.io/tree/master/modules" target="_blank" rel="noopener noreferrer">Inspect this website’s calculations ${external}</a><p class="source-date">Source distinctions reviewed ${checkedAt}. Unretrieved records are explicitly identified above.</p></div></div></details></section>
<section class="connections" aria-labelledby="connections-title"><div class="connections-heading"><h2 id="connections-title">Where this sits in the journey</h2><p>Conceptual connections, not claims of direct derivation.</p></div><div class="connection-rail"><div><p class="overline">Came from</p>${w.predecessor.length?w.predecessor.map(id=>workLink(byId[id],'connection-link')).join(''):'<p class="connection-start">Observing relationships<br>inside complex systems.</p>'}</div><div class="connection-current"><p class="overline">This work</p><p>${esc(w.title)}</p><small>${p.title} / ${esc(w.year)}</small></div><div><p class="overline">Leads toward</p>${w.successors.length?w.successors.map(id=>workLink(byId[id],'connection-link')).join(''):`<p class="connection-start">${esc(w.nextQuestion)}</p>`}</div></div></section><div class="page-end"><a href="#timeline" data-back class="back-link">${back} Return to the whole timeline</a><a href="mailto:navish.kumar@unibas.ch" class="text-link">Discuss this work ${external}</a></div></div>`;}
export function notFound(){return `<section class="not-found"><h1>That work is not on the timeline.</h1><p>The link may be incomplete or out of date. Every current entry is available on the main timeline.</p><a class="button" href="#timeline">Back to the timeline ${arrow}</a></section>`;}
