/** Small inspectable 3D engine. WebGL shading and a normal-lit, depth-buffered CPU fallback.
 * Geometry is native and state-driven; no screenshots masquerade as interactive scenes. */
export const V={add:(a,b)=>a.map((v,i)=>v+b[i]),sub:(a,b)=>a.map((v,i)=>v-b[i]),mul:(a,s)=>a.map(v=>v*s),dot:(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{const n=Math.hypot(...a)||1;return a.map(v=>v/n);}};
const {add,sub,mul,dot,cross,norm}=V;
export const mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
export const palette={jade:'#178f87',mint:'#8ed9c4',ice:'#b6dbdd',ink:'#193e47',red:'#db684b',gold:'#c59b61',white:'#f3f5ed',steel:'#759a9f',pale:'#dce7e3',violet:'#887fa7'};
export const rgb=c=>Array.isArray(c)?c:[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255);
export function meshBuilder(){
 const data=[],labels=[],pickables=[],shadows=[];
 function tri(a,b,c,color,normals){const n=norm(cross(sub(b,a),sub(c,a))),col=rgb(color);[a,b,c].forEach((p,i)=>data.push(...p,...(normals?normals[i]:n),...col));}
 function quad(a,b,c,d,color,ns){tri(a,b,c,color,ns&&[ns[0],ns[1],ns[2]]);tri(a,c,d,color,ns&&[ns[0],ns[2],ns[3]]);}
 function box(p,size,color,bevel=.06){const half=size.map(x=>x/2),r=Math.min(bevel,...half),core=half.map(x=>x-r),n=4;
  for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const u=(axis+1)%3,v=(axis+2)%3;const at=(i,j)=>{const q=[0,0,0];q[axis]=sign*half[axis];q[u]=(i/n*2-1)*half[u];q[v]=(j/n*2-1)*half[v];const base=q.map((x,k)=>Math.max(-core[k],Math.min(core[k],x))),normal=norm(sub(q,base));return [add(p,add(base,mul(normal,r))),normal];};for(let i=0;i<n;i++)for(let j=0;j<n;j++){let corners=[at(i,j),at(i+1,j),at(i+1,j+1),at(i,j+1)];if(sign<0)corners.reverse();quad(...corners.map(c=>c[0]),color,corners.map(c=>c[1]));}}
 }
 function ellipsoid(p,scale,color,segments=24,rings=12){const point=(i,j)=>{const t=j/rings*Math.PI,q=i/segments*Math.PI*2,n=[Math.sin(t)*Math.cos(q),Math.cos(t),Math.sin(t)*Math.sin(q)];return[add(p,n.map((v,k)=>v*scale[k])),norm(n.map((v,k)=>v/scale[k]))];};for(let j=0;j<rings;j++)for(let i=0;i<segments;i++){const vs=[point(i,j),point(i+1,j),point(i+1,j+1),point(i,j+1)];quad(...vs.map(v=>v[0]),color,vs.map(v=>v[1]));}}
 function sphere(p,r,color,n=20){ellipsoid(p,[r,r,r],color,n,Math.max(8,n/2));}
 function tube(path,r,color,sides=8){if(path.length<2)return;const frames=path.map((p,i)=>{const dir=norm(sub(path[Math.min(i+1,path.length-1)],path[Math.max(0,i-1)])),u=norm(cross(dir,Math.abs(dir[1])>.95?[1,0,0]:[0,1,0])),v=cross(dir,u);return Array.from({length:sides},(_,j)=>{const n=add(mul(u,Math.cos(j/sides*Math.PI*2)),mul(v,Math.sin(j/sides*Math.PI*2)));return[add(p,mul(n,r)),n];});});for(let i=0;i<frames.length-1;i++)for(let j=0;j<sides;j++){const k=(j+1)%sides,vs=[frames[i][j],frames[i][k],frames[i+1][k],frames[i+1][j]];quad(...vs.map(v=>v[0]),color,vs.map(v=>v[1]));}}
 const cylinder=(a,b,r,c,n=16)=>{tube([a,b],r,c,n);const axis=norm(sub(b,a)),u=norm(cross(axis,Math.abs(axis[1])>.95?[1,0,0]:[0,1,0])),v=cross(axis,u);for(let i=0;i<n;i++){const at=j=>add(mul(u,Math.cos(j/n*Math.PI*2)*r),mul(v,Math.sin(j/n*Math.PI*2)*r));tri(a,add(a,at(i+1)),add(a,at(i)),c,Array(3).fill(mul(axis,-1)));tri(b,add(b,at(i)),add(b,at(i+1)),c,Array(3).fill(axis));}};
 function ring(p,r,c,thickness=.026,plane='xz',start=0,end=Math.PI*2){const points=Array.from({length:65},(_,i)=>{const a=start+(end-start)*i/64;return add(p,plane==='xy'?[r*Math.cos(a),r*Math.sin(a),0]:plane==='yz'?[0,r*Math.cos(a),r*Math.sin(a)]:[r*Math.cos(a),0,r*Math.sin(a)]);});tube(points,thickness,c,7);return points;}
 function curve(a,b,lift=1){return Array.from({length:25},(_,i)=>{const t=i/24,p=mix(a,b,t);p[1]+=Math.sin(t*Math.PI)*lift;return p;});}
 function arrow(a,b,c,r=.035){const d=norm(sub(b,a)),u=norm(cross(d,Math.abs(d[1])>.9?[1,0,0]:[0,1,0])),v=cross(d,u),base=sub(b,mul(d,.23));cylinder(a,base,r,c,8);for(let i=0;i<12;i++){const f=j=>add(base,add(mul(u,Math.cos(j/12*Math.PI*2)*r*3),mul(v,Math.sin(j/12*Math.PI*2)*r*3)));tri(f(i),f(i+1),b,c);}}
 function label(id,p,text,kind='normal',detail=''){labels.push({id,p,text,kind,detail});}
 function pick(id,p,r=.6){pickables.push({id,p,r});}
 function shadow(p,r=.6,strength=.22){shadows.push({p,r,strength});}
 function floor(size=9,y=-.11){const n=42,h=size/2,col=rgb('#e9eeeb');const at=(i,j)=>{const x=(i/n*2-1)*h,z=(j/n*2-1)*h;let shade=0;for(const s of shadows){const d=((x-s.p[0])**2+(z-s.p[2])**2)/(s.r*s.r);shade+=s.strength*Math.exp(-d*1.8);}const color=col.map(c=>c*(1-Math.min(.34,shade)));return {p:[x,y,z],c:color};};for(let i=0;i<n;i++)for(let j=0;j<n;j++){const pts=[at(i,j),at(i,j+1),at(i+1,j+1),at(i+1,j)];for(const ids of [[0,1,2],[0,2,3]])for(const k of ids)data.push(...pts[k].p,0,1,0,...pts[k].c);}}
 function line(a,b,c='#c3d4d0',r=.009){tube([a,b],r,c,5);}
 function grid(size=7,step=1,y=-.09){for(let i=-size/2;i<=size/2+.01;i+=step){line([i,y,-size/2],[i,y,size/2]);line([-size/2,y,i],[size/2,y,i]);}}
 return{data,labels,pickables,tri,quad,box,ellipsoid,sphere,tube,cylinder,ring,curve,arrow,label,pick,shadow,floor,grid,line};
}
function matmul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function lookAt(e,t){const z=norm(sub(e,t)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]);}
function perspective(aspect){const t=1/Math.tan(.59/2),near=.1,far=70;return new Float32Array([t/aspect,0,0,0,0,t,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);}
const VS=`attribute vec3 p;attribute vec3 n;attribute vec3 c;uniform mat4 m;varying vec3 N;varying vec3 C;varying vec3 P;void main(){P=p;N=n;C=c;gl_Position=m*vec4(p,1.0);}`;
const FS=`precision mediump float;varying vec3 N;varying vec3 C;varying vec3 P;uniform vec3 eye;uniform float intensity;uniform vec3 tint;void main(){vec3 n=normalize(N),v=normalize(eye-P),l=normalize(vec3(-.6,1.4,.8));float a=max(dot(n,l),0.0),b=max(dot(n,normalize(vec3(1.0,.5,-.8))),0.0),spec=pow(max(dot(n,normalize(l+v)),0.0),42.0);vec3 linear=pow(C,vec3(2.2))*(.62+.45*a+.17*b);linear+=vec3(.22)*spec;linear*=intensity*tint;vec3 color=pow(linear,vec3(1.0/2.2));float fog=clamp((length(eye-P)-12.0)*.013,0.0,.12);gl_FragColor=vec4(mix(color,vec3(.957,.973,.965),fog),1.0);}`;
export function createStudio(canvas,labelLayer,{onPick=()=>{},onCamera=()=>{},onSelect=null,onDrag=null,camera:initial={}}={}){
 let gl=null,ctx=null,program,buffer,shaders=[],mesh=null,matrix,eye,disposed=false,contextLost=false;
 const camera={yaw:.48,pitch:.53,distance:12,target:[0,.75,0],...initial};const home=JSON.parse(JSON.stringify(camera));
 try{gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:false});}catch{}
 if(gl){const sh=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));shaders.push(s);return s;};program=gl.createProgram();gl.attachShader(program,sh(gl.VERTEX_SHADER,VS));gl.attachShader(program,sh(gl.FRAGMENT_SHADER,FS));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('3D shader linking failed');gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);['p','n','c'].forEach((name,i)=>{const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,36,i*12);});gl.enable(gl.DEPTH_TEST);}
 else ctx=canvas.getContext('2d',{alpha:false});
 if(!gl&&!ctx)throw Error('3D rendering is unavailable. The controls and computed results remain available.');
 const mode=gl?'webgl':'software-3d';canvas.dataset.renderer=mode;
 function project(p){if(!matrix)return null;const q=[0,0,0,0],v=[...p,1];for(let r=0;r<4;r++)for(let c=0;c<4;c++)q[r]+=matrix[c*4+r]*v[c];if(q[3]<.1)return null;return{x:(q[0]/q[3]*.5+.5)*(canvas.clientWidth||640),y:(.5-q[1]/q[3]*.5)*(canvas.clientHeight||440),depth:q[3]};}
 function software(w,h){const intensity=mesh.lighting==='night'?.36:mesh.lighting==='day'?1.05:1,tint=mesh.lighting==='sunset'?[1.08,1,.92]:mesh.lighting==='night'?[.8,.9,1]:[1,1,1];const image=ctx.createImageData(w,h),pixels=image.data,zbuf=new Float32Array(w*h),d=mesh.data,light=norm([-.6,1.4,.8]),fill=norm([1,.5,-.8]),sx=w/canvas.clientWidth,sy=h/canvas.clientHeight;
  for(let y=0;y<h;y++){const f=y/h;for(let x=0;x<w;x++){const k=(y*w+x)*4;pixels[k]=mesh.lighting==='night'?34-f*4:246-f*6;pixels[k+1]=mesh.lighting==='night'?49-f*5:249-f*5;pixels[k+2]=mesh.lighting==='night'?61-f*5:247-f*5;pixels[k+3]=255;}}
  const shade=(i,p)=>{const n=norm(d.slice(i+3,i+6)),v=norm(sub(eye,p)),a=Math.max(0,dot(n,light)),b=Math.max(0,dot(n,fill)),sp=Math.pow(Math.max(0,dot(n,norm(add(light,v)))),42)*.22;return d.slice(i+6,i+9).map((c,k)=>Math.min(255,Math.pow((Math.pow(c,2.2)*(.62+.45*a+.17*b)+sp)*intensity*tint[k],1/2.2)*255));};
  const edge=(a,b,x,y)=>(b.x-a.x)*(y-a.y)-(b.y-a.y)*(x-a.x);
  for(let i=0;i<d.length;i+=27){const pos=[0,9,18].map(j=>d.slice(i+j,i+j+3)),pts=pos.map(project);if(pts.some(p=>!p))continue;for(const p of pts){p.x*=sx;p.y*=sy;}const[a,b,c]=pts,area=edge(a,b,c.x,c.y);if(Math.abs(area)<.002)continue;const cols=pos.map((p,j)=>shade(i+j*9,p));const x0=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),x1=Math.min(w-1,Math.ceil(Math.max(a.x,b.x,c.x))),y0=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),y1=Math.min(h-1,Math.ceil(Math.max(a.y,b.y,c.y)));
   for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const u=edge(b,c,x+.5,y+.5)/area,v=edge(c,a,x+.5,y+.5)/area,t=1-u-v;if(u<-.0001||v<-.0001||t<-.0001)continue;const z=u/a.depth+v/b.depth+t/c.depth,k=y*w+x;if(z<=zbuf[k])continue;zbuf[k]=z;for(let ch=0;ch<3;ch++)pixels[k*4+ch]=(u*cols[0][ch]/a.depth+v*cols[1][ch]/b.depth+t*cols[2][ch]/c.depth)/z;}
  }ctx.putImageData(image,0,0);
 }
 function labels(){if(!labelLayer)return;labelLayer.replaceChildren();const w=canvas.clientWidth,h=canvas.clientHeight,placed=[];for(const l of mesh.labels){const p=project(l.p);if(!p||p.x<8||p.x>w-8||p.y<5||p.y>h-14)continue;const el=document.createElement('span');el.className='scene-label '+l.kind;el.dataset.label=l.id;el.textContent=l.text;labelLayer.append(el);const bw=el.offsetWidth,bh=el.offsetHeight,x=Math.max(bw/2+8,Math.min(w-bw/2-8,p.x));let y=p.y;
   for(let attempt=0;attempt<8&&placed.some(b=>Math.abs(x-b.x)<(bw+b.w)/2+8&&Math.abs(y-b.y)<(bh+b.h)/2+5);attempt++)y-=bh+7;
   y=Math.max(bh+9,y);el.style.left=x+'px';el.style.top=y+'px';placed.push({x,y,w:bw,h:bh});
  }}
 function render(){if(disposed||!mesh||contextLost)return;const start=performance.now(),w=canvas.clientWidth||640,h=canvas.clientHeight||440,dpr=gl?Math.min(devicePixelRatio||1,1.75):Math.min(1.6,Math.sqrt((drag?.moved?200000:600000)/(w*h))),rw=Math.max(1,Math.round(w*dpr)),rh=Math.max(1,Math.round(h*dpr));if(canvas.width!==rw||canvas.height!==rh){canvas.width=rw;canvas.height=rh;}
  const distance=camera.distance*(w/h<1.15?1.15/(w/h):1);eye=add(camera.target,[distance*Math.sin(camera.yaw)*Math.cos(camera.pitch),distance*Math.sin(camera.pitch),distance*Math.cos(camera.yaw)*Math.cos(camera.pitch)]);matrix=matmul(perspective(w/h),lookAt(eye,camera.target));
  if(gl){gl.useProgram(program);gl.viewport(0,0,rw,rh);gl.uniformMatrix4fv(gl.getUniformLocation(program,'m'),false,matrix);gl.uniform3fv(gl.getUniformLocation(program,'eye'),eye);gl.uniform1f(gl.getUniformLocation(program,'intensity'),mesh.lighting==='night'?.36:mesh.lighting==='day'?1.05:1);gl.uniform3fv(gl.getUniformLocation(program,'tint'),mesh.lighting==='sunset'?[1.08,1,.92]:mesh.lighting==='night'?[.8,.9,1]:[1,1,1]);if(mesh.lighting==='night')gl.clearColor(.13,.19,.24,1);else gl.clearColor(.964,.976,.97,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,mesh.data.length/9);gl.flush();}else software(rw,rh);labels();canvas.dataset.rendered=mode;canvas.dataset.vertices=mesh.data.length/9;canvas.dataset.camera=JSON.stringify(camera);canvas.dataset.renderMs=(performance.now()-start).toFixed(1);canvas.dataset.pickTargets=JSON.stringify(mesh.pickables.map(p=>({id:p.id,...project(p.p)})));
 }
 function pickAt(x,y){return mesh.pickables.map(o=>({o,p:project(o.p)})).filter(o=>o.p).map(h=>({...h,d:Math.hypot(h.p.x-x,h.p.y-y)})).filter(h=>h.d<Math.max(25,h.o.r*canvas.clientWidth/h.p.depth*1.6)).sort((a,b)=>a.d-b.d)[0]?.o;}
 function plane(x,y,height){const forward=norm(sub(camera.target,eye)),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),f=Math.tan(.59/2),dir=norm(add(forward,add(mul(right,(x/canvas.clientWidth*2-1)*f*canvas.clientWidth/canvas.clientHeight),mul(up,(1-y/canvas.clientHeight*2)*f))));const d=(height-eye[1])/dir[1];return d>0?add(eye,mul(dir,d)):null;}
 let drag=null;const listeners=[];function listen(type,fn,opts){canvas.addEventListener(type,fn,opts);listeners.push([type,fn,opts]);}
 listen('pointerdown',e=>{if(e.button!==0)return;const rect=canvas.getBoundingClientRect(),hit=onDrag?pickAt(e.clientX-rect.left,e.clientY-rect.top):null;drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,hit,delta:null};if(hit)onSelect?.(hit.id);canvas.setPointerCapture(e.pointerId);});
 listen('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4)drag.moved=true;if(drag.moved){if(drag.hit){const rect=canvas.getBoundingClientRect(),a=plane(drag.x-rect.left,drag.y-rect.top,drag.hit.p[1]),b=plane(e.clientX-rect.left,e.clientY-rect.top,drag.hit.p[1]);if(a&&b){drag.delta=sub(b,a);onDrag(drag.hit.id,drag.delta,false);}}else{camera.yaw-=dx*.007;camera.pitch=Math.max(.16,Math.min(1.35,camera.pitch+dy*.006));render();onCamera();}}drag.lastX=e.clientX;drag.lastY=e.clientY;});
 listen('pointerup',e=>{if(drag?.hit&&drag.moved&&drag.delta)onDrag(drag.hit.id,drag.delta,true);if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const hits=mesh.pickables.map(o=>({o,p:project(o.p)})).filter(o=>o.p).map(h=>({...h,d:Math.hypot(h.p.x-x,h.p.y-y)})).filter(h=>h.d<Math.max(25,h.o.r*canvas.clientWidth/h.p.depth*1.6)).sort((a,b)=>a.d-b.d);if(hits[0])onPick(hits[0].o.id);}const moved=drag?.moved;drag=null;if(moved)render();if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);});
 listen('pointercancel',()=>{drag=null;});
 listen('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();camera.distance=Math.max(7,Math.min(20,camera.distance+e.deltaY*.01));render();onCamera();},{passive:false});
 listen('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home'].includes(e.key))return;e.preventDefault();if(e.key==='Home')Object.assign(camera,JSON.parse(JSON.stringify(home)));else if(e.key==='+'||e.key==='-')camera.distance=Math.max(7,Math.min(20,camera.distance+(e.key==='+'?-.6:.6)));else if(e.key==='ArrowLeft'||e.key==='ArrowRight')camera.yaw+=e.key==='ArrowLeft'?-.18:.18;else camera.pitch=Math.max(.16,Math.min(1.35,camera.pitch+(e.key==='ArrowUp'?.1:-.1)));render();onCamera();});
 listen('webglcontextlost',e=>{e.preventDefault();contextLost=true;canvas.dataset.rendered='context-lost';});
 const resize=new ResizeObserver(()=>render());resize.observe(canvas);
 return{mode,project,render,set(next){mesh=next;if(gl&&!contextLost){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(mesh.data),gl.DYNAMIC_DRAW);}render();},camera(delta){Object.assign(camera,delta);render();},reset(){Object.assign(camera,JSON.parse(JSON.stringify(home)));render();},orbit(delta){camera.yaw+=delta;render();},zoom(delta){camera.distance=Math.max(7,Math.min(20,camera.distance+delta));render();},dispose(){disposed=true;resize.disconnect();listeners.forEach(([t,f,o])=>canvas.removeEventListener(t,f,o));if(gl){gl.deleteBuffer(buffer);gl.deleteProgram(program);shaders.forEach(s=>gl.deleteShader(s));gl.getExtension('WEBGL_lose_context')?.loseContext();}labelLayer?.replaceChildren();}};
}
