import {esc,arrow} from './render.mjs?v=scroll-4.2.1';
import {emptyWorld,copy,createLaboratory,moveObject,routeAgent,interpretCommand,diffWorld,validWorld,historyStore} from './world-model.mjs?v=scroll-4.2.1';
import {createWorldView} from './world-view.mjs?v=scroll-4.2.1';
const CREATE='Create a mountain laboratory at sunset. Put a microscope beside a robotic arm.';
const KEY='navish-spatial-world-v1';
export function mountWorld(root,onExplore){
 let initial=emptyWorld();try{const saved=JSON.parse(localStorage.getItem(KEY));if(validWorld(saved))initial=saved;}catch{}
 const store=historyStore(initial);let selected='microscope-1',renderer=null,recognition=null,disposed=false,preview=null,pathAnimation=0;
 root.innerHTML=`<div class="world-layout"><div class="world-view"><canvas aria-label="Interactive three-dimensional laboratory. Drag empty space to rotate; drag an object to move it." tabindex="0"></canvas><div class="world-labels" aria-hidden="true"></div><div class="world-corner">Perspective view <span data-light-name>Sunset</span></div><div class="world-help">Drag to orbit · + / − to zoom · Drag an object to move</div><div class="world-empty"><h3>One sentence.<br>A world you can keep editing.</h3><button class="button" type="button" data-create>Create the laboratory ${arrow}</button></div></div><aside class="world-panel"><h3>The same objects.</h3><p>Select one to inspect or move it.</p><div class="object-list" data-objects></div><div class="object-editor" data-editor></div></aside></div>
 <div class="world-command"><form class="command-form"><label class="command-label" for="world-input">Describe a change</label><div class="command-entry"><input id="world-input" name="command" maxlength="400" autocomplete="off" placeholder="Move the microscope closer to the window."><button class="button" type="submit">Apply ${arrow}</button></div></form><div class="command-examples"><span>Try</span>${[CREATE,'Move the microscope closer to the window.','Send the agent to the microscope.','Make it night.','Add a plant.'].map((v,i)=>`<button class="quiet-button" type="button" data-command="${esc(v)}">${['Create laboratory','Move microscope','Route agent','Change lighting','Add plant'][i]}</button>`).join('')}</div><p class="command-response" role="status" data-response>${initial.created?'Restored your last scene. Object identities are unchanged.':'Create the laboratory, then edit it in place.'}</p><div class="world-privacy"><button type="button" class="quiet-button" data-microphone>Use microphone</button><span>Optional browser speech recognition may send audio to its provider. Typed commands stay in this browser. No model API is called.</span></div></div>
 <div class="world-toolbar"><div><button class="small-button" type="button" data-undo>Undo</button><button class="small-button" type="button" data-redo>Redo</button><button class="small-button" type="button" data-export>Export scene</button></div><div><button class="small-button" type="button" data-orbit="-.35" aria-label="Rotate camera left">Rotate left</button><button class="small-button" type="button" data-orbit=".35" aria-label="Rotate camera right">Rotate right</button><button class="small-button" type="button" data-zoom="-1" aria-label="Zoom in">+</button><button class="small-button" type="button" data-zoom="1" aria-label="Zoom out">−</button></div></div>
 <div class="world-history"><section class="world-relations"><h4>Visible relations</h4><div data-relations></div></section><section class="world-revisions"><h4>State changes <span data-revision></span></h4><ol data-history></ol></section></div><p class="lab-footnote">Real 3D geometry and camera projection, persistent objects and reversible state changes. WebGL when available; depth-buffered software rendering otherwise. The language parser uses a limited local grammar; the route is a deterministic grid path around a fixed obstacle. This is not unrestricted generative AI, an autonomous agent, or a tested VR system.</p><details class="math-details"><summary>Inspect the scene graph</summary><pre class="formula" data-json></pre></details>`;
 const canvas=root.querySelector('canvas'),response=root.querySelector('[data-response]'),input=root.querySelector('#world-input');
 const say=message=>{response.textContent=message;};
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(store.state));}catch{say('The scene works, but this browser did not allow local persistence. Export preserves a copy.');}}
 function commit(next,label){if(store.commit(next,label)){preview=null;persist();draw();}else draw();}
 function run(command){onExplore('Language edits structured state. Existing object IDs survive each supported change.');const result=interpretCommand(store.state,command);if(result.ok)commit(result.state,command);say(result.message);if(result.ok&&/agent.*microscope/i.test(command))animateRoute();input.value='';}
 function animateRoute(){cancelAnimationFrame(pathAnimation);const s=store.state;if(!s.path.length||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const start=performance.now(),duration=Math.min(2600,Math.max(900,s.path.length*70));let last=-1;function tick(now){if(disposed)return;const t=Math.min(1,(now-start)/duration),index=Math.min(s.path.length-1,Math.floor(t*(s.path.length-1)));if(index!==last){const visual=copy(s);visual.objects.find(o=>o.id==='agent-1').position={...s.path[index]};renderer?.set(visual,selected);last=index;}if(t<1)pathAnimation=requestAnimationFrame(tick);else renderer?.set(store.state,selected);}pathAnimation=requestAnimationFrame(tick);}
 function draw(){cancelAnimationFrame(pathAnimation);if(disposed)return;const s=preview||store.state;root.dataset.state=JSON.stringify(s);root.querySelector('[data-light-name]').textContent=s.lighting;root.querySelector('.world-empty').hidden=s.created;root.querySelector('[data-revision]').textContent=`revision ${s.revision}`;
 root.querySelector('[data-objects]').innerHTML=s.objects.filter(o=>!['bench','window'].includes(o.type)).map(o=>`<button type="button" data-object="${esc(o.id)}" aria-pressed="${o.id===selected}"><span>${esc(o.name)}</span><small>${esc(o.id)}</small></button>`).join('')||'<p>No objects yet.</p>';
 const o=s.objects.find(o=>o.id===selected);root.querySelector('[data-editor]').innerHTML=o?`<p class="document-small">Coordinates in metres · y is fixed to the supporting surface.</p><div class="coordinate-fields">${['x','y','z'].map(k=>`<label>${k.toUpperCase()}<input type="number" step="0.1" ${k==='y'?'readonly':''} data-coordinate="${k}" aria-label="${esc(o.name)} ${k} coordinate" value="${o.position[k]}" min="-4" max="4"></label>`).join('')}</div>`:'';
 root.querySelector('[data-relations]').innerHTML=s.created?`<p>Microscope <strong>on</strong> workbench</p><p>Robotic arm <strong>on</strong> workbench</p><p>Microscope <strong>${Math.hypot(s.objects.find(o=>o.id==='microscope-1').position.x-s.objects.find(o=>o.id==='robotic-arm-1').position.x,s.objects.find(o=>o.id==='microscope-1').position.z-s.objects.find(o=>o.id==='robotic-arm-1').position.z).toFixed(2)} m from</strong> robotic arm</p>${s.path.length?`<p>Agent route <strong>${s.path.length-1} steps</strong> around bench</p>`:''}`:'<p>Objects and relations appear when the world is created.</p>';
 const records=store.records;root.querySelector('[data-history]').innerHTML=records.length?records.slice(-3).reverse().map(r=>`<li><strong>${esc(r.label)}</strong><span>${r.changes.map(esc).join(' · ')}</span></li>`).join(''):'<li>No edits in this visit. Changes will appear here.</li>';
 root.querySelector('[data-undo]').disabled=!store.past;root.querySelector('[data-redo]').disabled=!store.future;root.querySelector('[data-export]').disabled=!s.created;root.querySelector('[data-json]').textContent=JSON.stringify(s,null,2);renderer?.set(s,selected);
 }
 try{renderer=createWorldView(canvas,root.querySelector('.world-labels'),{select:id=>{selected=id;draw();},move:(id,p,done)=>{try{const next=moveObject(store.state,id,p);if(done){preview=null;commit(next,`Dragged ${id}`);say('Object moved; its identity is preserved. Inspect the recorded coordinate change below.');onExplore('Direct manipulation changes the same coordinates as a language command.');}else{preview=next;renderer.set(next,id);}}catch(e){preview=null;say(e.message);renderer.set(store.state,selected);}},camera:()=>onExplore('Camera motion changes your view—not the objects or their coordinates.')});}catch(e){canvas.hidden=true;root.querySelector('.world-view').insertAdjacentHTML('beforeend',`<p class="fallback-notice">${esc(e.message)} Use the coordinates and scene graph below.</p>`);}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-create'))run(CREATE);if(b.dataset.command)run(b.dataset.command);if(b.dataset.object){selected=b.dataset.object;onExplore('Each object has a stable identity and explicit spatial coordinates.');draw();}if(b.hasAttribute('data-undo')){store.undo();persist();draw();say('Previous world state restored.');onExplore();}if(b.hasAttribute('data-redo')){store.redo();persist();draw();say('Edit restored.');onExplore();}if(b.dataset.orbit){renderer?.rotate(+b.dataset.orbit);onExplore('The camera changes; world state does not.');}if(b.dataset.zoom){renderer?.zoom(+b.dataset.zoom);onExplore();}if(b.hasAttribute('data-export')){const blob=new Blob([JSON.stringify(store.state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='navish-laboratory-scene.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
 root.addEventListener('change',e=>{if(e.target.dataset.coordinate){try{const next=moveObject(store.state,selected,{[e.target.dataset.coordinate]:+e.target.value});commit(next,`Edited ${selected} coordinates`);say('Coordinates updated. The same object remains in the world.');onExplore('An explicit coordinate edit and a language edit operate on the same scene graph.');}catch(err){say(err.message);draw();}}});
 root.querySelector('form').addEventListener('submit',e=>{e.preventDefault();run(input.value);});
 canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','+','-'].includes(e.key)){e.preventDefault();if(e.key.startsWith('Arrow'))renderer?.rotate(e.key==='ArrowLeft'?-.2:.2);else renderer?.zoom(e.key==='+'?-.5:.5);onExplore('Keyboard camera controls leave the scene state unchanged.');}});
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition,mic=root.querySelector('[data-microphone]');
 if(!Speech){mic.disabled=true;mic.textContent='Speech unavailable in this browser';}else{mic.addEventListener('click',()=>{if(recognition){recognition.abort();recognition=null;mic.textContent='Use microphone';return;}recognition=new Speech();recognition.lang='en-US';recognition.interimResults=false;recognition.onresult=e=>{input.value=e.results[0][0].transcript;run(input.value);};recognition.onerror=e=>say(`Speech recognition: ${e.error}. Typed commands still work.`);recognition.onend=()=>{recognition=null;mic.textContent='Use microphone';};try{recognition.start();mic.textContent='Stop listening';say('Listening for one supported command.');}catch(e){say(`Speech did not start: ${e.message}`);recognition=null;}});}
 draw();return{stage(i){if(i===0){commit(createLaboratory(store.state),'Created laboratory');say('A persistent laboratory. Object IDs are visible beside the scene.');}else if(i===1){if(!store.state.created)commit(createLaboratory(store.state),'Created laboratory');const r=interpretCommand(store.state,'Move the microscope closer to the window.');if(r.ok)commit(r.state,'Moved microscope closer to window');say(r.message);}else if(i===2){if(!store.state.created)commit(createLaboratory(store.state),'Created laboratory');selected='microscope-1';renderer?.resetCamera();renderer?.rotate(.15);draw();say('The view changes. Object identity and coordinates remain inspectable.');}else{if(!store.state.created)commit(createLaboratory(store.state),'Created laboratory');commit(routeAgent(store.state),'Routed agent to microscope');animateRoute();say('The grid route ends beside the workbench, not inside it. No learned planning policy is used.');}},reset(){commit(createLaboratory(emptyWorld()),'Reset example');renderer?.resetCamera();say('Example restored. Undo can recover the previous scene.');},dispose(){disposed=true;cancelAnimationFrame(pathAnimation);recognition?.abort();renderer?.dispose();}};
}
