first_name: Navish
middle_name:
last_name: Kumar
title: blank
email: navish.kumar@unibas.ch
lang: en

url: https://kumarnavish.github.io
baseurl:
icon: ⚛️
description: >
  Crafted research portfolio of Navish Kumar: mathematical machine learning, urban systems modeling, and theory-to-practice AI.
footer_text: >
  Designed and maintained by Navish Kumar.
keywords: navish kumar, mathematical machine learning, variational inference, spectral graph theory, urban logistics modeling, social computing

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight

sass:
  style: compressed

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: assets
    values:
      sitemap: false

include:
  - _pages

exclude:
  - .bundle
  - .home
  - .jekyll-cache
  - .git
  - .github
  - _site
  - bin
  - vendor

keep_files:
  - CNAME
  - .nojekyll
