import test from 'node:test';import assert from 'node:assert/strict';
import {placeAnnotation,overlaps} from '../modules/worlds/label-layout.mjs';
const base={width:350,height:300,labelWidth:160,labelHeight:42,x:240,y:100};
test('an unobstructed annotation remains attached at its preferred location',()=>{const r=placeAnnotation(base);assert.deepEqual(r,{left:160,top:58,right:320,bottom:100});});
test('wrapped mobile annotation clears the actual memory readout',()=>{const obstacles=[{left:170,top:9,right:340,bottom:94}];const r=placeAnnotation({...base,obstacles});assert(r&&!overlaps(r,obstacles[0]));assert(r.left>=12&&r.right<=338);});
test('panel and earlier-label intersections have a valid separated layout',()=>{const obstacles=[{left:200,top:8,right:345,bottom:125},{left:8,top:230,right:342,bottom:290}];const a=placeAnnotation({...base,obstacles});assert(a);const b=placeAnnotation({...base,x:160,y:190,obstacles:[...obstacles,a]});assert(b);for(const o of [...obstacles,a])assert(!overlaps(b,o));});
test('overcrowded viewport returns no misleading overlapped annotation',()=>{assert.equal(placeAnnotation({...base,obstacles:[{left:0,top:0,right:350,bottom:300}]}),null);});
test('a narrow two-axis corridor is not incorrectly declared occluded',()=>{const p={width:277,height:194,labelWidth:98,labelHeight:50,x:220,y:132,obstacles:[{left:9,top:9,right:260,bottom:55},{left:9,top:122,right:268,bottom:184},{left:117,top:65,right:222,bottom:90}]};const r=placeAnnotation(p);assert(r);for(const o of p.obstacles)assert(!overlaps(r,o));assert(r.left>=12&&r.right<=265&&r.top>=12&&r.bottom<=182);});
test('boundary search agrees with exhaustive integer placement on small scenes',()=>{let seed=173;const next=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};for(let k=0;k<50;k++){const p={width:64,height:64,labelWidth:12,labelHeight:10,x:next(64),y:next(64),obstacles:Array.from({length:3},()=>{const left=next(50),top=next(50);return{left,top,right:left+next(14)+1,bottom:top+next(14)+1};})};let best=Infinity;for(let left=12;left<=40;left++)for(let top=12;top<=42;top++){const r={left,top,right:left+12,bottom:top+10};if(p.obstacles.every(o=>!overlaps(r,o)))best=Math.min(best,(left-(p.x-6))**2+(top-(p.y-10))**2);}const r=placeAnnotation(p);if(best===Infinity)assert.equal(r,null);else{assert(r);assert.equal((r.left-(p.x-6))**2+(r.top-(p.y-10))**2,best);}}});
