import test from 'node:test';import assert from 'node:assert/strict';
import {stories} from '../modules/narrative/chapters.mjs';
import {evaluateNarrative,progressFromAnchors,caseAt} from '../modules/narrative/model.mjs';
import {graphState,replayState,rankState,timeState} from '../modules/worlds/math.mjs';
import {valid,compile,isFree} from '../modules/worlds/compiler.mjs';
const near=(a,b,t=1e-8)=>assert(Math.abs(a-b)<t,`${a} != ${b}`);
for(const key of Object.keys(stories)){
 test(`${key}: declarative 4–7 chapter journey has complete reader-facing content`,()=>{const s=stories[key];assert(s.chapters.length>=4&&s.chapters.length<=7);assert.equal(s.cameras.length,s.chapters.length);assert.equal(s.targets.length,s.chapters.length);s.chapters.forEach(c=>{assert(c.title&&c.body&&c.cue);});});
 test(`${key}: scroll state is path-independent, including reverse and skipped chapters`,()=>{const points=[0,.03,.12,.27,.41,.57,.74,.83,.91,1],original=points.map(p=>JSON.stringify(evaluateNarrative(key,p)));for(const p of[1,.41,.91,0,.57,.03])evaluateNarrative(key,p);points.slice().reverse().forEach(p=>assert.equal(JSON.stringify(evaluateNarrative(key,p)),original[points.indexOf(p)]));});
 test(`${key}: reduced motion retains every chapter and finite computation`,()=>{const n=stories[key].chapters.length;for(let i=0;i<n;i++){const a=evaluateNarrative(key,i/(n-1)),b=evaluateNarrative(key,i/(n-1),{reduced:true});assert.deepEqual(a.science,b.science);assert.equal(b.index,i);assert(!JSON.stringify(b).includes('NaN'));}});
}
test('scroll normalization handles direct jumps and reverses identically',()=>{const a=[200,900,1700,2600];near(progressFromAnchors(200,a),0);near(progressFromAnchors(2600,a),1);near(progressFromAnchors(550,a),1/6);near(progressFromAnchors(1300,a),.5);near(progressFromAnchors(-50,a),0);near(progressFromAnchors(9000,a),1);assert.throws(()=>progressFromAnchors(0,[1,1]));});
test('gain scene withholds operator until after cycle transport and computes exact eigenvalues',()=>{const first=evaluateNarrative('gain',0),cycle=evaluateNarrative('gain',.4),operator=evaluateNarrative('gain',.6),end=evaluateNarrative('gain',1);assert.equal(first.reveal.operator,0);assert.equal(cycle.reveal.operator,0);assert(cycle.science.inconsistent>0);assert(operator.reveal.operator>.9);assert.deepEqual(operator.science,graphState(operator.science.angles));near(end.science.eigenvalues[0],0);});
test('replay teaches forgetting before oracle, then independent versus duplicated memories',()=>{const old=evaluateNarrative('replay',0),learn=evaluateNarrative('replay',.2),full=evaluateNarrative('replay',.8),bad=evaluateNarrative('replay',1);near(old.science.oldLoss,0);assert(learn.science.oldLoss>0);assert.equal(learn.reveal.oracle,0);near(full.science.unavailable,0);assert(bad.science.unavailable>0);assert.equal(bad.science.selected.length,2);assert.equal(bad.science.directions,1);});
test('infeasible rank has no repair or cost; solution is revealed after feasibility',()=>{const line=evaluateNarrative('rank',.2),plane=evaluateNarrative('rank',.4),volume=evaluateNarrative('rank',.6),solution=evaluateNarrative('rank',.8),limited=evaluateNarrative('rank',1);for(const f of[line,plane]){assert.equal(f.science.repair,null);assert.equal(f.science.cost,null);}assert(volume.science.feasible);assert.equal(volume.reveal.solution,0);assert(solution.reveal.solution>.9);assert(!limited.science.affordable);});
test('fixed-budget temporal story ends at an exactly optimal zero replay allocation',()=>{for(let i=0;i<=100;i++){const s=evaluateNarrative('time',i/100).science;assert.equal(s.replay+s.newUpdates,64);assert.equal(s.processed,64);}assert(evaluateNarrative('time',.2).science.benefit>0);assert(evaluateNarrative('time',.6).science.benefit<0);const end=evaluateNarrative('time',1).science;assert.equal(end.replay,0);assert.equal(end.oracle,0);});
test('CasePath reconstructs source conflict and scoped replay without accumulating versions',()=>{const a=caseAt(1),hold=caseAt(3),ready=caseAt(5);assert.equal(a.source.date,'2026-05-12');assert(!hold.nodes.gate.value);assert(ready.nodes.gate.value);assert.equal(hold.nodes.invoice.version,ready.nodes.invoice.version);assert(ready.nodes.date.version>hold.nodes.date.version);assert.deepEqual(ready.source,hold.source);assert(ready.report);assert.deepEqual(caseAt(5),ready);});
test('spatial sequence produces valid persistent identities and reversible causal edits',()=>{const world=evaluateNarrative('world',4/6).science,agent=evaluateNarrative('world',5/6).science,edit=evaluateNarrative('world',1).science;assert(valid(world));assert(valid(agent));assert(valid(edit));assert.deepEqual(world.objects.map(o=>o.id),edit.objects.map(o=>o.id));assert.deepEqual(agent.objects.find(o=>o.id==='arm-1'),edit.objects.find(o=>o.id==='arm-1'));assert.notDeepEqual(agent.objects.find(o=>o.id==='microscope-1').position,edit.objects.find(o=>o.id==='microscope-1').position);assert.equal(edit.path.length,0);for(const p of agent.path)assert(isFree(agent,p.x,p.z));});
