from pathlib import Path
import json,hashlib,subprocess
r=Path.cwd();p=r/'modules/worlds/stage.mjs';s=p.read_text();old="canvas.dataset.camera=cam.position.toArray().map(v=>v.toFixed(3)).join(',');";new=old+"canvas.dataset.projection=JSON.stringify({fov:cam.fov,aspect:cam.aspect,near:cam.near,far:cam.far,target:controls.target.toArray()});";assert old in s;p.write_text(s.replace(old,new))
p=r/'scripts/referent_checks.py';s=p.read_text();old="    page.locator('[data-select=\"eigenmode\"]').select_option(str(mode));page.wait_for_timeout(100)";new='''    before_frame=int(page.locator('.world-canvas').get_attribute('data-frame') or 0)
    page.locator('[data-select="eigenmode"]').select_option(str(mode))
    page.wait_for_function("args=>{const value=JSON.parse(document.querySelector('.n-scene-overlay').dataset.eigenmode||'null'),c=document.querySelector('.world-canvas');return value?.index===args.mode&&+c.dataset.frame>args.before;}",arg={'mode':mode,'before':before_frame})''';assert old in s;s=s.replace(old,new)
old="const T=await import('./vendor/three.module.min.js');const {gainNodePositions}=await import('./modules/narrative/graph-scenes.mjs');const {stories}=await import('./modules/narrative/chapters.mjs');";new="const T=await import('./vendor/three.module.min.js');const {gainNodePositions}=await import('./modules/narrative/graph-scenes.mjs');";assert old in s;s=s.replace(old,new)
old="const host=document.querySelector('.n-canvas-host'),r=host.getBoundingClientRect(),canvas=host.querySelector('canvas'),camera=new T.PerspectiveCamera(40,r.width/r.height,.08,180);camera.position.fromArray(canvas.dataset.camera.split(',').map(Number));camera.lookAt(...stories.gain.targets.at(-1));camera.updateMatrixWorld();";new="const host=document.querySelector('.n-canvas-host'),r=host.getBoundingClientRect(),canvas=host.querySelector('canvas'),projection=JSON.parse(canvas.dataset.projection),camera=new T.PerspectiveCamera(projection.fov,projection.aspect,projection.near,projection.far);camera.position.fromArray(canvas.dataset.camera.split(',').map(Number));camera.lookAt(...projection.target);camera.updateMatrixWorld();";assert old in s;s=s.replace(old,new)
old="return{projected,obstacles,mode:mode.index,residual:mode.residual,canvas:[r.width,r.height]};";new="return{projected,obstacles,projection,mode:mode.index,residual:mode.residual,canvas:[r.width,r.height]};";assert old in s;s=s.replace(old,new)
old="'mode':page.locator('#demo-root').get_attribute('data-mode')";new=old+",'selected':page.locator('[data-select=\"eigenmode\"]').input_value(),'mode_readout':page.locator('.n-scene-overlay').get_attribute('data-eigenmode')";assert old in s;s=s.replace(old,new);p.write_text(s)
paths=subprocess.check_output(['git','ls-files'],text=True).splitlines()+['scripts/explorer_resize_checks.py']
files={p:hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in paths if not p.startswith('.delivery/') and p!='.github/workflows/closeout-staging.yml'}
assert len(files)==75
assert hashlib.sha256(json.dumps(files,sort_keys=True,separators=(',',':')).encode()).hexdigest()=='808458f5aebc08de7e5494486d947b30931cb1940154e7388ea1f4413f87a8f4'
print('Exact final projection-aware application matches all 75 authored files.')
