import {fmt,contentHTML,metric} from './scene-kit.mjs';
import {esc} from '../render.mjs';
export function caseScene(host){
 host.innerHTML=`<div class="n-case-workspace"><div class="n-case-top"><span>CASE / 014 <small>SYNTHETIC DEMONSTRATION</small></span><b data-hold>Evidence pending</b></div><div class="n-case-records"><article class="n-original"><header><i>MK</i><div>Mara Keller<small>Original customer message · unchanged</small></div></header><h3>Camera damaged in the laboratory</h3><p>My laboratory camera broke on <mark>12 May 2026</mark>.</p><p>The repair invoice is <strong>CHF 420</strong>.</p><footer>source/message-1 · original record preserved</footer></article><div class="n-case-side"><article class="n-invoice"><small>REPAIR INVOICE</small><strong>CHF <span data-amount>420</span></strong><span>Independent amount review</span></article><article class="n-policy"><small>POLICY EXCERPT</small><strong>Ends 31 May</strong></article><article class="n-later"><small>NEWER REPAIR REPORT</small><strong>12 June 2026</strong><span data-report>Conflicts with the original</span></article></div></div><div class="n-assertion"><span>Bounded date assertion</span><strong data-assertion>Not extracted</strong><small data-authority>Not authority to act</small></div><div class="n-case-checks">${[['date','Reviewed date'],['coverage','Coverage'],['invoice','Invoice'],['gate','Action gate']].map(([key,label])=>`<div data-node="${key}"><span>${label}</span><b></b><small></small></div>`).join('')}</div><div class="n-case-provenance"><span>Provenance</span><p></p></div></div>`;
 const get=s=>host.querySelector(s),set=(s,v)=>{const e=get(s);if(e.textContent!==String(v))e.textContent=v;};
 return{render(f){const s=f.science,r=f.reveal;get('.n-invoice').style.opacity=r.assertion;get('.n-policy').style.opacity=r.assertion;get('.n-later').style.opacity=r.conflict;get('.n-later').hidden=r.conflict<.01;get('.n-assertion').style.opacity=r.assertion;get('.n-case-checks').style.opacity=r.gate;get('.n-case-provenance').style.opacity=r.packet;
 set('[data-amount]',s.invoice);set('[data-assertion]',s.review?.authority==='human'?(s.nodes.date.value?'12 May · reviewed':(s.review.date==='2026-06-12'?'12 June':'Date')+' · review conflicts'):s.report?'Prior assertion revoked':s.parsed?'12 May · source-bound':'Not extracted');set('[data-authority]',s.nodes.date.value?'Review anchored to the preserved original':s.review?.authority==='human'?'Review does not match the preserved source':'Observation ≠ action authorization');set('[data-report]',s.nodes.date.value?'Discrepancy resolved by source review':'Conflicts with the original');
 const okay=s.nodes.gate.value;set('[data-hold]',okay?'ADMISSIBLE · HUMAN DECISION':f.position>=2.5?(s.nodes.date.value?'HOLD · INVOICE UNRESOLVED':'HOLD · UNRESOLVED DATE'):'EVIDENCE PENDING');get('[data-hold]').classList.toggle('ready',okay);get('.n-original mark').classList.toggle('reviewed',okay);get('.n-later').classList.toggle('resolved',okay);
 for(const key of ['date','coverage','invoice','gate']){const n=s.nodes[key],el=get(`[data-node="${key}"]`);el.classList.toggle('satisfied',n.value);el.classList.toggle('retained',!n.changed);el.querySelector('b').textContent=n.value?'SATISFIED':'UNRESOLVED';el.querySelector('small').textContent=`v${n.version} · ${n.changed?'recomputed':'retained'}`;}
 const invoiceVersion=s.nodes.invoice.version;set('.n-case-provenance p',`message-1 → report-2 → reviewed observation → replayed checks. Invoice remains v${invoiceVersion}. No payment sent.`);host.dataset.caseState=JSON.stringify({date:s.nodes.date.version,invoice:invoiceVersion,gate:okay});
 },dispose(){host.replaceChildren();}};
}
