/** A chapter changes one thing the reader can understand. All numbers live in model.mjs. */
const beat=(title,body,cue)=>({title,body,cue});
export const stories={
 gain:{theme:'observatory',title:'One disagreement travels further than one edge.',chapters:[
  beat('Every pair has an instruction.','Imagine five devices agreeing on their relative orientation. Each relationship is simple. For the whole network to agree, following a loop must bring you back facing the way you started.','First, only the relationships.'),
  beat('Change just one instruction.','Keep every other relationship fixed. Now B asks C for an extra turn. A local instruction can sound perfectly reasonable and still be impossible to reconcile with the rest.','The highlighted edge is the only intervention.'),
  beat('Come back facing the wrong way.','Carry an orientation from A, through B and C, back to A. The trip ends where it began—but the orientation does not. No choice of device settings can satisfy that loop.','Follow the transported arrow, not an equation.'),
  beat('A local change becomes a global signal.','The same edge changes two conjugate entries of the normalized Laplacian. As its angle grows, the smallest eigenvalue lifts away from zero. The spectrum now certifies a contradiction you have already seen.','Two matrix entries change. One global certificate responds.'),
  beat('Detection is not a repair plan.','A positive eigenvalue tells us that consistency is impossible. It does not identify the culprit. Here, an exact search over this tiny network finds the fewest relationships that must be retuned. That search is separate from the spectral certificate.','The spectral framework and the finite repair search have different jobs.'),
  beat('Restore the edge. Restore the loop.','Retune the inconsistent relationship. The orientation returns correctly, the operator changes back, and the smallest eigenvalue returns to zero. One object carried the whole argument.','Agreement → contradiction → certificate → repair.')],
 cameras:[[6.3,4.3,7.2],[3.8,3.8,5.1],[5.4,4.2,6.8],[6.0,4.4,7.1],[6.0,4.4,7.1],[6.3,4.3,7.2]],targets:[[0,1.7,.2],[.05,2.5,-.4],[0,1.9,0],[.8,1.6,.4],[.8,1.6,.4],[0,1.7,.2]]},
 replay:{theme:'replay-world',title:'Forgetting is a movement you can see.',chapters:[
  beat('The old skills are already right.','One set of model parameters supports three earlier skills. Each currently hits its target. Nothing needs repairing yet.','The three capability errors start at zero.'),
  beat('Learning moves the same model.','A new task asks for a different parameter setting. Move toward it and the new-task error falls. But the old skills use those same parameters: their errors rise as the model leaves them behind.','New learning and forgetting are the same movement, viewed from different tasks.'),
  beat('All the history would have changed the update.','Freeze the new-task-only result. The gold point shows where equal-weight learning with all the old information would have ended in this quadratic example. A finite buffer does not automatically have access to that answer.','Gold is an explanatory oracle—not information the learner secretly receives.'),
  beat('The gap is the correction we need.','The difference between those two points gives a precise request to the memory buffer. A stored example can supply a gradient direction. The question is whether the available directions can add up to the needed correction.','Candidate memories enter only after there is something to repair.'),
  beat('Independent memories fill the missing directions.','Select a memory for A, B and C. Their components combine into the requested correction. The model reaches the joint optimum of this example—not zero loss on incompatible tasks.','The green correction reaches the gold point.'),
  beat('Two memories can still mean one direction.','Replace the buffer with two copies of A. Its size is two, but its span is one-dimensional. The red residual cannot be removed by changing weights within that buffer. What is stored matters more than the count alone.','A larger archive is not necessarily a more useful correction space.')],
 cameras:[[6.4,4.8,-6.5],[6.2,4.5,-6.3],[5.4,3.8,-5.8],[4.9,3.6,-5.2],[5.4,4.0,-5.9],[5.4,4.0,-5.9]],targets:[[-.2,1,.7],[.3,1.1,.8],[.2,1.1,.8],[.1,1.0,.8],[.1,1.0,.8],[.1,1,.8]]},
 rank:{theme:'rank-world',title:'Before a repair can be small, it must be possible.',chapters:[
  beat('The adapter can move along one direction.','Think of the adapter as the set of corrections the model is allowed to make. At rank one in this coordinate-space example, every possible correction lies on one line.','The line is a restriction—not a training trajectory.'),
  beat('The obligations do not intersect it.','Recovering the earlier capabilities imposes three inequalities. In the restricted space, two demands contradict each other: x must be at least 1.40 and at most −0.70. No optimizer can satisfy both.','There is no repair point to draw.'),
  beat('More freedom is not always enough.','A second direction opens a plane. Yet the conflicting demands still require movement in z, which this plane cannot provide. The space is larger and the problem remains impossible.','Rank two still misses the feasible region.'),
  beat('One new direction makes a solution exist.','Open the third direction. For the first time, the adapter can reach the region where all three obligations hold. This is a change in what is possible, before any claim about how fast we can train.','The first feasible intersection appears.'),
  beat('Choose the nearest feasible repair.','Among all feasible corrections, the solver finds the one with the smallest Euclidean norm. Its direction and cost come from the stated constrained problem, not a point chosen for the picture.','The minimum-norm solution appears only after feasibility.'),
  beat('Possible can still be too costly.','Now impose the separate current-task change budget. Even the smallest feasible repair lies outside it. Expanding an adapter and preserving current learning are different conditions.','Feasible ≠ within budget.')],
 cameras:[[6,3.8,7.8],[6,4,7.2],[6,4,7.2],[7.5,4.9,4.0],[6.5,4.0,2.8],[7.2,4.5,3.5]],targets:[[0,.7,.3],[0,.8,.4],[0,.8,.4],[.3,.9,.8],[.35,.8,1.05],[.1,.8,.8]]},
 time:{theme:'time-world',title:'Scroll is time. The past does not update itself.',chapters:[
  beat('A new window arrives.','The learner has a fixed budget of 64 observations for this period. Initially, all 64 come from the present. These are simulated observations, not language-model tokens or benchmark measurements.','The budget is fixed throughout the story.'),
  beat('Useful history earns a place.','While the world is stable, observations from the archive estimate the same quantity. This example explicitly gives the archive less noise, so replay can lower expected error. History is useful here for a stated reason.','24 archived observations enter the budget.'),
  beat('Remembering uses time that could learn the present.','Replay is not free extra training. The same 64 slots now hold 24 archived observations and only 40 new ones. Each replay slot replaces a current observation.','24 replay + 40 current = 64. Never 88.'),
  beat('The world moves. Those records do not.','Advance the present while keeping the replay choice. The archived mean now lags behind the current mean. It still reduces noise, but its bias can outweigh that benefit.','The same allocation changes from helpful to harmful.'),
  beat('Older knowledge pulls against the present.','An observation can remain useful for yesterday and become harmful for today. Compare expected error on the archive with expected error at the current mean. The two objectives are not interchangeable.','Backward benefit does not guarantee current benefit.'),
  beat('Sometimes the right allocation is zero.','For this amount of known drift and this discrete 64-slot budget, the error-minimizing allocation is to replay nothing. This is an oracle calculation for the toy world—not a claim that real learners know the drift.','The value of a memory changes even when the memory itself does not.')],
 cameras:[[8,5.8,9.6],[8,5.8,9.6],[7,4.8,8.4],[7.5,5.5,9.5],[7.5,5.5,9.5],[7.5,5.5,9.5]],targets:[[0,.9,0],[0,.9,0],[0,.9,0],[0,1.1,0],[0,1.1,0],[0,1.1,0]]},
 case:{theme:'case-world',title:'A decision must survive its evidence changing.',chapters:[
  beat('Begin with the original message.','The customer says the camera broke on 12 May. This synthetic message is a source record, not a model summary. It stays unchanged throughout the case.','One source. One explicit date.'),
  beat('Bind a claim to what supports it.','The invoice establishes an amount. The policy record establishes a period. A date extracted from the message is stored as a bounded assertion—not permission to pay.','Source text, assertions and authorization remain separate.'),
  beat('A newer record introduces a conflict.','A synthetic repair report gives 12 June instead. The prior date assertion can no longer be treated as resolved. The original message is not overwritten to make the records agree.','A conflicting record revokes certainty, not history.'),
  beat('The proposed action becomes HOLD.','The amount may look plausible, but the date obligation is unresolved and the later interpretation is outside the policy period. The deterministic gate refuses the proposal.','HOLD is the correct operational result.'),
  beat('A reviewer resolves the specific conflict.','A human-reviewed observation confirms 12 May against the original source and identifies the report discrepancy. Date-dependent checks replay. The independent invoice check does not need to run again.','Only changed dependencies recompute.'),
  beat('The evidence trail can accompany the decision.','The original message, conflicting report, reviewed observation and derived checks remain inspectable. A human decision is now admissible in this demonstration. No payment has been sent.','Authority is earned by resolved obligations—not fluency.')],cameras:Array(6).fill([6,4,8]),targets:Array(6).fill([0,1,0])},
 world:{theme:'spatial-world',title:'Language should edit a world, not replace a picture.',chapters:[
  beat('Start with a sentence.','“Create a mountain laboratory at sunset.” Before there is an image, there is a request: a place, a context, and a lighting condition.','A sentence is the input—not the final artifact.'),
  beat('Separate what the sentence asks for.','The local compiler recognizes the supported place and lighting spans. It produces explicit operations. Unsupported clauses are rejected, rather than silently approximated.','This is a limited grammar, not unrestricted generative AI.'),
  beat('Give the objects identities.','The microscope and robotic arm become named entities. Their relation to the workbench is explicit. These IDs will survive the edits that follow.','microscope-1, arm-1 and bench-1 are persistent entities.'),
  beat('Anchor those entities in space.','Coordinates turn the scene graph into placements. Before committing, the system checks its supported surfaces and overlap rules. The anchors are the bridge between a sentence and a spatial environment.','Structure becomes inspectable placement.'),
  beat('Materialize the same structure.','The laboratory appears from those entities and placements. Its geometry is procedural and editable. The scene graph remains available behind the rendered view.','The world is state, not a single rendered image.'),
  beat('Give an agent a destination.','“Send the agent to the microscope.” A deterministic grid planner resolves a route around furniture. The agent follows the computed path instead of moving straight through the bench.','A goal is checked against the world it acts in.'),
  beat('Change one object. Keep the world.','“Move the microscope closer to the window.” The microscope keeps its ID. The robotic arm stays put. The changed destination invalidates the old route. Now the same world is yours to inspect and edit.','An edit changes the intended state—not everything around it.')],
 cameras:[[6.9,4.8,8.8],[6.9,4.8,8.8],[6.9,4.8,8.8],[5.7,3.8,7],[6.9,4.8,8.8],[4.0,3.3,5.7],[.7,2.3,3.0]],targets:Array(7).fill([0,1.0,-1.8])},
 natural:{theme:'posterior-world',title:'An estimate is a place. Uncertainty gives it shape.',chapters:[
  beat('An estimate starts away from the answer.','A Gaussian approximation begins with a mean—the location of its best estimate. The target is fixed. The learning rule has to move the estimate toward it.','First, notice where the estimate is.'),
  beat('A belief is not just a point.','The spread describes uncertainty. Reveal the full density and compare it with the target distribution. The height here is probability density, not the optimization loss.','Now notice the shape.'),
  beat('Update the mean and its uncertainty together.','Scroll through actual square-root natural-gradient steps in this diagonal Gaussian example. The mean moves and the covariance factor changes. The divergence is computed from the two distributions at each step.','One update rule changes both location and shape.'),
  beat('The example illustrates. The analysis guarantees under assumptions.','The approximation approaches the target. A smooth animation is not a convergence proof: the linked paper establishes guarantees under its stated regularity and step-size conditions.','The live trajectory and the theorem are different kinds of evidence.')],cameras:[[6.5,5.8,8],[6.5,5.8,8],[6.2,5.3,7.5],[6.2,5.3,7.5]],targets:Array(4).fill([0,.35,0])},
 bounds:{theme:'structure',title:'Finding a contradiction is not measuring its repair.',chapters:[
  beat('Every edge asks for agreement.','In this signed network, a plus edge asks its endpoints for the same sign. A minus edge would ask for opposite signs. With all plus signs, every relationship can be satisfied.','One assignment can satisfy the entire network.'),
  beat('One sign breaks that possibility.','Flip one edge. Follow a cycle and you will find incompatible demands. The contradiction is combinatorial; the spatial arrangement is only a way to keep the relationships visible.','An inconsistency does not disappear when the drawing changes.'),
  beat('Turn a warning into a repair bound.','The smallest Laplacian eigenvalue supplies a basic Rayleigh lower bound on the number of edges that must be removed. Exhaustive enumeration gives the exact answer for this four-node example.','A certificate and an exact small-graph search agree here.'),
  beat('Remove the minimum repair.','Remove the conflicting edge found by the search. Every remaining relationship can be satisfied and the smallest eigenvalue returns to zero. The paper develops a wider family of spectral bounds than this illustration.','The broken relationship is removed, not secretly changed.')],cameras:[[6,4.2,7],[5.3,3.8,6.8],[6,4.2,7],[6,4.2,7]],targets:Array(4).fill([0,1.2,0])},
 urban:{theme:'urban-world',title:'The road is only part of a delivery.',chapters:[
  beat('Compare one parcel on the same route.','A van travels faster than a cargo bike in this illustrative street. Looking only at road speed makes the decision seem straightforward.','Start with travel time alone.'),
  beat('The van has to find somewhere to stop.','Add parking search. The van waits while the bike reaches a nearby stopping place. The street did not get longer; a neglected component entered the calculation.','One stop overhead can reverse the result.'),
  beat('The final walk also belongs to the journey.','The parcel still has to reach the door. Add the walk from each vehicle. A local service-time model must preserve these components instead of replacing them with a city-wide average.','Travel + parking + final walk.'),
  beat('Change the neighbourhood. Change the answer.','Move to the outer district. Longer travel and different stop overhead change the balance again. These times are invented, not fitted predictions; the research studies how real urban context can inform service-time models.','Vehicle labels do not decide the result. Context does.')],cameras:[[7.8,6.4,8.5],[6.8,5.3,7.5],[5.8,4.8,6.5],[7.8,6.4,8.5]],targets:Array(4).fill([0,.4,0])},
 interaction:{theme:'conversation-world',title:'The same count can hide a different conversation.',chapters:[
  beat('Eight messages look like eight messages.','From a group total alone, two conversations can look identical. We know how much activity happened, but not how people encountered one another.','The aggregate does not reveal the pairs.'),
  beat('Keep the people. Reveal the replies.','Open the group into individual accounts. Now six of the eight replies arrive at one recipient, while another recipient receives none. The activity count never changed.','The same messages now have destinations.'),
  beat('Redistribute the same eight messages.','Give each recipient two replies. Equal totals conceal a completely different pattern of exposure. That difference only becomes visible at the pair level.','Who interacts with whom is information the total discards.'),
  beat('Observation is not evidence of persuasion.','Pair-level analysis makes interaction structure visible. It does not show that counterspeech caused a change in beliefs or behaviour. These accounts are fictional; the original paper analyses paired interactions in real data.','A more informative description is not a causal claim.')],cameras:[[7,6.0,8.5],[6.4,5.8,8],[6.4,5.8,8],[6.4,5.8,8]],targets:Array(4).fill([0,.4,0])}
};
export const order=['interaction','bounds','gain','urban','natural','replay','rank','time','case','world'];
