import {stories} from './chapters.mjs';
import {evaluateNarrative,progressFromAnchors} from './model.mjs';
import {createNarrativeRenderer} from './renderer.mjs';
import {createExplorer} from './explore.mjs';
import {esc} from '../render.mjs';
/** One scroll input, one pure frame. Navigation and autoplay move the page, never mutate a chapter. */
export function mountScrollNarrative(work,root,{at=null,chapter=null}={}){
 const key=work.mechanism,story=stories[key],count=story.chapters.length;
 root.className='scroll-narrative';root.innerHTML=`<div class="n-intro"><p>Scroll to follow the idea. Scroll back to retrace it.</p><button data-auto type="button" aria-pressed="false">Auto-tour</button></div><div class="n-story-layout"><div class="n-stage world-exhibit ${story.theme}" tabindex="0" role="region" aria-label="${esc(work.title)} scientific narrative"><div class="n-stage-top"><span data-chapter-count>1 / ${count}</span><div><button data-prev type="button" aria-label="Previous chapter">←</button><button data-next type="button" aria-label="Next chapter">→</button><button data-skip type="button">Explore</button></div><i class="n-progress-line"></i></div><div class="n-stage-render"></div><div class="n-stage-caption"><p data-cue></p><span data-classification></span></div></div><div class="n-prose">${story.chapters.map((c,i)=>`<article class="n-chapter" data-chapter="${i}" id="${work.id}-chapter-${i+1}"><div><span class="n-step">${String(i+1).padStart(2,'0')}</span><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p></div></article>`).join('')}<article class="n-explore-chapter"><div><span class="n-step">Your turn</span><h2>Now try it yourself.</h2><p>The same scientific object is now an instrument. Change its inputs. Scrolling back restores the guided argument without discarding your sandbox.</p><div class="n-explorer" inert></div><button type="button" data-restart class="n-restart">Return to the beginning ↑</button></div></article></div></div><p class="n-accessible-status" role="status" aria-live="polite"></p>`;
 const layout=root.querySelector('.n-story-layout'),stage=root.querySelector('.n-stage'),host=root.querySelector('.n-stage-render'),articles=[...root.querySelectorAll('.n-chapter')],exploreArticle=root.querySelector('.n-explore-chapter'),exploreHost=root.querySelector('.n-explorer'),mql=matchMedia('(prefers-reduced-motion: reduce)');
 let anchors=[],exploreAt=Infinity,raf=0,disposed=false,mode='guide',progress=0,lastProgress=-1,lastMode='',lastIndex=-1,autoFrame=0,autoStart=0,autoFrom=0,autoTo=0,force=false,preview=null;
 const explorer=createExplorer(key,exploreHost,scene=>{preview=scene||null;force=true;queue();});
 const renderer=createNarrativeRenderer(key,host,{onSelect:id=>{if(mode==='explore')explorer.select(id);},onDrag:(id,p,done)=>{if(mode==='explore')explorer.drag(id,p,done);}});
 function zone(){return innerWidth<=780?innerHeight*.78:innerHeight*.49;}
 function measure(){if(disposed)return;const z=zone();anchors=articles.map(e=>e.getBoundingClientRect().top+scrollY+e.clientHeight*.44-z);anchors[0]=Math.max(anchors[0],layout.getBoundingClientRect().top+scrollY-(innerWidth<=780?65:98));exploreAt=exploreArticle.getBoundingClientRect().top+scrollY+60-z;root.dataset.anchors=JSON.stringify(anchors);root.dataset.exploreAt=String(exploreAt);force=true;queue();}
 function frame(){raf=0;if(disposed||anchors.length!==count)return;progress=Math.round(progressFromAnchors(scrollY,anchors)*1e6)/1e6;mode=scrollY>=exploreAt?'explore':'guide';if(progress===lastProgress&&mode===lastMode&&!force)return;force=false;
  if(mode==='explore')explorer.activate();const params=mode==='explore'?explorer.parameters():null;const f=evaluateNarrative(key,progress,{reduced:mql.matches,explore:preview&&params?{...params,scene:preview}:params});preview=null;
  root.dataset.progress=String(progress);root.dataset.mode=mode;root.dataset.state=JSON.stringify(f.science);root.dataset.narrative=JSON.stringify({key,progress:f.progress,index:f.index,local:f.local,reveal:f.reveal,camera:f.camera,parameters:f.parameters});
  stage.dataset.mode=mode;exploreHost.inert=mode!=='explore';exploreHost.classList.toggle('unlocked',mode==='explore');
  if(mode!==lastMode&&mode==='explore')renderer.setCamera(story.cameras.at(-1),story.targets.at(-1));renderer.render(f);
  articles.forEach((a,i)=>a.setAttribute('aria-current',mode==='guide'&&i===f.index?'step':'false'));root.querySelector('[data-chapter-count]').textContent=mode==='explore'?'Explore':`${f.index+1} / ${count}`;root.querySelector('.n-progress-line').style.transform=`scaleX(${progress})`;
  root.querySelector('[data-cue]').textContent=mode==='explore'?'Change a control. The same computation responds.':f.chapter.cue;root.querySelector('[data-classification]').textContent=f.classification;
  root.querySelector('[data-prev]').disabled=progress===0&&mode==='guide';root.querySelector('[data-next]').disabled=mode==='explore';
  if(lastIndex!==f.index||lastMode!==mode){root.querySelector('.n-accessible-status').textContent=mode==='explore'?'Explorer unlocked.':`Chapter ${f.index+1}: ${f.chapter.title}`;lastIndex=f.index;}
  // A copied URL, reload or new tab can reconstruct this exact guided progress.
  if(mode==='guide'&&location.hash.startsWith('#work/'+work.id))try{history.replaceState({...history.state,narrative:progress},'',`#work/${work.id}/at/${progress.toFixed(6)}`);}catch{}
  lastProgress=progress;lastMode=mode;
 }
 function queue(){if(!disposed&&!raf)raf=requestAnimationFrame(frame);}
 function stop(){if(autoFrame)cancelAnimationFrame(autoFrame);autoFrame=0;root.querySelector('[data-auto]').textContent='Auto-tour';root.querySelector('[data-auto]').setAttribute('aria-pressed','false');}
 function moveTo(y,{animate=true}={}){stop();window.scrollTo({top:Math.max(0,y),behavior:animate&&!mql.matches?'smooth':'instant'});queue();}
 function goProgress(p,animate=false){const u=Math.max(0,Math.min(1,p))*(count-1),i=Math.floor(u),j=Math.min(count-1,i+1);moveTo(anchors[i]+(anchors[j]-anchors[i])*(u-i),{animate});}
 root.querySelector('[data-next]').onclick=()=>{const i=Math.min(count-1,Math.floor(progress*(count-1)+.08)+1);moveTo(progress>=.999?exploreAt+4:anchors[i]);};
 root.querySelector('[data-prev]').onclick=()=>moveTo(mode==='explore'?anchors.at(-1):anchors[Math.max(0,Math.ceil(progress*(count-1)-.08)-1)]);
 root.querySelector('[data-skip]').onclick=()=>moveTo(exploreAt+4);root.querySelector('[data-restart]').onclick=()=>goProgress(0,true);
 root.querySelector('[data-auto]').onclick=()=>{if(autoFrame){stop();return;}autoStart=performance.now();autoFrom=scrollY;autoTo=exploreAt+4;if(autoFrom>=autoTo)autoFrom=Math.max(0,anchors[0]);root.querySelector('[data-auto]').textContent='Pause auto-tour';root.querySelector('[data-auto]').setAttribute('aria-pressed','true');const duration=Math.max(4000,(autoTo-autoFrom)*8);function auto(t){if(disposed)return;const p=Math.min(1,(t-autoStart)/duration);window.scrollTo({top:autoFrom+(autoTo-autoFrom)*p,behavior:'instant'});queue();if(p<1)autoFrame=requestAnimationFrame(auto);else stop();}autoFrame=requestAnimationFrame(auto);};
 const manual=e=>{if(e.type==='keydown'&&['ArrowRight','ArrowLeft'].includes(e.key)&&stage.contains(e.target)&&mode==='guide'){e.preventDefault();root.querySelector(e.key==='ArrowRight'?'[data-next]':'[data-prev]').click();}else if(!e.target?.closest?.('[data-auto]'))stop();};
 window.addEventListener('scroll',queue,{passive:true});window.addEventListener('resize',measure);window.addEventListener('wheel',stop,{passive:true});window.addEventListener('touchstart',stop,{passive:true});root.addEventListener('pointerdown',manual);root.addEventListener('keydown',manual);mql.addEventListener('change',measure);
 const ro=new ResizeObserver(measure);ro.observe(layout);measure();
 const init=requestAnimationFrame(()=>{measure();if(at!==null)goProgress(at);else if(chapter!==null)goProgress(Math.max(0,Math.min(count-1,chapter))/(count-1));else queue();});
 return{dispose(){disposed=true;stop();cancelAnimationFrame(raf);cancelAnimationFrame(init);ro.disconnect();window.removeEventListener('scroll',queue);window.removeEventListener('resize',measure);window.removeEventListener('wheel',stop);window.removeEventListener('touchstart',stop);root.removeEventListener('pointerdown',manual);root.removeEventListener('keydown',manual);mql.removeEventListener('change',measure);explorer.dispose();renderer.dispose();}};
}
