import {T,group,mesh,box,ball,line,ring,rod,point,segment,vector,alpha,annotation,contentHTML,metric,fmt,V,basePlane} from './scene-kit.mjs';
import {constraints,incoming,memories,dot,add,sub,scale,replayState} from '../worlds/math.mjs';
import {feasibleGeometry} from './feasible.mjs';
export function replayScene(view,overlay){
 const g=group(view.content),labels=annotation(view),P=v=>[-1.45+v[0]*1.7,.18+v[2]*1.7,-.8+v[1]*1.7];basePlane(g,'#e5ede6');
 const origin=ball(g,P([0,0,0]),.095,'#638573'),current=vector(g,'#3a83ad',.036),oracle=vector(g,'#b98738',.020,true),repair=vector(g,'#328971',.044),residual=segment(g,'#b75844',.026,true),unapplied=segment(g,'#328971',.020,true),wanted=segment(g,'#af8a54',.018,true),actual=ball(g,P([0,0,0]),.13,'#ebf6e7',{metalness:.36,roughness:.18});
 const candidateGroup=group(g),candidates=[0,2,3].map(i=>({i,arrow:vector(candidateGroup,'#7baf9f',.015),point:ball(candidateGroup,[0,0,0],.05,'#599782')}));
 const axes=group(g);[[1.65,0,0],[0,1.5,0],[0,0,1.5]].forEach(p=>line(axes,[P([0,0,0]),P(p)],'#c0d2c3',.006));
 const skillGroup=group(g),skills=[0,1,2].map((i)=>{const x=-2+i*1.0,z=2.2;ring(skillGroup,[x,.01,z],.26,'#7fa089');const bar=box(skillGroup,[x,.05,z],[.25,.08,.25],'#80a487');return{bar,x,z};});
 const panel=document.createElement('div');panel.className='n-bottom-metrics';overlay.append(panel);const buffer=document.createElement('div');buffer.className='n-buffer';overlay.append(buffer);
 return{render(f){const s=f.science,r=f.reveal;current.set(P([0,0,0]),P(s.current));oracle.set(P([0,0,0]),P(s.joint));repair.set(P(s.current),P(s.actual));wanted.set(P(s.current),P(s.joint));const full=replayState(s.selected,s.learning,1);residual.set(P(full.actual),P(s.joint));unapplied.set(P(s.actual),P(full.actual));point(actual,P(s.actual));
 alpha(current.g,r.current);alpha(oracle.g,r.oracle);alpha(wanted.g,r.correction*(1-r.candidates*.55));alpha(repair.g,r.correction);alpha(residual.g,r.residual);alpha(unapplied.g,r.residual);alpha(candidateGroup,r.candidates);alpha(axes,r.oracle*.8);alpha(skillGroup,1-r.candidates*.6);
 candidates.forEach(({i,arrow,point:p})=>{const m=memories[i],end=add(s.current,scale(m.v,dot(s.desired,m.v))),selected=s.selected.includes(i)||(i===0&&s.selected.includes(1));arrow.set(P(s.current),P(end));alpha(arrow.g,selected?1:.26);point(p,P(end));});
 skills.forEach(({bar},i)=>{const h=.06+s.actual[i]**2*.9;bar.scale.y=h/.08;bar.position.y=h/2;bar.material.color.set(s.actual[i]>.1?'#b57156':'#80a487');});
 const metrics=r.current<.08?[metric('Earlier-skill loss',fmt(s.oldLoss))]:r.oracle<.5?[metric('Earlier-skill loss',fmt(s.oldLoss)),metric('New-task loss',fmt(s.newLoss))]:[metric('Old-task loss',fmt(s.oldLoss)),metric('New-task loss',fmt(s.newLoss)),...(r.residual>.5?[metric('Unavailable correction',fmt(s.unavailable),'danger'),...(s.notApplied>.001?[metric('Available, not applied',fmt(s.notApplied))]:[])]:[])];contentHTML(panel,metrics.join(''));
 buffer.hidden=r.candidates<.01;buffer.style.opacity=r.candidates;contentHTML(buffer,`<span class="n-small">Selected memories</span><div>${s.selected.map(i=>`<b>${memories[i].name}</b>`).join('')}</div><strong>${s.selected.length} memories · ${s.directions} independent directions</strong>`);
 const a=[];if(r.current<.1){a.push({text:'Three earlier skills · all at target',pos:[-1,.65,2.2],tone:'green'});}else if(r.oracle<.45){a.push({text:'New learning',pos:add(P(s.current),[0,.5,0]),tone:'blue'},{text:'Earlier errors rise',pos:[-1,1.1,2.2],tone:'red'});}else{if(r.residual>.5&&s.unavailable>.01)a.push({text:`Unavailable ${fmt(s.unavailable)} · outside memory span`,pos:add(P(scale(add(full.actual,s.joint),.5)),[0,.5,.1]),tone:'red'});else if(r.residual>.5&&s.notApplied>.01)a.push({text:`Available ${fmt(s.notApplied)} · not yet applied`,pos:add(P(scale(add(s.actual,full.actual),.5)),[0,.5,.1]),tone:'green'});else a.push({text:'Full-history target · oracle',pos:add(P(s.joint),[0,.55,-.1]),tone:'amber'});if(r.candidates<.5)a.push({text:'Current-only result',pos:add(P(s.current),[0,.48,0]),tone:'blue'});}
 labels(a);
 },dispose(){panel.remove();buffer.remove();}};
}
export function rankScene(view,overlay){
 const g=group(view.content),labels=annotation(view),lineSpace=segment(g,'#c4afe9',.035);lineSpace.set([-2.6,0,0],[2.6,0,0]);
 const planeSpace=group(g),plane=mesh(planeSpace,new T.PlaneGeometry(5.2,4.4),'#b9a4e4',[0,.9,0],{transparent:true,opacity:.14,depthWrite:false,side:T.DoubleSide});plane.add(new T.LineSegments(new T.EdgesGeometry(plane.geometry),new T.LineBasicMaterial({color:'#a896c8'})));
 const volumeSpace=group(g),geo=new T.BoxGeometry(5.2,4.4,5.2),outline=new T.LineSegments(new T.EdgesGeometry(geo),new T.LineBasicMaterial({color:'#9485ad',transparent:true,opacity:.6}));outline.position.y=.9;volumeSpace.add(outline);
 const obligationGroup=group(g);constraints.forEach(({n,b},i)=>{const normal=V(n).normalize(),center=V(n).multiplyScalar(b/dot(n,n)),p=mesh(obligationGroup,new T.PlaneGeometry(5.0,5.0),['#c7a477','#9c83c1','#79aba9'][i],center.toArray(),{transparent:true,opacity:.09,depthWrite:false,side:T.DoubleSide});p.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),normal);p.add(new T.LineSegments(new T.EdgesGeometry(p.geometry),new T.LineBasicMaterial({color:['#c7a477','#9c83c1','#79aba9'][i],transparent:true,opacity:.45})));});
 const feasible=group(g),poly=mesh(feasible,feasibleGeometry(),'#69b795',[0,0,0],{transparent:true,opacity:.16,depthWrite:false,side:T.DoubleSide});poly.add(new T.LineSegments(new T.EdgesGeometry(poly.geometry,10),new T.LineBasicMaterial({color:'#75cba5',transparent:true,opacity:.8})));
 const solution=group(g),pointer=vector(solution,'#e5b376',.027),marker=ball(solution,[.35,.65,1.05],.09,'#e9bc7b');pointer.set([0,0,0],[.35,.65,1.05]);
 const budget=group(g),sphere=mesh(budget,new T.SphereGeometry(1,32,20),'#bbc0dc',[0,0,0],{transparent:true,opacity:.05,depthWrite:false});ring(budget,[0,0,0],1,'#9ca2c0');ring(budget,[0,0,0],1,'#9ca2c0',[0,0,0]);ball(g,[0,0,0],.065,'#e2e1ed');
 const panel=document.createElement('div');panel.className='n-bottom-metrics';overlay.append(panel);const rules=document.createElement('div');rules.className='n-constraints';overlay.append(rules);
 return{render(f){const s=f.science,r=f.reveal;alpha(lineSpace.g,1);alpha(planeSpace,s.rank>=2?(s.rank===3?.22:1):0);planeSpace.scale.y=s.rank===2?Math.max(.01,Math.min(1,f.visual.opening-1)):1;volumeSpace.scale.z=s.rank===3?Math.max(.01,Math.min(1,f.visual.opening-2)):1;alpha(volumeSpace,s.rank===3?Math.max(.02,r.feasible)*(1-r.solution*.65):0);alpha(obligationGroup,r.constraints*(1-r.feasible*.6));alpha(feasible,r.feasible*(s.feasible?1:.14));alpha(solution,s.feasible?r.solution:0);alpha(budget,r.budget);budget.scale.setScalar(s.radius);pointer.color(s.affordable?'#81d7aa':'#e5b376');marker.material.color.set(s.affordable?'#81d7aa':'#e5b376');
 rules.hidden=r.constraints<.01;rules.style.opacity=r.constraints;contentHTML(rules,`<span class="n-small">Recovery obligations</span><code>x + z ≥ 1.40</code><code>−x + z ≥ 0.70</code><code>y ≥ 0.65</code>`);
 contentHTML(panel,metric('Available space',s.rank===1?'A line':s.rank===2?'A plane':'A volume')+(r.constraints>.6?metric('Feasible repair',s.feasible?'Exists':'None'):'')+(r.solution>.5?metric('Minimum cost',(s.cost===null?'—':fmt(s.cost))):'')+(r.budget>.5?metric('Allowed cost',fmt(s.budget)) :''));
 const a=[];if(r.solution>.5&&s.feasible)a.push({text:r.budget>.5&&!s.affordable?'Even the smallest repair exceeds the budget':'Minimum-norm repair',pos:[.35,1.18,1.05],tone:s.affordable?'green':'amber'});else if(r.constraints>.5&&!s.feasible)a.push({text:'No intersection · no repair',pos:[0,2.4,0],tone:'red'});else if(s.feasible&&r.feasible>.5)a.push({text:'The feasible region is now reachable',pos:[1.5,2.5,1.8],tone:'green'});else a.push({text:'Corrections available to the adapter',pos:[0,.6,0],tone:'plain'});labels(a);
 },dispose(){panel.remove();rules.remove();}};
}
export function naturalScene(view,overlay){
 const g=group(view.content),labels=annotation(view),n=48,m=36,positions=new Float32Array((n+1)*(m+1)*3),indices=[];for(let j=0;j<m;j++)for(let i=0;i<n;i++){const a=j*(n+1)+i;indices.push(a,a+n+1,a+1,a+1,a+n+1,a+n+2);}
 function surface(color,wire){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(positions.slice(),3));geo.setIndex(indices);const o=mesh(g,geo,color,[0,0,0],{wireframe:wire,transparent:wire,opacity:wire?.36:1,side:T.DoubleSide,roughness:.35,metalness:.24});return o;}
 const belief=surface('#4b9fac',false),target=surface('#c69e61',true),mean=ball(g,[-2,.04,1.5],.09,'#b0dcd8'),targetPoint=ball(g,[1,.04,-.5],.07,'#d6b778');
 function update(o,s){const data=o.geometry.attributes.position;for(let j=0;j<=m;j++)for(let i=0;i<=n;i++){const x=-4+i/n*8,z=-3+j/m*6,q=((x-s.m[0])/s.c[0])**2+((z-s.m[1])/s.c[1])**2,h=Math.exp(-q/2)/(2*Math.PI*s.c[0]*s.c[1])*4;data.setXYZ(j*(n+1)+i,x,h,z);}data.needsUpdate=true;o.geometry.computeVertexNormals();}
 update(target,{m:[1,-.5],c:[1,1/Math.sqrt(7)]});const contours=group(g);for(let k=1;k<=3;k++)line(contours,Array.from({length:97},(_,i)=>{const a=i/96*Math.PI*2;return[1+Math.cos(a)*k,.015,-.5+Math.sin(a)*k/Math.sqrt(7)];}),'#776347',.009);
 const pathGeo=new T.BufferGeometry();pathGeo.setAttribute('position',new T.BufferAttribute(new Float32Array(81*3),3));const path=new T.Line(pathGeo,new T.LineBasicMaterial({color:'#d8c394'}));g.add(path);
 const panel=document.createElement('div');panel.className='n-bottom-metrics';overlay.append(panel);const chart=document.createElement('div');chart.className='n-error-chart';chart.innerHTML='<span class="n-small">Actual KL divergence by step</span><canvas width="300" height="100"></canvas>';overlay.append(chart);let last='';
 return{render(f){const s=f.science,r=f.reveal,signature=s.steps+':'+s.method;if(last!==signature){last=signature;update(belief,s);point(mean,[s.m[0],.04,s.m[1]]);s.path.forEach((p,i)=>pathGeo.attributes.position.setXYZ(i,p.m[0],.024,p.m[1]));pathGeo.attributes.position.needsUpdate=true;pathGeo.setDrawRange(0,s.path.length);const ctx=chart.querySelector('canvas').getContext('2d');ctx.clearRect(0,0,300,100);ctx.strokeStyle='#d9b77d';ctx.lineWidth=2;ctx.beginPath();s.loss.forEach((v,i)=>{const x=4+i/80*286,y=92-v/s.loss[0]*82;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
 alpha(belief,r.surface);alpha(target,r.target);alpha(contours,r.target);chart.hidden=r.loss<.01;chart.style.opacity=r.loss;panel.hidden=r.loss<.01;panel.style.opacity=r.loss;contentHTML(panel,metric('Computed steps',s.steps)+metric('KL divergence',fmt(s.kl))+metric('Surface height','Probability density'));
 labels(r.surface<.2?[{text:'Current estimate',pos:[s.m[0],.45,s.m[1]],tone:'blue'},{text:'Target mean',pos:[1,.45,-.5],tone:'amber'}]:[{text:'Current belief',pos:[s.m[0],4/(2*Math.PI*s.c[0]*s.c[1])+.3,s.m[1]],tone:'blue'},{text:'Fixed target density',pos:[2.5,.5,-1.4],tone:'amber'}]);
 },dispose(){panel.remove();chart.remove();}};
}
