import {T,group,mesh,box,ball,line,ring,rod,point,segment,vector,alpha,annotation,contentHTML,metric,fmt,V} from './scene-kit.mjs?v=scroll-4.2';
import {graphEdges,graphCycles} from '../worlds/math.mjs?v=scroll-4.2';
const pts=[[-2.5,.9,.8],[-1.3,3,-.4],[1.1,3.25,-.45],[2.55,1,.4],[0,.45,2]],names='ABCDE';
export function gainScene(view,overlay){
 const g=group(view.content),labels=annotation(view),edges=[],nodes=[],orient=[];
 graphEdges.forEach(([a,b],i)=>{const link=segment(g,'#769da9',.022);link.set(pts[a],pts[b]);link.g.userData.pick=String(i);edges.push(link);});
 pts.forEach((p,i)=>{const n=group(g);ball(n,p,.16,'#426579',{roughness:.23,metalness:.66});ring(n,p,.25,'#709ead',[0,0,0],.009);nodes.push(n);const a=vector(g,'#9acbdb',.019);a.set(p,[p[0]+.4,p[1],p[2]]);orient.push(a);});
 const transported=group(g),arrow=vector(transported,'#f2c173',.022),initial=vector(transported,'#759ead',.012,true),arcGeometry=new T.BufferGeometry();arcGeometry.setAttribute('position',new T.BufferAttribute(new Float32Array(65*3),3));const mismatch=new T.Line(arcGeometry,new T.LineBasicMaterial({color:'#ed9b76'}));transported.add(mismatch);
 const inspector=document.createElement('div');inspector.className='n-operator';overlay.append(inspector);const certificate=document.createElement('div');certificate.className='n-certificate';overlay.append(certificate);
 return {render(f){const s=f.science,r=f.reveal,v=f.visual,edge=v.edge??1;const chosen=(v.cycle>=0?s.cycles[v.cycle]:null)||s.cycles.find(c=>c.nodes.some((a,i)=>{const b=c.nodes[(i+1)%c.nodes.length];return (a===graphEdges[edge][0]&&b===graphEdges[edge][1])||(b===graphEdges[edge][0]&&a===graphEdges[edge][1]);}))||s.cycles[0];const pathNodes=[...chosen.nodes,chosen.nodes[0]];const cycleEdges=pathNodes.slice(0,-1).map((a,i)=>graphEdges.findIndex(([u,w])=>(u===a&&w===pathNodes[i+1])||(w===a&&u===pathNodes[i+1])));
  edges.forEach((e,i)=>{e.color(i===edge?'#efbd73':r.transport>.2&&cycleEdges.includes(i)?'#acdbea':'#698e9f');const local=1-(i!==edge?v.focus*.86:0),cycleFocus=r.transport>.2&&r.operator<.2&&!cycleEdges.includes(i)?.16:1,operatorFocus=r.operator>.7&&!f.exploring?.24:1;alpha(e.g,local*cycleFocus*operatorFocus);});
  orient.forEach((o,i)=>{const ang=f.inspection?f.inspection.phases[i]:i===graphEdges[edge][1]?s.angles[edge]*Math.PI/180:0,len=f.inspection?.22+f.inspection.amplitudes[i]*.85:.43;o.set(pts[i],[pts[i][0]+len*Math.cos(ang),pts[i][1]+len*Math.sin(ang),pts[i][2]]);alpha(o.g,i===graphEdges[edge][1]?1:.55);});
  const path=pathNodes.map(n=>pts[n]),t=f.exploring?1:v.transport,z=t*(path.length-1),i=Math.min(path.length-2,Math.floor(z)),frac=t===1?1:z-i,p=V(path[i]).lerp(V(path[i+1]),frac).toArray();
  // Interpolate transport on an edge; at each vertex it equals that cycle's exact accumulated gain.
  const gains=cycleEdges.map((e,i)=>s.angles[e]*(graphEdges[e][0]===pathNodes[i]?1:-1)),angle=(gains.slice(0,i).reduce((a,b)=>a+b,0)+gains[i]*frac)*Math.PI/180;
  arrow.set(p,[p[0]+.63*Math.cos(angle),p[1]+.63*Math.sin(angle),p[2]]);initial.set(path[0],[path[0][0]+.63,path[0][1],path[0][2]]);mismatch.position.set(...path[0]);const closing=chosen.angle*Math.PI/180;for(let j=0;j<=64;j++){const q=closing*j/64;arcGeometry.attributes.position.setXYZ(j,.34*Math.cos(q),.34*Math.sin(q),.002);}arcGeometry.attributes.position.needsUpdate=true;mismatch.visible=Math.abs(chosen.angle)>.1&&t>.98;alpha(transported,f.inspection?0:r.transport);overlay.dataset.eigenmode=JSON.stringify(f.inspection||null);
  inspector.style.opacity=r.operator;inspector.hidden=r.operator<.01;contentHTML(inspector,`<span class="n-small">Normalized Laplacian · live</span><div class="n-matrix">${s.re.map((row,i)=>row.map((v,j)=>{const hit=(i===graphEdges[edge][0]&&j===graphEdges[edge][1])||(j===graphEdges[edge][0]&&i===graphEdges[edge][1]);return `<span class="${hit?'changed':''}" style="opacity:${hit?1:f.exploring?1:Math.max(0,Math.min(1,(f.position-2.5)/.4))}">${fmt(v,2)}${Math.abs(s.im[i][j])>.001?`<small>${s.im[i][j]>0?'+':'−'}${fmt(Math.abs(s.im[i][j]),2)}i</small>`:''}</span>`;}).join('')).join('')}</div><div class="n-spectrum" style="opacity:${r.spectrum}">${s.eigenvalues.map((v,i)=>`<div><i style="height:${2+v*37}px"></i><small>${fmt(v)}</small></div>`).join('')}</div>`);
  certificate.style.opacity=r.certificate;certificate.hidden=r.certificate<.01;contentHTML(certificate,`${metric('Spectral certificate',s.inconsistent?'Inconsistent':'Balanced')}${metric('Exact tiny-graph retunings',s.repair.ids.length)}<span class="n-small">Finite search, not the spectral bound itself.</span>${f.inspection?`<div class="n-mode-reading">${metric('Mode '+(f.inspection.index+1)+' · energy',fmt(f.inspection.eigenvalue))}<span class="n-small">‖Lv − λv‖ = ${f.inspection.residual.toExponential(1)}<br>Arrow length: amplitude · direction: phase</span></div>`:''}`);
  const a=[];if(f.inspection){a.push({text:'Eigenmode '+(f.inspection.index+1)+' · computed from L',pos:[0,3.7,-.4],tone:'amber'});}else if(r.transport>.7&&r.operator<.7)a.push({text:t>.97?`Same node · ${fmt(Math.abs(chosen.angle),0)}° orientation mismatch`:'Transport around '+pathNodes.map(i=>names[i]).join(' → '),pos:[p[0],p[1]+.75,p[2]],tone:'amber'});else if(v.focus>.6)a.push({text:`Only ${names[graphEdges[edge][0]]}–${names[graphEdges[edge][1]]} changes · ${fmt(s.angles[edge],0)}°`,pos:[.05,3.55,-.35],tone:'amber'});else if(r.operator<.4)pts.forEach((p,i)=>a.push({text:names[i],pos:[p[0],p[1]+.4,p[2]],tone:'plain'}));if(!f.inspection&&r.transport>.4&&r.operator<.4)chosen.nodes.forEach(i=>a.push({text:names[i],pos:[pts[i][0],pts[i][1]+.39,pts[i][2]],tone:'plain'}));labels(a);
 },picks:edges.map(x=>x.g),dispose(){inspector.remove();certificate.remove();}};
}
export function boundsScene(view,overlay){
 const g=group(view.content),P=[[-2,.55,1.2],[2,.55,1.2],[0,3,-.3],[0,.55,-2.1]],E=[[0,1],[0,2],[0,3],[1,2],[1,3],[2,3]],links=[],labels=annotation(view);
 E.forEach(([a,b])=>{const full=segment(g,'#6e8676',.046),left=segment(g,'#89948a',.036),right=segment(g,'#89948a',.036);full.set(P[a],P[b]);links.push({full,left,right,a,b});});P.forEach(p=>ball(g,p,.18,'#c8b492',{metalness:.64,roughness:.24}));
 const panel=document.createElement('div');panel.className='n-bottom-metrics';overlay.append(panel);
 return {render(f){const s=f.science,annotations=[];links.forEach((e,i)=>{e.full.g.visible=!s.removed.includes(i);e.full.color(s.signs[i]<0?'#b25642':'#6e8676');const cut=s.removed.includes(i);e.left.g.visible=e.right.g.visible=cut;if(cut){const mid=V(P[e.a]).lerp(V(P[e.b]),.5);e.left.set(P[e.a],V(P[e.a]).lerp(mid,.8).toArray());e.right.set(V(P[e.b]).lerp(mid,.8).toArray(),P[e.b]);}annotations.push({text:cut?'removed':s.signs[i]>0?'+':'−',pos:V(P[e.a]).lerp(V(P[e.b]),.5).toArray(),tone:cut?'light-label':s.signs[i]>0?'green':'red'});});
 panel.hidden=f.reveal.spectrum<.01;panel.style.opacity=f.reveal.spectrum;contentHTML(panel,metric('λ minimum',fmt(s.minimum))+metric('Rayleigh lower bound',s.lowerBound+' edge')+metric('Exact minimum removal',s.frustration+' edge'));labels(annotations);
 },dispose(){panel.remove();}};
}
