import { useCallback, useMemo } from 'react'

import {
  fetchDagApi,
  fetchLatestRunApi,
  fetchProvenanceApi,
} from '../lib/api'
import { formatDateTime, formatDuration } from '../lib/formatters'
import { useResource } from '../lib/useResource'
import { ErrorBlock, LoadingBlock } from '../components/StateBlocks'

interface OpsData {
  latestRun: Awaited<ReturnType<typeof fetchLatestRunApi>>
  dag: Awaited<ReturnType<typeof fetchDagApi>>
  provenance: Awaited<ReturnType<typeof fetchProvenanceApi>>
}

export function OpsConsolePage() {
  const loadOps = useCallback(
    () =>
      Promise.all([fetchLatestRunApi(), fetchDagApi(), fetchProvenanceApi()]).then(
        ([latestRun, dag, provenance]) => ({
          latestRun,
          dag,
          provenance,
        }),
      ),
    [],
  )
  const state = useResource<OpsData>(loadOps)

  const warningTotal = useMemo(() => {
    if (!state.data) {
      return 0
    }
    return state.data.latestRun.tasks.reduce(
      (count, task) =>
        count +
        task.logs.filter((log) => log.level === 'warning' || log.level === 'error')
          .length,
      0,
    )
  }, [state.data])

  if (state.loading) {
    return <LoadingBlock label="Loading ops run reports." />
  }

  if (!state.data || state.error) {
    return (
      <ErrorBlock
        label="Unable to load ops reports."
        details={state.error ?? 'unknown ops error'}
      />
    )
  }

  const { latestRun, dag, provenance } = state.data
  const runUrl = latestRun.run.action_run_url ?? provenance.action_run_url

  return (
    <div className="page">
      <section className="hero">
        <p className="eyebrow">Operations</p>
        <h1>Pipeline Console</h1>
        <p className="hero-copy">
          DAG metadata, task durations, logs, and provenance are rendered from
          `/ops/*.json` generated by the pipeline runtime.
        </p>
      </section>

      <section className="panel">
        <header className="panel-header">
          <h2>Run Summary</h2>
          {runUrl ? (
            <a href={runUrl} target="_blank" rel="noreferrer">
              Open workflow run
            </a>
          ) : null}
        </header>
        <div className="kv-grid">
          <p>
            <span>Status</span>
            <strong>{latestRun.run.status}</strong>
          </p>
          <p>
            <span>Finished</span>
            <strong>{formatDateTime(latestRun.run.finished_at)}</strong>
          </p>
          <p>
            <span>Duration</span>
            <strong>{formatDuration(latestRun.run.duration_seconds)}</strong>
          </p>
          <p>
            <span>Warnings</span>
            <strong>{warningTotal}</strong>
          </p>
        </div>
      </section>

      <section className="panel">
        <header className="panel-header">
          <h2>DAG</h2>
        </header>
        <div className="stack-list">
          {dag.tasks.map((task) => (
            <article key={task.name} className="stack-item">
              <h3>{task.name}</h3>
              <p className="meta-line">Inputs: {task.inputs.join(', ') || 'none'}</p>
              <p className="meta-line">Outputs: {task.outputs.join(', ') || 'none'}</p>
              <p className="meta-line">Deps: {task.deps.join(', ') || 'none'}</p>
            </article>
          ))}
        </div>
        <p className="meta-line">
          Edges: {dag.edges.map((edge) => `${edge.from}→${edge.to}`).join(' · ') || 'none'}
        </p>
      </section>

      <section className="panel">
        <header className="panel-header">
          <h2>Task Durations</h2>
        </header>
        <div className="stack-list">
          {latestRun.tasks.map((task) => (
            <article key={task.name} className="stack-item">
              <h3>
                {task.name} <span className={`badge badge-${task.status}`}>{task.status}</span>
              </h3>
              <p className="meta-line">
                Duration {formatDuration(task.duration_seconds)} · Started{' '}
                {formatDateTime(task.started_at)}
              </p>
              {task.logs.length > 0 ? (
                <p className="meta-line">
                  Logs:{' '}
                  {task.logs
                    .map((log) => `[${log.level}] ${log.message}`)
                    .join(' | ')}
                </p>
              ) : null}
              {task.error ? <p className="meta-line">{task.error}</p> : null}
            </article>
          ))}
        </div>
      </section>

      <section className="panel">
        <header className="panel-header">
          <h2>Provenance</h2>
        </header>
        <p className="meta-line">Git SHA: {provenance.git_sha}</p>
        <p className="meta-line">
          Python {provenance.pipeline.python_version} · {provenance.pipeline.platform}
        </p>
        <p className="meta-line">
          Artifact map:{' '}
          {Object.entries(provenance.artifacts)
            .map(([key, value]) => `${key}=${value}`)
            .join(' · ')}
        </p>
      </section>
    </div>
  )
}
