/** A deliberately limited local compiler. Parsing is not delegated to a model. */
import {clamp,norm} from './math.mjs';
export const clone=s=>JSON.parse(JSON.stringify(s));
export const empty=()=>({version:3,created:false,lighting:'sunset',revision:0,objects:[],relations:[],path:[],selected:'microscope-1'});
const object=(id,type,name,x,y,z)=>({id,type,name,position:{x,y,z},yaw:0,color:null});
const structural=['bench','window'];
export function laboratory(previous=empty()){
 const s=clone(previous);s.created=true;
 const defaults=[object('bench-1','bench','Workbench',0,0,-1.8),object('window-1','window','Window',0,1.8,-4),object('microscope-1','microscope','Microscope',-1,1,-1.5),object('arm-1','arm','Robotic arm',1.05,1,-1.7),object('agent-1','agent','Agent',-2.8,0,2.4)];
 for(const o of defaults)if(!s.objects.some(x=>x.id===o.id))s.objects.push(o);
 s.relations=[{from:'microscope-1',to:'bench-1',type:'on'},{from:'arm-1',to:'bench-1',type:'on'},{from:'microscope-1',to:'arm-1',type:'beside'}];return s;
}
export function valid(s){return !!s&&s.version===3&&typeof s.created==='boolean'&&['sunset','daylight','night'].includes(s.lighting)&&Number.isSafeInteger(s.revision)&&s.revision>=0&&Array.isArray(s.objects)&&s.objects.length<=24&&Array.isArray(s.path)&&s.path.length<1000&&Array.isArray(s.relations)&&s.relations.length<80&&s.relations.every(r=>r&&typeof r.from==='string'&&typeof r.to==='string'&&['on','beside'].includes(r.type))&&s.path.every(p=>p&&['x','y','z'].every(k=>Number.isFinite(p[k])&&Math.abs(p[k])<15))&&s.objects.every(o=>o&&typeof o.id==='string'&&/^[a-z]+-\d+$/.test(o.id)&&typeof o.name==='string'&&o.name.length<80&&['bench','window','microscope','arm','agent','plant','lamp','sphere','cube'].includes(o.type)&&Number.isFinite(o.yaw)&&(!o.color||/^#[0-9a-f]{6}$/i.test(o.color))&&['x','y','z'].every(k=>Number.isFinite(o.position?.[k])&&Math.abs(o.position[k])<15))&&new Set(s.objects.map(o=>o.id)).size===s.objects.length&&(!s.created||['bench-1','window-1','microscope-1','arm-1','agent-1'].every(id=>s.objects.some(o=>o.id===id)));}
function find(s,name){name=name.trim().replace(/^(the|a|an) /,'');const type={'robotic arm':'arm',robot:'agent',workbench:'bench',laboratory:'lab'}[name]||name;if(name==='it')return s.objects.find(o=>o.id===s.selected);return s.objects.find(o=>o.type===type||o.id===name);}
export function isFree(s,x,z,ignore=null){if(Math.abs(x)>3.85||z< -3.7||z>3.65)return false;if(Math.abs(x)<2.5&&z> -3.15&&z<-.44)return false;return !s.objects.some(o=>!structural.includes(o.type)&&!['microscope','arm','agent'].includes(o.type)&&o.position.y<.1&&o.id!==ignore&&Math.hypot(o.position.x-x,o.position.z-z)<.64);}
export function move(s,id,p){const n=clone(s),o=n.objects.find(o=>o.id===id);if(!o)throw Error('Unknown object.');if(structural.includes(o.type))throw Error('The architecture is fixed in this prototype.');const q={...o.position,...p};if(![q.x,q.y,q.z].every(Number.isFinite))throw Error('Coordinates must be finite.');if(o.position.y>.5){q.x=clamp(q.x,-1.65,1.65);q.z=clamp(q.z,-2.55,-1.05);q.y=1;if(n.objects.some(a=>a.id!==id&&a.position.y===1&&Math.hypot(a.position.x-q.x,a.position.z-q.z)<.46))throw Error('That placement overlaps another instrument.');}else{q.y=0;q.x=clamp(q.x,-3.65,3.65);q.z=clamp(q.z,-3.6,3.5);if(!isFree(n,q.x,q.z,id))throw Error('That placement intersects furniture or another floor object.');}o.position=Object.fromEntries(Object.entries(q).map(([k,v])=>[k,+v.toFixed(3)]));n.path=[];return n;}
export function route(s,targetId='microscope-1'){
 const agent=s.objects.find(o=>o.id==='agent-1'),target=s.objects.find(o=>o.id===targetId);if(!agent||!target)throw Error('The agent and destination must exist.');
 const step=.25,start=[Math.round(agent.position.x/step),Math.round(agent.position.z/step)],key=a=>a.join(','),cells=[];
 for(let x=-15;x<=15;x++)for(let z=-14;z<=14;z++)if(isFree(s,x*step,z*step))cells.push([x,z]);
 cells.sort((a,b)=>Math.hypot(a[0]*step-target.position.x,a[1]*step-target.position.z)-Math.hypot(b[0]*step-target.position.x,b[1]*step-target.position.z));if(!cells.length||!isFree(s,start[0]*step,start[1]*step))throw Error('No safe starting cell or route.');const goal=cells[0],parent=new Map([[key(start),null]]),queue=[start];let found=false;
 for(let i=0;i<queue.length;i++){const c=queue[i];if(key(c)===key(goal)){found=true;break;}for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const n=[c[0]+dx,c[1]+dz];if(!parent.has(key(n))&&isFree(s,n[0]*step,n[1]*step)){parent.set(key(n),c);queue.push(n);}}}
 if(!found)throw Error('No collision-free path was found.');const path=[];let p=goal;while(p){path.push({x:p[0]*step,y:0,z:p[1]*step});p=parent.get(key(p));}path.reverse();const n=clone(s);n.path=path;n.objects.find(o=>o.id===agent.id).position={...path.at(-1)};return n;
}
export function difference(a,b){const d=[];if(a.created!==b.created)d.push('Laboratory created');if(a.lighting!==b.lighting)d.push(`Lighting: ${a.lighting} → ${b.lighting}`);for(const o of b.objects){const old=a.objects.find(x=>x.id===o.id);if(!old){d.push(`Create ${o.name} · ${o.id}`);continue;}for(const k of ['x','y','z'])if(o.position[k]!==old.position[k])d.push(`${o.id}.${k}: ${old.position[k]} → ${o.position[k]}`);if(o.yaw!==old.yaw)d.push(`${o.id}.rotation: ${old.yaw}° → ${o.yaw}°`);if(o.color!==old.color)d.push(`${o.id}.color: ${o.color}`);}for(const o of a.objects)if(!b.objects.some(x=>x.id===o.id))d.push(`Remove ${o.id}`);if(JSON.stringify(a.path)!==JSON.stringify(b.path))d.push(b.path.length?`Plan path · ${b.path.length-1} collision-free grid steps`:'Invalidate previous route');return d;}
const COLORS={blue:'#538fbf',green:'#608b66',red:'#b96151',white:'#e4e9e3',amber:'#cf9854',purple:'#9c84ba'};
export function compile(input,original){
 if(typeof input!=='string'||input.length>500)throw Error('Use a command up to 500 characters.');if(!valid(original))throw Error('Invalid input scene.');
 const clauses=input.trim().toLowerCase().split(/(?<!\d)\.(?!\d)|;|\n|\bthen\b/).map(x=>x.trim()).filter(Boolean);if(!clauses.length)throw Error('Describe a change first.');let s=clone(original),ops=[];
 for(const c of clauses){let m;
  if(/^(create|build|make) (a |the )?(mountain |alpine )?lab(oratory)?( at (sunset|night|daylight))?$/.test(c)){s=laboratory(s);s.lighting=c.endsWith('night')?'night':c.endsWith('daylight')?'daylight':'sunset';ops.push({op:'create',target:'laboratory',objects:s.objects.map(o=>o.id)});continue;}
  if(!s.created)throw Error('Create the laboratory before editing its objects.');
  if(/^put (a |the )?microscope beside (a |the )?robotic arm$/.test(c)){ops.push({op:'bind-relation',from:'microscope-1',relation:'beside',to:'arm-1'});continue;}
  if((m=c.match(/^(move|put) (?:the )?(.+?) closer to (?:the )?(.+)$/))){const o=find(s,m[2]),target=find(s,m[3]);if(!o||!target)throw Error('The named object or destination does not exist.');const p={x:o.position.x+(target.position.x-o.position.x)*.2,z:o.position.z+(target.position.z-o.position.z)*.3};s=move(s,o.id,p);s.selected=o.id;ops.push({op:'move',id:o.id,toward:target.id});continue;}
  if((m=c.match(/^move (?:the )?(.+?) (left|right|forward|back|backward)(?: by)?(?: (\d+(?:\.\d+)?) ?(?:metres?|meters?|m))?$/))){const o=find(s,m[1]);if(!o)throw Error('That object does not exist.');const axis=['left','right'].includes(m[2])?'x':'z',d=(['left','back','backward'].includes(m[2])?-1:1)*clamp(+(m[3]||.4),0,2);s=move(s,o.id,{[axis]:o.position[axis]+d});s.selected=o.id;ops.push({op:'translate',id:o.id,axis,metres:d});continue;}
  if((m=c.match(/^(?:make it|set (?:the )?lighting to) (day|daylight|sunset|night)$/))){s.lighting=m[1]==='day'?'daylight':m[1];ops.push({op:'lighting',value:s.lighting});continue;}
  if((m=c.match(/^add (?:a |an |another )?(?:(blue|green|red|white|amber|purple) )?(plant|lamp|sphere|cube)$/))){if(s.objects.length>=24)throw Error('The 24-object scene limit has been reached.');let i=1;while(s.objects.some(o=>o.id===m[2]+'-'+i))i++;const floor=['plant','lamp'].includes(m[2]);const spots=floor?[[3,-2.6],[-3,-2.5],[3,1.5],[-3,1],[2.8,2.8]]:[[.1,-1.25],[.1,-2.4],[-1.55,-2.4],[1.55,-1.15]];const p=spots.find(([x,z])=>floor?isFree(s,x,z):!s.objects.some(o=>o.position.y===1&&Math.hypot(o.position.x-x,o.position.z-z)<.5));if(!p)throw Error('No non-overlapping placement remains for that object.');const o=object(m[2]+'-'+i,m[2],m[2][0].toUpperCase()+m[2].slice(1),p[0],floor?0:1,p[1]);o.color=m[1]?COLORS[m[1]]:null;s.objects.push(o);s.selected=o.id;s.path=[];ops.push({op:'add',id:o.id,position:o.position});continue;}
  if((m=c.match(/^rotate (?:the )?(.+?) (?:by )?(-?\d+(?:\.\d+)?) degrees?$/))){const o=find(s,m[1]);if(!o||structural.includes(o.type))throw Error('Choose a movable object.');o.yaw=(o.yaw+ +m[2])%360;s.selected=o.id;ops.push({op:'rotate',id:o.id,degrees:+m[2]});continue;}
  if((m=c.match(/^make (?:the )?(.+?) (blue|green|red|white|amber|purple)$/))){const o=find(s,m[1]);if(!o||structural.includes(o.type))throw Error('Choose a movable object.');o.color=COLORS[m[2]];ops.push({op:'material',id:o.id,color:o.color});continue;}
  if((m=c.match(/^(?:send|move|walk) (?:the )?agent to (?:the )?(.+)$/))){const o=find(s,m[1]);if(!o)throw Error('That destination is not in the scene.');s=route(s,o.id);ops.push({op:'route',id:'agent-1',target:o.id,steps:s.path.length-1});continue;}
  if((m=c.match(/^remove (?:the )?(.+)$/))){const o=find(s,m[1]);if(!o||['bench','window','arm','microscope','agent'].includes(o.type))throw Error('Only added objects can be removed in this prototype.');s.objects=s.objects.filter(x=>x.id!==o.id);s.relations=s.relations.filter(r=>r.from!==o.id&&r.to!==o.id);s.path=[];ops.push({op:'remove',id:o.id});continue;}
  throw Error(`Unsupported clause: “${c}”. No changes applied. Try a displayed example or use direct manipulation.`);
 }
 const diff=difference(original,s);if(diff.length)s.revision=original.revision+1;if(!valid(s))throw Error('The proposed scene did not pass validation.');return{state:s,ops,diff,clauses};
}
