import {T,box,ball,line,rod,ring,arrow,clear,V,mesh,material} from './stage.mjs';
import {replayState,rankState,constraints,memories,incoming,posteriorExample,dot,sub,norm,scale,add} from './math.mjs';
import {exhibit,slider,btn,stat,fmt} from './ui.mjs';
const colors={current:'#3388bc',joint:'#c08a35',memory:'#278f83',residual:'#d35d4c',violet:'#ae95df'};
function dashed(g,a,b,color,r=.012){const av=V(a),bv=V(b);for(let j=0;j<14;j+=2)rod(g,av.clone().lerp(bv,j/14).toArray(),av.clone().lerp(bv,(j+1)/14).toArray(),r,color);}
export function mountReplay(root){
 let selected=[0],learning=0,correction=1,previous=null;
 const ui=exhibit(root,{theme:'replay-world',title:'Memory is a direction, not a pile of data',intro:'The model moves. Its old skills move with it.',controls:`<div class="memory-library"><span>Choose up to three stored memories</span><div>${memories.map((m,i)=>btn('memory'+i,`<b>${m.name}</b><small>${i===1?'Same direction as A':'An independent old skill'}</small>`)).join('')}</div></div>${slider('learn','Learn the new task',0,1,0,.02)}${slider('correction','Replay correction',0,1,1,.02)}`,math:'<p>Three parameters θ serve three old skills, each with target zero. Old loss is ½‖θ‖². The new task wants u = (1.35, 1.05, 0.9), with loss ½‖θ−u‖². Equal-weight full-history training would choose u/2. This oracle is shown only to expose the correction the memory buffer needs.</p><p>We orthogonalize the selected memory directions and project the desired correction onto their span. The second A memory is deliberately redundant. The red segment is the Euclidean residual—not another optimizer update. The illustration uses signed span projection, not a claim about nonnegative replay weights or a particular memory-selection algorithm.</p>',boundary:'A transparent local quadratic example. The research question is which corrections a finite buffer can supply; these numbers are not manuscript results.'});
 const view=ui.stage({background:'#eef4f0',camera:[6.5,5.6,8.5],target:[-.65,1.0,.65],onPick:id=>toggle(+id)});
 const origin=[-1.8,.12,-.65],P=v=>[origin[0]+v[0]*2.1,origin[1]+v[2]*2.1,origin[2]+v[1]*2.1];
 function toggle(i){ui.stop();if(selected.includes(i))selected=selected.filter(x=>x!==i);else if(selected.length<3)selected.push(i);else{selected=selected.slice(1);selected.push(i);}learning=1;draw();}
 function draw(){const s=replayState(selected,learning,correction);ui.state(s);ui.set('learn',learning);ui.set('correction',correction);root.querySelectorAll('.memory-library button').forEach((b,i)=>b.setAttribute('aria-pressed',String(selected.includes(i))));
 ui.read.innerHTML=`<div class="vector-key"><span style="--key:${colors.current}">Current-only update</span><span style="--key:${colors.joint}">Full-history oracle</span><span style="--key:${colors.memory}">Available correction</span><span style="--key:${colors.residual}">Still missing</span></div>${stat('Independent memory directions',s.directions,' / 3')}${stat('Unrealizable correction',fmt(s.missing))}<div class="skill-readings"><h3>Earlier capability error</h3>${['A','B','C'].map((n,i)=>`<div><span>Skill ${n}</span><i><b style="width:${Math.min(100,s.actual[i]**2/2*100)}%"></b></i><strong>${fmt(s.actual[i]**2/2,2)}</strong></div>`).join('')}</div>${stat('Old-task loss',fmt(s.oldLoss))}${stat('New-task loss',fmt(s.newLoss))}`;
 ui.story(learning<.05?'Three old skills. One shared model.':s.directions<3?'A second memory can add nothing.':'The missing direction was in the memory—not the optimizer.',learning<.05?'Move toward the new task. Watch all three earlier skills move away from their target.':s.directions<3?`The buffer has ${selected.length} memories but only ${s.directions} independent directions. The red residual is what no combination of these memories can repair.`:'A, B and C supply the full correction toward the oracle. The old and new losses are still nonzero: the tasks compete.',learning<.05?'Learn the new task':s.directions<3?'Choose A, B and C':'Compare with two copies of A');
 if(!view)return;clear(view.content);const g=view.content,picks=[],labels=[];
 const axes=[[1.65,0,0],[0,1.55,0],[0,0,1.55]];axes.forEach((a,i)=>{rod(g,P([0,0,0]),P(a),.01,'#9bb6ab');labels.push({text:'parameter '+['A','B','C'][i],pos:P(a),tone:'light-label'});});
 for(let i=0;i<=6;i++){line(g,[P([i*.3,0,0]),P([i*.3,1.65,0])],'#d5e2da',.006);line(g,[P([0,i*.3,0]),P([1.65,i*.3,0])],'#d5e2da',.006);}
 ball(g,P([0,0,0]),.10,'#708b7e');ring(g,P([0,0,0]),.23,'#8bab9c');
 arrow(g,P([0,0,0]),P(s.current),colors.current,.039);ball(g,P(s.current),.12,colors.current,{metalness:.5});
 dashed(g,P([0,0,0]),P(s.joint),colors.joint,.022);ball(g,P(s.joint),.08,colors.joint,{transparent:true,opacity:.45});ring(g,P(s.joint),.16,colors.joint,[0,0,0]);
 if(learning>.05){labels.push({text:'Current-only learning',pos:add(P(s.current),[.25,.43,-.2]),tone:'blue'});labels.push({text:'Full-history oracle · unavailable',pos:add(P(s.joint),[-.2,.6,-.4]),tone:'amber'});}
 for(const i of [0,2,3]){const m=memories[i],amount=dot(s.desired,m.v),end=add(s.current,scale(m.v,amount));const used=selected.includes(i)||(i===0&&selected.includes(1));arrow(g,P(s.current),P(end),used?colors.memory:'#a5bbb1',.016,{transparent:true,opacity:used?.8:.32});const b=ball(g,P(end),.065,used?colors.memory:'#adc3b7');b.userData.pick=String(i);picks.push(b);}
 arrow(g,P(s.current),P(s.actual),colors.memory,.047);dashed(g,P(s.actual),P(s.joint),colors.residual,.025);
 const marker=ball(g,P(s.actual),.13,'#edf9ef',{metalness:.45,roughness:.15});ring(g,P(s.actual),.19,colors.memory,[0,0,0],.018);
 if(learning>.05&&s.missing>.01)labels.push({text:`Unreachable residual  ${fmt(s.missing)}`,pos:add(P(scale(add(s.actual,s.joint),.5)),[.15,-.38,.4]),tone:'red'});
 view.setLabels(labels);view.setPickables(picks);
 const from=previous||s.actual;let start=null;view.setTick((t,dt)=>{start??=t;const a=dt===0?1:Math.min(1,(t-start)/.65),k=1-(1-a)**3;marker.position.copy(V(P(from))).lerp(V(P(s.actual)),k);});previous=s.actual.slice();
 }
 memories.forEach((_,i)=>ui.on('memory'+i,()=>toggle(i)));ui.input('learn',v=>{learning=v;draw();});ui.input('correction',v=>{correction=v;draw();});ui.on('next',()=>{if(learning<.05)learning=1;else if(replayState(selected).directions<3)selected=[0,2,3];else selected=[0,1];draw();});ui.on('reset',()=>{selected=[0];learning=0;correction=1;draw();});ui.sequence(i=>{learning=i===0?0:1;selected=i<2?[0]:i===2?[0,1]:[0,2,3];correction=i===1?0:1;draw();});draw();return ui;
}
function clippedRegion(){
 const l=-2.4,h=2.6;let faces=[[[l,l,l],[l,l,h],[l,h,h],[l,h,l]],[[h,l,h],[h,l,l],[h,h,l],[h,h,h]],[[l,l,h],[l,l,l],[h,l,l],[h,l,h]],[[l,h,l],[l,h,h],[h,h,h],[h,h,l]],[[l,l,l],[l,h,l],[h,h,l],[h,l,l]],[[l,l,h],[h,l,h],[h,h,h],[l,h,h]]];
 for(const {n,b} of constraints){const next=[],intersections=[];for(const face of faces){const poly=[];for(let i=0;i<face.length;i++){const a=face[i],c=face[(i+1)%face.length],da=dot(n,a)-b,dc=dot(n,c)-b;if(da>=-1e-8)poly.push(a);if((da>=0)!==(dc>=0)){const t=da/(da-dc),p=add(a,scale(sub(c,a),t));poly.push(p);if(!intersections.some(q=>norm(sub(q,p))<1e-6))intersections.push(p);}}if(poly.length>=3)next.push(poly);}if(intersections.length>=3){const mid=scale(intersections.reduce(add,[0,0,0]),1/intersections.length),normal=V(n).normalize(),u=new T.Vector3().crossVectors(normal,Math.abs(normal.y)<.9?new T.Vector3(0,1,0):new T.Vector3(1,0,0)).normalize(),v=new T.Vector3().crossVectors(normal,u);intersections.sort((a,b)=>Math.atan2(V(sub(a,mid)).dot(v),V(sub(a,mid)).dot(u))-Math.atan2(V(sub(b,mid)).dot(v),V(sub(b,mid)).dot(u)));next.push(intersections);}faces=next;}
 const data=[];for(const f of faces)for(let i=1;i<f.length-1;i++)data.push(...f[0],...f[i],...f[i+1]);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(data,3));geo.computeVertexNormals();return geo;
}
export function mountRank(root){
 let rank=1,budget=.60,attempted=false;
 const ui=exhibit(root,{theme:'rank-world',title:'The space of possible repairs',intro:'Before asking how to optimize, ask whether a solution exists.',controls:`<div class="rank-select"><span>Adapter freedom</span><div>${[1,2,3].map(r=>btn('rank'+r,`<b>${r}</b><small>${['a line','a plane','a volume'][r-1]}</small>`)).join('')}</div></div>${slider('budget','Allowed change cost',.2,1.6,.6,.02)}${btn('attempt','Try to solve')}`,math:'<p>This is an exact three-dimensional linear-constraint example, not the full nonlinear LoRA model. Rank selects span(e₁,…,eᵣ). The constraints are x + z ≥ 1.4, −x + z ≥ 0.7 and y ≥ 0.65. At ranks one and two, z = 0, so the first two requirements contradict each other.</p><p>At rank three, active-set enumeration solves min ½‖δ‖² subject to the three inequalities. We show a repair only after finding a feasible point and checking all its constraints. The translucent sphere is the separate allowed-change budget. The green region is clipped to a finite display box.</p>',boundary:'The minimal repair is (0.35, 0.65, 1.05), with cost 0.82375 in this illustrative isotropic current-task metric. No unpublished experimental or contribution claim is inferred from this example.'});
 const view=ui.stage({background:'#111322',dark:true,camera:[6.3,4.0,7.4],target:[0,.85,.55]});
 function draw(){const s=rankState(rank,budget);ui.state({...s,attempted});ui.set('budget',budget.toFixed(2));root.querySelectorAll('.rank-select button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i+1===rank)));
 ui.read.innerHTML=`<h3>Three obligations</h3><div class="constraint-list">${constraints.map((c,i)=>`<div><span>${c.name}</span><code>${['x + z ≥ 1.40','−x + z ≥ 0.70','y ≥ 0.65'][i]}</code><small>${s.feasible?'Satisfied at the repair':'Must be satisfied'}</small></div>`).join('')}</div>${stat('Feasible repair',s.feasible?'Found':'Does not exist')}${stat('Minimum change cost',s.cost===null?'—':fmt(s.cost))}<div class="w-callout">${!s.feasible?'No solution is drawn: in this subspace the requirements contradict one another.':s.affordable?'Inside the allowed-change budget. Both conditions hold.':'The smallest feasible repair lies outside the allowed-change budget.'}</div>`;
 ui.story(!s.feasible?'More training cannot escape this space.':!s.affordable?'Possible. Still too expensive.':'The shortest admissible repair is now available.',!s.feasible?(attempted?'The solver found no feasible point. With z = 0, you need x ≥ 1.40 and x ≤ −0.70 at the same time.':'The pale adapter space misses the entire feasible region. Expanding from a line to a plane still cannot supply z.'):!s.affordable?'The green region exists, and the solver finds its nearest point. But that point is outside the cost sphere.':'The repair satisfies all three obligations and the separate cost budget. Its coordinates and cost are computed, not animated into existence.',!s.feasible?'Unlock the next direction':!s.affordable?'Allow the minimum change':'Restrict the adapter again');
 if(!view)return;clear(view.content);const g=view.content,labels=[];box(g,[0,-.18,0],[6.2,.16,6.2],'#212438',{metalness:.3,roughness:.5});
 for(const [i,col] of [[0,'#9da3bd'],[1,'#9da3bd'],[2,'#7b719d']]){const end=[0,0,0];end[i]=3;arrow(g,[0,0,0],end,col,.012);labels.push({text:['x','y','z'][i],pos:end,tone:'plain'});}
 if(rank===1)rod(g,[-2.8,0,0],[2.8,0,0],.045,'#baa9ec',{emissive:'#baa9ec',emissiveIntensity:.25});
 if(rank===2){const plane=mesh(g,new T.PlaneGeometry(5.6,4.6),'#b9a6e5',[0,1.5,0],{transparent:true,opacity:.19,side:T.DoubleSide,depthWrite:false});const e=new T.LineSegments(new T.EdgesGeometry(plane.geometry),new T.LineBasicMaterial({color:'#c6b5ed'}));plane.add(e);}
 if(rank===3){const cube=mesh(g,new T.BoxGeometry(5.6,4.6,5.6),'#b9a6e5',[0,1.5,0],{transparent:true,opacity:.035,depthWrite:false,side:T.DoubleSide});const e=new T.LineSegments(new T.EdgesGeometry(cube.geometry),new T.LineBasicMaterial({color:'#837797',transparent:true,opacity:.6}));cube.add(e);}
 constraints.forEach(({n,b},i)=>{const normal=V(n).normalize(),center=V(n).multiplyScalar(b/dot(n,n));const m=mesh(g,new T.PlaneGeometry(5.2,5.2),['#d7a76b','#af8ecd','#85acb4'][i],center.toArray(),{transparent:true,opacity:.10,side:T.DoubleSide,depthWrite:false});m.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),normal);const edges=new T.LineSegments(new T.EdgesGeometry(m.geometry),new T.LineBasicMaterial({color:['#d7a76b','#af8ecd','#85acb4'][i],transparent:true,opacity:.45}));m.add(edges);});
 const feasible=mesh(g,clippedRegion(),'#6cc7a5',[0,0,0],{transparent:true,opacity:rank===3?.19:.05,depthWrite:false,side:T.DoubleSide,roughness:.25});const fe=new T.LineSegments(new T.EdgesGeometry(feasible.geometry,10),new T.LineBasicMaterial({color:'#74d1b2',transparent:true,opacity:rank===3?.7:.22}));feasible.add(fe);
 const sphere=mesh(g,new T.SphereGeometry(s.radius,32,22),'#a5add0',[0,0,0],{transparent:true,opacity:.045,depthWrite:false,wireframe:false});ring(g,[0,0,0],s.radius,'#6e7295',[0,0,0],.012);ring(g,[0,0,0],s.radius,'#6e7295');ball(g,[0,0,0],.07,'#edf0ff');
 if(s.repair){arrow(g,[0,0,0],s.repair,s.affordable?'#83e1b5':'#efba73',.031);ball(g,s.repair,.12,s.affordable?'#96f0c6':'#f0bd79',{metalness:.5,roughness:.18});labels.push({text:'Minimum-norm repair',pos:add(s.repair,[0,.45,0]),tone:s.affordable?'green':'amber'});labels.push({text:'All three obligations satisfied',pos:[1.45,2.25,2.3],tone:'green'});}else labels.push({text:'No intersection. No repair.',pos:[0,2.55,0],tone:'red'});
 labels.push({text:'Allowed change',pos:[-s.radius-.22,.25,0],tone:'plain'});view.setLabels(labels);view.setPickables([]);
 }
 [1,2,3].forEach(r=>ui.on('rank'+r,()=>{rank=r;attempted=false;draw();}));ui.input('budget',v=>{budget=v;draw();});ui.on('attempt',()=>{attempted=true;draw();});ui.on('next',()=>{const s=rankState(rank,budget);if(rank<3)rank++;else if(!s.affordable)budget=.9;else rank=1;draw();});ui.on('reset',()=>{rank=1;budget=.6;attempted=false;draw();});ui.sequence(i=>{rank=[1,2,3,3][i];budget=i===3?.9:.6;draw();});draw();return ui;
}
function gaussianSurface(state,color,wire=false){const n=48,m=36,positions=[],indices=[],cols=[],c=new T.Color(color);for(let j=0;j<=m;j++)for(let i=0;i<=n;i++){const x=-4+i/n*8,z=-3+j/m*6,q=((x-state.m[0])/state.c[0])**2+((z-state.m[1])/state.c[1])**2,h=Math.exp(-q/2)/(2*Math.PI*state.c[0]*state.c[1])*4;positions.push(x,h,z);const col=c.clone().lerp(new T.Color('#fff6de'),Math.min(.65,h*.24));cols.push(col.r,col.g,col.b);}for(let j=0;j<m;j++)for(let i=0;i<n;i++){const a=j*(n+1)+i;indices.push(a,a+n+1,a+1,a+1,a+n+1,a+n+2);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('color',new T.Float32BufferAttribute(cols,3));geo.setIndex(indices);geo.computeVertexNormals();return new T.Mesh(geo,new T.MeshStandardMaterial({color:wire?color:'#ffffff',vertexColors:!wire,wireframe:wire,transparent:wire,opacity:wire?.3:1,side:T.DoubleSide,metalness:wire?0:.5,roughness:.26}));}
export function mountNatural(root){
 let steps=0,method='natural',animation=null;
 const ui=exhibit(root,{theme:'posterior-world',title:'A belief has a shape',intro:'Learning must move the estimate—and reshape its uncertainty.',controls:`${slider('steps','Optimization steps',0,80,0)}<div class="geometry-buttons">${btn('natural','Natural geometry')}${btn('euclidean','Euclidean geometry')}${btn('run','Run 20 steps')}</div>`,math:'<p>We use the exact diagonal Gaussian specialization of Algorithm 1 in the linked preprint. Target mean (1, −0.5), precision (1,7), initial mean (−2,1.5), initial standard deviations (0.8,0.45), step size 0.07. Both updates use the previous covariance factor. The surface height is probability density—not the optimization loss.</p><p>The computed KL is ½Σ[hⱼ(mⱼ−μⱼ)² + hⱼcⱼ² − log(hⱼcⱼ²) − 1]. The second trajectory is a Euclidean update with the same starting point and step size, not a claim of universal speed superiority.</p>',boundary:'The paper’s contribution is a convergence analysis under its assumptions. This analytic visualization illustrates the update; it does not reproduce an empirical benchmark.'});
 const view=ui.stage({background:'#111d24',dark:true,camera:[7.5,6.3,8.5],target:[0,.3,0]});
 function draw(){const s=posteriorExample(steps,method);ui.state({steps,method,m:s.m,c:s.c,kl:s.kl});ui.set('steps',steps);ui.read.innerHTML=`<h3>The target stays fixed.</h3><p>The filled surface is the current Gaussian belief. The fine gold mesh is the target.</p>${stat('KL divergence',fmt(s.kl))}${stat('Mean',s.m.map(v=>fmt(v,2)).join(', '))}${stat('Standard deviations',s.c.map(v=>fmt(v,2)).join(', '))}<div class="convergence-chart"><span>Computed divergence</span><canvas width="460" height="180" aria-label="Computed KL divergence by step"></canvas></div>`;
 const cv=ui.read.querySelector('canvas'),ctx=cv.getContext('2d');ctx.clearRect(0,0,460,180);ctx.strokeStyle='#638596';ctx.beginPath();ctx.moveTo(15,160);ctx.lineTo(445,160);ctx.stroke();ctx.strokeStyle='#d8b975';ctx.lineWidth=3;ctx.beginPath();s.loss.forEach((v,i)=>{const x=15+i/80*430,y=158-v/s.loss[0]*135;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();root.querySelector('[data-act="natural"]').setAttribute('aria-pressed',method==='natural');root.querySelector('[data-act="euclidean"]').setAttribute('aria-pressed',method==='euclidean');
 ui.story(steps<2?'An estimate is more than a point.':steps<20?'The mean moves. The geometry changes.':'The belief now fits the target.',steps<2?'The peak is your estimate; the spread is its uncertainty. A learning rule has to update both.':'Every frame follows the update equations. The error trace is computed from the actual Gaussian distributions.',steps<20?'Run 20 actual steps':'Compare the other geometry');if(!view)return;clear(view.content);const g=view.content;
 for(let x=-4;x<=4;x++)line(g,[[x,.002,-3],[x,.002,3]],'#263c49',.008);for(let z=-3;z<=3;z++)line(g,[[-4,.002,z],[4,.002,z]],'#263c49',.008);
 const target=gaussianSurface({m:[1,-.5],c:[1,1/Math.sqrt(7)]},'#deb577',true);target.position.y=.012;g.add(target);const surface=gaussianSurface(s,'#3c9db0');surface.castShadow=true;surface.receiveShadow=true;g.add(surface);
 const path=s.path.map(p=>[p.m[0],.035,p.m[1]]);if(path.length>1)line(g,path,'#eee0ba',.025);for(let k=1;k<=3;k++){const pts=Array.from({length:97},(_,i)=>{const a=i/96*Math.PI*2;return[1+Math.cos(a)*k,.027,-.5+Math.sin(a)*k/Math.sqrt(7)];});line(g,pts,'#866e48',.009);}
 const h=4/(2*Math.PI*s.c[0]*s.c[1]);view.setLabels([{text:'Your current belief',pos:[s.m[0],h+.34,s.m[1]],tone:'blue'},{text:'Target posterior',pos:[2.2,.55,-1.55],tone:'amber'}]);view.setPickables([]);
 }
 function run(){clearInterval(animation);animation=setInterval(()=>{steps=Math.min(80,steps+1);draw();if(steps%20===0||steps===80)clearInterval(animation);},70);}
 ui.input('steps',v=>{clearInterval(animation);steps=v;draw();});for(const m of ['natural','euclidean'])ui.on(m,()=>{clearInterval(animation);method=m;draw();});ui.on('run',run);ui.on('next',()=>{if(steps<20)run();else{method=method==='natural'?'euclidean':'natural';draw();}});ui.on('reset',()=>{clearInterval(animation);steps=0;method='natural';draw();});ui.sequence(i=>{clearInterval(animation);steps=[0,1,20,60][i];draw();});const dispose=ui.dispose.bind(ui);ui.dispose=()=>{clearInterval(animation);dispose();};draw();return ui;
}
