import {T,box,ball,line,rod,ring,clear,arrow,V} from './stage.mjs?v=scroll-4.2.1';
import {graphState,graphEdges,signedGraph,wrap} from './math.mjs?v=scroll-4.2.1';
import {exhibit,slider,btn,stat,fmt} from './ui.mjs?v=scroll-4.2.1';
const names='ABCDE',positions=[[-2.5,.9,.8],[-1.3,3.0,-.4],[1.1,3.25,-.45],[2.55,1.0,.4],[0,.45,2.0]];
const color={blue:'#85cee4',gold:'#efba6a',red:'#ec7f71',ink:'#234759'};
export function mountGain(root){
 let angles=[0,0,0,0,0,0,0],active=1,cycle=-1,trace=0,repairFlash=false;
 const ui=exhibit(root,{theme:'observatory',title:'The consistency observatory',intro:'Seven local instructions. One network that must agree.',controls:`<div class="edge-palette"><span>Choose a relationship</span><div>${graphEdges.map(([u,v],i)=>btn('edge-'+i,`${names[u]}–${names[v]}`)).join('')}</div></div>${slider('angle','Relative orientation',-180,180,0,1,'°')}<div class="cycle-list"></div>`,math:'<p>Each directed edge has unit gain exp(iθ). The normalized Laplacian is L = I − D⁻½AD⁻½. We diagonalize its real symmetric block representation and pair the duplicated eigenvalues. The three shown cycles form a fundamental cycle basis, not a list of every cycle.</p><p>Repair enumerates every spanning tree of this seven-edge example and finds a balanced assignment with the fewest changed edges. This is an exact finite search, not a scalable repair algorithm or a new theorem.</p>',boundary:'This five-node worked example illustrates the published framework. Device orientations are a concrete interpretation, not a validated sensor deployment.'});
 const view=ui.stage({background:'#081824',dark:true,camera:[5.6,3.5,6.7],target:[0,1.65,.3],onPick:id=>{if(id.startsWith('edge')){active=+id.slice(4);cycle=-1;ui.stop();draw();}}});
 let particles=[];
 if(view){ring(view.fixed,[0,-.10,0],4.2,'#183a4c');ring(view.fixed,[0,-.09,0],3.9,'#153445');for(let i=0;i<48;i++){const a=i/48*Math.PI*2;rod(view.fixed,[Math.cos(a)*4.12,-.07,Math.sin(a)*4.12],[Math.cos(a)*4.22,-.07,Math.sin(a)*4.22],.008,'#345665');}const arch=ring(view.fixed,[0,1.8,-1.15],3.55,'#193d50',[0,0,0],.018);arch.rotation.y=.16;}
 function draw(){const s=graphState(angles);ui.state({...s,active,cycle});ui.set('angle',angles[active],'°');root.querySelectorAll('.edge-palette button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===active)));
  ui.read.innerHTML=`<h3>Normalized Laplacian</h3><p class="math-label">L = I − D⁻½ A D⁻½</p><div class="complex-matrix">${s.re.map((r,i)=>r.map((v,j)=>{const im=s.im[i][j],changed=(graphEdges[active][0]===i&&graphEdges[active][1]===j)||(graphEdges[active][1]===i&&graphEdges[active][0]===j);return `<span class="${changed?'matrix-changed':''}">${fmt(v,2)}${Math.abs(im)>.001?`<small>${im<0?'−':'+'}${fmt(Math.abs(im),2)}i</small>`:''}</span>`;}).join('')).join('')}</div><p class="rail-caption">Five real eigenvalues</p><div class="eigen-bars">${s.eigenvalues.map((v,i)=>`<div><i style="height:${3+v*55}px;background:${i===0?color.gold:color.blue}"></i><span>${fmt(v)}</span></div>`).join('')}</div>${stat('Inconsistent fundamental cycles',s.inconsistent,' / 3')}${stat('Smallest eigenvalue',fmt(s.eigenvalues[0]),'',s.inconsistent?'amber':'')}`;
  root.querySelector('.cycle-list').innerHTML=s.cycles.map((c,i)=>`<button data-cycle="${i}" aria-pressed="${cycle===i}">${c.nodes.map(n=>names[n]).join('–')}<small>${Math.abs(c.angle)<1e-7?'Closes exactly':Math.abs(c.angle).toFixed(0)+'° mismatch'}</small></button>`).join('');
  root.querySelectorAll('[data-cycle]').forEach(b=>b.onclick=()=>{cycle=+b.dataset.cycle;trace=performance.now()/1000;ui.stop();draw();});
  ui.story(s.inconsistent?'One instruction cannot fit the whole network.':repairFlash?'The loop closes. Zero returns.':'Every instruction agrees—until you change one.',s.inconsistent?`${s.inconsistent} of the three basis cycles fail to close. Exactly two matrix entries respond to this edge; the spectrum detects a global contradiction.`:'Follow a cycle back to its starting device. Its orientation returns unchanged. Change B–C to make that impossible.',s.inconsistent?`Retune ${s.repair.ids.length} ${s.repair.ids.length===1?'edge':'edges'}`:'Introduce a 110° contradiction');
  if(!view)return;clear(view.content);particles=[];let picks=[],labels=[];
  graphEdges.forEach(([u,v],i)=>{const a=positions[u],b=positions[v],inCycle=cycle>=0&&s.cycles[cycle].nodes.some((n,j,ns)=>n===u&&ns[(j+1)%ns.length]===v||n===v&&ns[(j+1)%ns.length]===u);const affected=s.cycles.some(c=>Math.abs(c.angle)>1e-6&&c.nodes.some((n,j,ns)=>n===u&&ns[(j+1)%ns.length]===v||n===v&&ns[(j+1)%ns.length]===u));const col=i===active?color.gold:inCycle?'#f6dfb0':affected?color.red:color.blue;const mid=V(a).lerp(V(b),.5).toArray();mid[1]+=(i>=5?.42:.10);const m=line(view.content,[a,mid,b],col,i===active?.044:.018,{emissive:col,emissiveIntensity:.15});m.userData.pick='edge'+i;picks.push(m);const p=ball(view.content,a,.052,col,{emissive:col,emissiveIntensity:.8});particles.push({p,curve:new T.CatmullRomCurve3([V(a),V(mid),V(b)]),i});if(i===active){const lp=mid.slice();lp[1]+=.27;labels.push({text:`${names[u]} → ${names[v]}   ${angles[i]}°`,pos:lp,tone:'amber'});}});
  positions.forEach((p,i)=>{ball(view.content,p,.21,'#35566a',{metalness:.75,roughness:.18});ring(view.content,p,.29,i===graphEdges[active][1]?color.gold:'#6d9baa',[0,0,0]);const a=(i===graphEdges[active][1]?angles[active]:0)*Math.PI/180;arrow(view.content,p,[p[0]+.47*Math.cos(a),p[1]+.47*Math.sin(a),p[2]],i===graphEdges[active][1]?color.gold:color.blue,.023);labels.push({text:names[i],pos:[p[0],p[1]+.54,p[2]],tone:'plain'});});
  s.eigenvalues.forEach((v,i)=>{const h=Math.max(.035,v*.9);box(view.content,[-1.1+i*.47,h/2,2.9],[.22,h,.22],i===0?color.gold:'#70bdd4',{metalness:.6,roughness:.24});});labels.push({text:`λmin  ${fmt(s.eigenvalues[0])}`,pos:[-1.1,.27,3.32],tone:'amber'});let transported=null,legs=[],phase=0;const traceStart=performance.now()/1000;
  if(cycle>=0){
   const ns=s.cycles[cycle].nodes,origin=positions[ns[0]];
   const reference=new T.Group();gatherArrow(reference,'#92cfc1');reference.position.copy(V(origin));view.content.add(reference);
   transported=new T.Group();gatherArrow(transported,s.inconsistent?color.gold:'#92cfc1');view.content.add(transported);
   for(let j=0;j<ns.length;j++){const u=ns[j],v=ns[(j+1)%ns.length],ei=graphEdges.findIndex(([a,b])=>a===u&&b===v||a===v&&b===u),a=positions[u],b=positions[v],mid=V(a).lerp(V(b),.5).toArray();mid[1]+=(ei>=5?.42:.10);const angle=angles[ei]*(graphEdges[ei][0]===u?1:-1);legs.push({curve:new T.CatmullRomCurve3([V(a),V(mid),V(b)]),start:phase,angle});phase+=angle;}
   labels.push({text:`Back at ${names[ns[0]]}: ${Math.abs(wrap(phase))}° away from the starting orientation`,pos:[origin[0],origin[1]-.25,origin[2]],tone:Math.abs(wrap(phase))>.01?'amber':'green',dx:-15,dy:25});
  }
  function gatherArrow(group,col){ring(group,[0,0,0],.28,col,[0,0,0],.011);arrow(group,[0,0,.035],[.58,0,.035],col,.028);}
  view.setLabels(labels);view.setPickables(picks);view.setTick(t=>{
   for(const {p,curve,i} of particles)p.position.copy(curve.getPoint(((t*.22+i*.15)%1)));
   if(transported){const elapsed=t===0?legs.length:Math.min(legs.length,Math.max(0,(t-traceStart)/.85)),j=Math.min(legs.length-1,Math.floor(elapsed)),f=elapsed===legs.length?1:elapsed-j;transported.position.copy(legs[j].curve.getPoint(f));transported.rotation.z=(legs[j].start+legs[j].angle*f)*Math.PI/180;root.dataset.transportedAngle=String(wrap(legs[j].start+legs[j].angle*f));}
  });
 }
 graphEdges.forEach((_,i)=>ui.on('edge-'+i,()=>{active=i;cycle=-1;draw();}));ui.input('angle',a=>{angles[active]=a;repairFlash=false;draw();});
 function next(){const s=graphState(angles);if(s.inconsistent){angles=s.repair.target;repairFlash=true;}else{angles[active]=110;repairFlash=false;}draw();}
 ui.on('next',next);ui.on('reset',()=>{angles=Array(7).fill(0);active=1;cycle=-1;draw();});ui.sequence(i=>{angles=Array(7).fill(0);active=1;cycle=i===2?0:-1;if(i===1||i===2)angles[1]=110;repairFlash=i===3;draw();});draw();return ui;
}
export function mountBounds(root){
 let signs=[1,1,1,1,1,1],removed=[],picked=0;const edges=[[0,1],[0,2],[0,3],[1,2],[1,3],[2,3]],pos=[[-2,.65,1.2],[2,.65,1.2],[0,3.0,-.3],[0,.65,-2.1]];
 const ui=exhibit(root,{theme:'structure',title:'The minimum repair',intro:'How many relationships must give before a network can agree?',controls:`<div class="sign-switches">${edges.map(([u,v],i)=>btn('sign'+i,`${names[u]}–${names[v]}  +`)).join('')}</div>`,math:'<p>For x ∈ {−1,+1}⁴, xᵀLx equals four times the number of unsatisfied edges. Rayleigh’s inequality gives frustration ≥ ⌈4λmin/4⌉. The exact answer here checks all eight distinct vertex-sign assignments.</p>',boundary:'This is a four-node signed specialization. The truss is a layout for relationships, not a mechanical load simulation. The published paper has bounds beyond the basic illustration shown here.'});
 const view=ui.stage({background:'#f1eee8',camera:[6,4.5,7],target:[0,1.2,0],onPick:id=>{picked=+id;signs[picked]*=-1;removed=[];draw();}});
 function draw(){const s=signedGraph(signs,removed);ui.state({...s,signs,removed});root.querySelectorAll('.sign-switches button').forEach((b,i)=>{b.textContent=`${names[edges[i][0]]}–${names[edges[i][1]]}  ${signs[i]===1?'+':'−'}`;b.setAttribute('aria-pressed',String(signs[i]<0));});
 ui.read.innerHTML=`<h3>Detection is not repair.</h3><p>A contradiction tells you something must change. The repair count tells you how much.</p>${stat('Certified lower bound',s.lowerBound,' edges')}${stat('Exact minimum removal',s.frustration,' edges')}${stat('Smallest eigenvalue',fmt(s.minimum))}<div class="w-callout">Plus: same sign.<br>Minus: opposite signs.<br>Find one assignment that satisfies all edges.</div>`;
 ui.story(s.frustration?'No assignment satisfies every relationship.':'The remaining relationships can all agree.',s.frustration?`The spectral bound guarantees at least ${s.lowerBound} removal. Exhaustive search finds a repair of ${s.frustration}.`:'The smallest eigenvalue is zero. Introduce a minus edge and watch a contradictory cycle appear.',s.frustration?'Remove a minimum repair':'Flip one relationship');if(!view)return;clear(view.content);const picks=[],labels=[];
 const base=box(view.content,[0,.05,0],[5.8,.22,4.8],'#e1d6c1',{roughness:.65});edges.forEach(([u,v],i)=>{const a=V(pos[u]),b=V(pos[v]),cut=removed.includes(i),col=signs[i]<0?'#b95945':'#536d63';if(cut){rod(view.content,a.toArray(),a.clone().lerp(b,.35).toArray(),.034,'#b5aaa0');rod(view.content,a.clone().lerp(b,.65).toArray(),b.toArray(),.034,'#b5aaa0');}else{const m=rod(view.content,a.toArray(),b.toArray(),.06,col,{metalness:.65,roughness:.25});m.userData.pick=String(i);picks.push(m);}const mid=a.lerp(b,.5);labels.push({text:cut?'removed':signs[i]===1?'+':'−',pos:mid.toArray(),tone:signs[i]<0?'red':'light-label'});});
 pos.forEach((p,i)=>{ball(view.content,p,.2,'#dbccb3',{metalness:.65,roughness:.2});labels.push({text:names[i],pos:[p[0],p[1]+.34,p[2]],tone:'light-label'});});view.setLabels(labels);view.setPickables(picks);
 }
 edges.forEach((_,i)=>ui.on('sign'+i,()=>{signs[i]*=-1;removed=[];draw();}));ui.on('next',()=>{const s=signedGraph(signs,removed);if(s.frustration)removed=s.repair;else{signs[0]*=-1;removed=[];}draw();});ui.on('reset',()=>{signs=Array(6).fill(1);removed=[];draw();});ui.sequence(i=>{signs=i===0?Array(6).fill(1):[-1,1,1,1,1,1];removed=i===3?signedGraph(signs).repair:[];draw();});draw();return ui;
}
