import {T,box,ring,line,clear,V} from './stage.mjs?v=scroll-4.2.2';
import {exhibit,btn,esc,fmt} from './ui.mjs?v=scroll-4.2.2';
import {empty,laboratory,valid,clone,move,compile,route,difference,isFree} from './compiler.mjs?v=scroll-4.2.2';
import {landscape,architecture,makeObject} from './laboratory.mjs?v=scroll-4.2.2';
const KEY='navish-living-world-v3',CREATE='Create a mountain laboratory at sunset. Put a microscope beside a robotic arm.';
export function mountSpatial(root){
 let state=empty(),past=[],future=[],records=[],compiled=null,selected='microscope-1',pending=0,recognition=null,disposed=false,inside=false,dragging=null;
 try{const p=JSON.parse(localStorage.getItem(KEY));if(valid(p))state=p;}catch{}
 const ui=exhibit(root,{theme:'spatial-world',title:'A sentence becomes a place',intro:'Create it once. Keep its identity. Change what you mean.',controls:`<form class="world-language"><label for="scene-command">Describe a world, or change this one</label><div><input id="scene-command" maxlength="500" autocomplete="off" placeholder="${CREATE}"/><button type="submit" class="primary">Compile & apply</button><button type="button" data-act="microphone" aria-label="Use speech recognition">Speak</button></div></form><div class="world-examples">${[['create','Create the laboratory'],['closer','Move the microscope'],['plant','Add a plant'],['night','Change the light'],['route','Route the agent']].map(([id,name])=>btn(id,name)).join('')}</div><p class="compiler-response" role="status">${state.created?'Your previous scene is restored.':'Typed instructions are local. The compiler supports a small, explicit language—not arbitrary AI generation.'}</p><div class="world-secondary">${btn('undo','Undo')}${btn('redo','Redo')}${btn('enter','Step inside')}${btn('export','Export world')}${btn('source','Show scene graph')}<span>Optional speech may send audio to your browser’s provider.</span></div>`,math:'<p>Text is split into clauses, parsed into typed operations, bound to stable object IDs, checked for support and collision constraints, and committed as one atomic revision. If any clause is unsupported, the entire command is rejected without changing the scene.</p><p>Object transforms, materials and identities persist. Orbiting is a camera operation and never edits the scene. Agent navigation uses a deterministic 0.25-metre grid with the workbench and floor objects inflated by its clearance radius. Undo/redo restores complete snapshots.</p>',boundary:'This is a local scene compiler and browser 3D editor. It is not a generative language model, a learned planner or a headset-validated VR system. No paid API is called.'});
 const response=root.querySelector('.compiler-response'),input=root.querySelector('#scene-command');let view=null,architectureGroup=null,objects=new Map(),routeGroup=null,selectionRing=null,tweens=[],labels=[],initial=false,animationStart=0;
 function say(t,error=false){response.textContent=t;response.classList.toggle('error',error);}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{say('Changes are kept in this visit. Local storage is unavailable; export preserves the scene.');}}
 function commit(next,label,ops=[]){if(pending){clearTimeout(pending);pending=0;root.querySelector('.world-language button[type="submit"]').disabled=false;}const diff=difference(state,next);if(!diff.length){say('Already in that state. No object was replaced.');return;}past.push(clone(state));if(past.length>40)past.shift();future=[];next=clone(next);next.revision=state.revision+1;state=next;compiled={ops,diff};records.push({revision:state.revision,label,diff});selected=state.selected||selected;save();draw();say(diff.join(' · '));}
 function run(text,manual=true){if(manual)ui.stop();if(pending){clearTimeout(pending);pending=0;}root.querySelector('.world-language button[type="submit"]').disabled=false;let result;try{result=compile(text,state);}catch(e){compiled={error:e.message,ops:[]};drawPanel();say(e.message,true);return;}compiled=result;drawPanel();say('Parsed → bound to object IDs → placement checked. Applying one revision.');const b=root.querySelector('.world-language button[type="submit"]');b.disabled=true;
  pending=setTimeout(()=>{pending=0;b.disabled=false;commit(result.state,text,result.ops);input.value='';},matchMedia('(prefers-reduced-motion: reduce)').matches?0:480);
 }
 function onDrag(id,p,done){if(done==='cancel'){dragging=null;draw();return;}ui.stop();dragging=done?null:id;try{const next=move(state,id,p);if(done){state.selected=id;commit(next,'Direct manipulation: '+id,[{op:'translate',id,position:p}]);}else{const o=next.objects.find(o=>o.id===id),g=objects.get(id);if(g)g.position.set(o.position.x,o.position.y,o.position.z);}}catch(e){say(e.message,true);if(done)draw();}}
 view=ui.stage({background:'#e4c9ae',camera:[7.3,4.3,10],target:[0,1.2,-1.5],floor:false,onPick:id=>{selected=id;state.selected=id;drawPanel();syncSelection();},onDrag});
 if(view){landscape(view.fixed);box(view.fixed,[0,-.45,0],[10,.3,10],'#aaad9c',{roughness:1});architectureGroup=new T.Group();view.fixed.add(architectureGroup);routeGroup=new T.Group();view.scene.add(routeGroup);view.controls.maxDistance=19;view.controls.minDistance=1.8;}
 function drawPanel(){
 const o=state.objects.find(o=>o.id===selected),ops=compiled?.ops||[];
 ui.read.innerHTML=`<div class="compiler-title"><h3>Words → world state</h3><span>Revision ${state.revision}</span></div><div class="compile-stages"><span class="${compiled?'done':''}">Parse</span><span class="${ops.length?'done':''}">Bind IDs</span><span class="${ops.length?'done':''}">Check</span><span class="${state.created?'done':''}">Commit</span></div><div class="compiled-ops">${compiled?.error?`<p class="compile-error">${esc(compiled.error)}</p>`:ops.length?ops.map(o=>`<div><b>${esc(o.op.toUpperCase())}</b><code>${esc(o.id||o.target||o.from||o.value||'')}${o.to?' → '+esc(o.to):''}${o.steps!==undefined?' · '+o.steps+' steps':''}</code></div>`).join(''):'<p>A command becomes typed operations—not a replacement image.</p>'}</div><h4 class="object-heading">Persistent objects <span>${state.objects.length}</span></h4><div class="object-roster">${state.objects.filter(o=>!['bench','window'].includes(o.type)).map(o=>`<button data-object="${o.id}" aria-pressed="${o.id===selected}"><span>${esc(o.name)}</span><code>${o.id}</code></button>`).join('')||'<p>Start with the laboratory.</p>'}</div>${o?`<div class="coordinate-editor"><span>${esc(o.id)} · metres</span><div>${['x','y','z'].map(k=>`<label>${k}<input aria-label="${k} coordinate" data-axis="${k}" type="number" step="0.1" value="${o.position[k]}" ${k==='y'?'readonly':''}></label>`).join('')}</div></div>`:''}<div class="world-diff"><h4>Last state change</h4>${records.length?records.at(-1).diff.map(d=>`<p>${esc(d)}</p>`).join(''):'<p>No edits in this visit.</p>'}</div><pre class="scene-json" hidden>${esc(JSON.stringify(state,null,2))}</pre>`;
 root.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>{selected=b.dataset.object;state.selected=selected;drawPanel();syncSelection();});root.querySelectorAll('[data-axis]').forEach(e=>e.onchange=()=>{try{commit(move(state,selected,{[e.dataset.axis]:+e.value}),'Coordinate edit: '+selected);}catch(err){say(err.message,true);drawPanel();}});
 root.querySelector('[data-act="undo"]').disabled=!past.length;root.querySelector('[data-act="redo"]').disabled=!future.length;root.querySelector('[data-act="export"]').disabled=!state.created;
 }
 function syncSelection(){if(!view)return;if(selectionRing){view.scene.remove(selectionRing);selectionRing.geometry.dispose();selectionRing.material.dispose();selectionRing=null;}const o=state.objects.find(o=>o.id===selected);if(o&&!['bench','window'].includes(o.type)){selectionRing=ring(view.scene,[o.position.x,o.position.y+.015,o.position.z],o.type==='agent'?.4:.38,'#4bada2');}view.setLabels(state.objects.filter(o=>o.id===selected||o.type==='agent').map(o=>({text:o.name+' · '+o.id,pos:()=>{const g=objects.get(o.id);return g?[g.position.x,g.position.y+(o.type==='agent'?.65:1.1),g.position.z]:[o.position.x,o.position.y+1,o.position.z];},tone:o.id===selected?'green':'light-label'})));view.invalidate();}
 function draw(){ui.state(state);drawPanel();ui.story(!state.created?'Do not generate a new picture. Create a world.':'The microscope moves. The laboratory remembers.',!state.created?'Write the sentence above. Watch it bind objects and relations into one editable scene.':'Select an object to inspect its ID and coordinates. Language, dragging and numeric edits all change the same persistent state.',!state.created?'Create the mountain laboratory':'Move the microscope closer to the window');
 if(!view)return;if(state.created&&!initial){architecture(architectureGroup);initial=true;}else if(!state.created&&initial){clear(architectureGroup);initial=false;}
 const night=state.lighting==='night',day=state.lighting==='daylight';view.background(night?'#142530':day?'#d6e4e3':'#e4c9ae');view.key.color.set(night?'#b1cee6':day?'#fff7e5':'#ffd09b');view.key.intensity=night?.45:day?2.5:2.7;view.key.position.set(day?4:-7,night?6:8,-3);view.hemi.intensity=night?.45:.85;view.rim.intensity=night?1.1:.55;
 for(const[id,g]of objects)if(!state.objects.some(o=>o.id===id)){view.content.remove(g);clear(g);objects.delete(id);}
 tweens=[];for(const o of state.objects){if(o.type==='window')continue;let g=objects.get(o.id);if(!g){g=makeObject({...o,color:null});g.traverse(m=>{if(m.isMesh)m.material.userData.baseColor=m.material.color.getHex();});view.content.add(g);objects.set(o.id,g);g.scale.setScalar(matchMedia('(prefers-reduced-motion: reduce)').matches?1:.01);}g.userData.position=o.position;g.userData.height=o.position.y;g.rotation.y=o.yaw*Math.PI/180;if(g.userData.lastColor!==o.color){g.traverse(m=>{if(m.isMesh)m.material.color.set(o.color||m.material.userData.baseColor);});}g.userData.lastColor=o.color;tweens.push({g,from:g.position.clone(),to:V([o.position.x,o.position.y,o.position.z]),scale:g.scale.x});}
 clear(routeGroup);if(state.path.length>1)line(routeGroup,state.path.map(p=>[p.x,.025,p.z]),'#6ac3b5',.018);animationStart=performance.now()/1000;
 view.setPickables([...objects.values()].filter(g=>g.userData.draggable));syncSelection();view.setTick((t,dt)=>{const a=dt===0?1:Math.min(1,(t-animationStart)/.75),k=1-(1-a)**3;for(const o of tweens){if(o.g.name===dragging)continue;o.g.position.lerpVectors(o.from,o.to,k);o.g.scale.setScalar(o.scale+(1-o.scale)*k);}if(state.path.length>1){const agent=objects.get('agent-1'),length=state.path.length-1,a=dt===0?1:Math.min(1,(t-animationStart)/Math.min(5,1+length*.09)),idx=a*length,lo=Math.floor(idx),hi=Math.min(length,lo+1),p=state.path[lo],q=state.path[hi];agent.position.set(p.x+(q.x-p.x)*(idx-lo),0,p.z+(q.z-p.z)*(idx-lo));if(hi!==lo)agent.rotation.y=Math.atan2(q.x-p.x,q.z-p.z);}},state.path.length>1?5500:850);
 root.dataset.objectIdentities=JSON.stringify(Object.fromEntries([...objects].map(([id,g])=>[id,g.uuid])));
 }
 root.querySelector('form').addEventListener('submit',e=>{e.preventDefault();run(input.value);});const examples={create:CREATE,closer:'Move the microscope closer to the window.',plant:'Add a plant.',night:'Make it night.',route:'Send the agent to the microscope.'};for(const[id,c]of Object.entries(examples))ui.on(id,()=>run(c));ui.on('next',()=>run(state.created?examples.closer:CREATE));
 ui.on('undo',()=>{clearTimeout(pending);pending=0;root.querySelector('.world-language button[type="submit"]').disabled=false;if(!past.length)return;future.push(clone(state));state=past.pop();compiled=null;save();draw();say('Previous scene restored.');});ui.on('redo',()=>{clearTimeout(pending);pending=0;root.querySelector('.world-language button[type="submit"]').disabled=false;if(!future.length)return;past.push(clone(state));state=future.pop();compiled=null;save();draw();say('Edit restored.');});ui.on('reset',()=>{clearTimeout(pending);pending=0;root.querySelector('.world-language button[type="submit"]').disabled=false;commit(laboratory(empty()),'Reset laboratory');view?.go([7.3,4.3,10],[0,1.2,-1.5]);});
 ui.on('enter',()=>{inside=!inside;view?.go(inside?[.5,1.9,3.2]:[7.3,4.3,10],inside?[0,1.4,-2.6]:[0,1.2,-1.5]);root.querySelector('[data-act="enter"]').textContent=inside?'See the whole world':'Step inside';if(inside)say('You are inside. Drag to look around; select an object to inspect it.');});
 ui.on('source',()=>{const el=root.querySelector('.scene-json');el.hidden=!el.hidden;});ui.on('export',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='mountain-laboratory.scene.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition,mic=root.querySelector('[data-act="microphone"]');if(!Speech){mic.disabled=true;mic.textContent='Speech unavailable';}else mic.onclick=()=>{if(recognition){recognition.abort();return;}recognition=new Speech();recognition.lang='en-US';recognition.interimResults=false;recognition.onresult=e=>run(e.results[0][0].transcript);recognition.onerror=e=>say(`Speech ${e.error}. Typed commands still work.`,true);recognition.onend=()=>{recognition=null;mic.textContent='Speak';};try{recognition.start();mic.textContent='Listening…';}catch(e){recognition=null;say(e.message,true);}};
 ui.sequence(i=>{if(i===0)run(CREATE,false);if(i===1)run(examples.closer,false);if(i===2){selected='microscope-1';view?.go([3.2,2.8,3.3],[0,1.3,-1.8]);drawPanel();syncSelection();}if(i===3)run(examples.route,false);});
 const dispose=ui.dispose.bind(ui);ui.dispose=()=>{disposed=true;clearTimeout(pending);recognition?.abort();if(routeGroup){clear(routeGroup);view.scene.remove(routeGroup);}if(selectionRing){selectionRing.geometry.dispose();selectionRing.material.dispose();view.scene.remove(selectionRing);}dispose();};draw();return ui;
}
