import {T,mesh,box,ball,line,rod,ring,clear,V} from './stage.mjs';
import {timeState,meanAt,simulatePeriod,urbanExample,interactionExample} from './math.mjs';
import {exhibit,slider,btn,stat,fmt} from './ui.mjs';
export function mountTime(root){
 let month=2,replay=24,budget=64,window=3,stable=false;
 const ui=exhibit(root,{theme:'time-world',title:'Yesterday does not update itself',intro:'The archive stays still. The world moves on.',controls:`<div class="time-selector"><span>Advance the present</span><div>${Array.from({length:10},(_,i)=>btn('month'+(i+1),String(i+1))).join('')}</div></div>${slider('replay','Replay updates',0,48,24)}${slider('window','History window',1,6,3)}${btn('stable','Keep the world stable')}`,math:'<p>One simulated period has a hard budget of 64 observations. Replaying k leaves exactly 64 − k for new observations. Each draw is actually processed by the local mean estimator. The archive in this example has lower noise variance: 0.2 rather than 1. This is an explicit modelling assumption, not a general property of old data.</p><p>If α = k/B and drift is the difference between the current and archived means, expected squared error is α²drift² + [(B−k) + 0.2k]/B². Thus at fixed compute, variance reduction can be overtaken by bias. “Oracle allocation” uses the known toy drift and is not a practical learned replay policy.</p>',boundary:'A synthetic budgeted estimation environment motivated by the TiC-LM replication question. It is not a language-model training run, and no numbers here are TiC-LM benchmark results.'});
 const view=ui.stage({background:'#f1eade',camera:[8.8,6.0,10.3],target:[0,.6,0]});let dots=[];
 function draw(){const s=timeState(month,replay,budget,window,stable),sample=simulatePeriod(s,1729+month);ui.state({...s,estimate:sample.estimate,processed:sample.processed});replay=s.replay;ui.set('replay',replay);ui.set('window',window);root.querySelectorAll('.time-selector button').forEach((b,i)=>{b.setAttribute('aria-current',i+1===month?'step':'false');b.classList.toggle('past',i+1<month);});root.querySelector('[data-act="stable"]').setAttribute('aria-pressed',String(stable));
 ui.read.innerHTML=`<h3>Same budget. Different use.</h3><div class="budget-blocks">${sample.samples.map(o=>`<i class="${o.old?'replayed':'new'}"></i>`).join('')}</div><div class="budget-legend"><span>${s.replay} replay</span><span>${s.newUpdates} new</span></div>${stat('Processed this simulated period',sample.processed,' / 64')}${stat('Bias from old information',fmt(Math.abs(s.bias)))}${stat('Expected squared error',fmt(s.error,4))}<div class="risk-compare"><span>New only <b>${fmt(s.noReplay,4)}</b></span><span class="${s.benefit<0?'bad':'good'}">Replay <b>${s.benefit<0?'increases':'reduces'} error</b></span></div><p class="rail-note">Archive noise variance 0.2; new observations 1.0. Equal 64-draw compute cap.</p>`;
 ui.story(s.benefit>=0?'The past earns its place in the budget.':'The same history now pulls the estimate backwards.',s.benefit>=0?'The archive reduces noise more than it adds bias. Advance time while leaving the replay allocation unchanged.':`${s.replay} of 64 updates are still spent on historical information. That information did not become noisier—it became wrong for the present.`,s.benefit>=0&&month<10?'Advance to a changed world':s.benefit<0?'Use the toy-oracle allocation':'Compare with fixed replay');
 if(!view)return;clear(view.content);dots=[];const g=view.content,labels=[],picks=[];
 box(g,[0,-.06,0],[10.6,.18,3.5],'#e1d1b4',{roughness:.62});line(g,[[-4.8,.08,1.4],[4.8,.08,1.4]],'#ad9374',.015);
 for(let t=1;t<=10;t++){const x=(t-5.5)*.94,m=stable?0:meanAt(t),past=t<month,current=t===month,selected=t>=month-window&&t<month,col=current?'#418c7b':selected?(s.benefit<0?'#c97c60':'#9fb695'):'#c4bba7';
  const panel=box(g,[x,.8+m*.6,-.35],[.10,1.5,1.55],col,{transparent:!current,opacity:current?.9:past?.6:.12,roughness:.45});panel.userData.pick=String(t);picks.push(panel);
  if(past||current){for(let j=0;j<5;j++)box(g,[x+.06,.42+m*.6+j*.19,-.45],[.018,.036,.75-j*.06],current?'#e2efe1':'#eee7d9',{roughness:.7});}
  if(current){ring(g,[x,.08,-.35],.8,'#4f9881');labels.push({text:`NOW · period ${t}`,pos:[x,2.0+m*.6,-.35],tone:'green'});}if(t===1)labels.push({text:'The archive',pos:[x,.22,1.6],tone:'light-label'});
 }
 const track=Array.from({length:10},(_,i)=>[(i-4.5)*.94,.10+(stable?0:meanAt(i+1))*.6,-1.35]);line(g,track,'#588671',.025);const x=(month-5.5)*.94;ball(g,[x,.15+s.current*.6,-1.35],.09,'#3f927f');ball(g,[x,.15+s.past*.6,-1.35],.075,'#c67a50');if(s.drift>.01){line(g,[[x,.15+s.past*.6,-1.35],[x,.15+s.current*.6,-1.35]],'#cb7956',.035);labels.push({text:`History lags by ${fmt(s.drift,2)}`,pos:[x+.2,.5+s.past*.6,-1.7],tone:'red'});}
 for(let i=0;i<Math.min(replay,12);i++){const a=[(Math.max(1,month-1-(i%window))-5.5)*.94,.2,1.0],b=[x,.2,1.0],p=ball(g,a,.025,s.benefit<0?'#b86443':'#779b75');dots.push({p,a:V(a),b:V(b),delay:i/12});}
 view.setPickables(picks);view.setLabels(labels);view.setTick(t=>dots.forEach(o=>o.p.position.lerpVectors(o.a,o.b,(t*.28+o.delay)%1)));
 }
 for(let i=1;i<=10;i++)ui.on('month'+i,()=>{month=i;draw();});ui.input('replay',v=>{replay=v;draw();});ui.input('window',v=>{window=v;draw();});ui.on('stable',()=>{stable=!stable;draw();});ui.on('next',()=>{const s=timeState(month,replay,budget,window,stable);if(s.benefit<0)replay=s.oracle;else if(month<10){month=8;stable=false;}else replay=32;draw();});ui.on('reset',()=>{month=2;replay=24;window=3;stable=false;draw();});ui.sequence(i=>{month=[2,4,8,8][i];replay=i===3?timeState(8,24,64,3).oracle:24;stable=false;draw();});draw();return ui;
}
function vehicle(g,x,z,bike=false){const group=new T.Group();g.add(group);group.position.set(x,0,z);if(bike){for(const dx of[-.22,.22]){const w=ring(group,[dx,.20,0],.16,'#344641',[0,Math.PI/2,0],.027);}rod(group,[-.2,.2,0],[.15,.48,0],.03,'#9d5840');rod(group,[.2,.2,0],[.15,.48,0],.024,'#9d5840');box(group,[-.06,.43,0],[.26,.23,.26],'#a67a56');}else{box(group,[0,.34,0],[.86,.54,.44],'#e7e5d9',{roughness:.3});box(group,[.30,.51,0],[.21,.2,.45],'#526f75');for(const x of[-.27,.29])for(const z of[-.24,.24])mesh(group,new T.CylinderGeometry(.11,.11,.07,18),'#35443f',[x,.13,z]).rotation.x=Math.PI/2;}return group;}
export function mountUrban(root){
 let region=0,parking=0;const ui=exhibit(root,{theme:'urban-world',title:'The last few metres change the answer',intro:'A faster vehicle can still make a slower delivery.',controls:`<div class="district-select">${['Dense centre','Residential','Outer district'].map((v,i)=>btn('region'+i,v)).join('')}</div>${slider('parking','Van parking search',0,10,0,.5,' min')}`,math:'<p>Service time = travel + parking + final walk. Travel time is 60 × distance / speed. The two modes use the same route length for each chosen region; stop overhead differs. Every displayed component is explicitly computed.</p>',boundary:'These are schematic micro-regions and invented service times, not H3 geometry, geographic data, or predictions from the paper’s fitted model. Payload, weather and full routing constraints are omitted.'});
 const view=ui.stage({background:'#eaf0e9',camera:[8,6.8,9],target:[0,.3,0]});
 function draw(){const s=urbanExample(region,parking);ui.state({...s,region});ui.set('parking',parking,' min');root.querySelectorAll('.district-select button').forEach((b,i)=>b.setAttribute('aria-pressed',i===region));ui.read.innerHTML=`<h3>One parcel. Two journeys.</h3>${[['Van',s.van,s.vanTotal],['Cargo bike',s.bike,s.bikeTotal]].map(([n,parts,total])=>`<div class="delivery-total"><h4>${n}<b>${fmt(total,1)} min</b></h4>${parts.map((p,i)=>`<div><span>${['Travel','Parking','Walk'][i]}</span><i style="width:${p/20*100}%"></i><strong>${fmt(p,1)}</strong></div>`).join('')}</div>`).join('')}<div class="w-callout">${s.bikeTotal<s.vanTotal?'The bike wins here—not because it travels faster, but because it spends less time stopping.':'Here the travel-speed advantage is large enough to survive the stop overhead.'}</div>`;ui.story(s.bikeTotal<s.vanTotal?'The road was only part of the delivery.':'Fast on the road. Now add the stop.',`In ${s.name.toLowerCase()}, the van spends ${fmt(parking,1)} minutes finding a place to stop. Change that one component and the answer can reverse.`,parking<4?'Add seven minutes of parking':'Remove the parking search');if(!view)return;clear(view.content);const g=view.content;
 const tile=mesh(g,new T.CylinderGeometry(4.3,4.3,.22,6),'#cfdbca',[0,-.04,0],{roughness:.8});tile.rotation.y=Math.PI/6;
 box(g,[0,.1,0],[7.3,.02,1.3],'#aab8af',{roughness:.9});box(g,[0,.1,0],[1.2,.02,6.3],'#aab8af',{roughness:.9});for(let i=-3;i<=3;i++){box(g,[i,.13,0],[.3,.01,.025],'#e3e7d8');box(g,[0,.13,i],[.025,.01,.3],'#e3e7d8');}
 const buildings=[[-2, -1.8],[1.8,-1.7],[-2,1.8],[2,1.8]];buildings.forEach(([x,z],i)=>{const h=[1.7,.95,.55][region]+i*.13,b=box(g,[x,h/2+.13,z],[1.35,h,1.2],i===0?'#b9c9b8':'#dcd8c7',{roughness:.68});box(g,[x,h+.18,z],[1.46,.08,1.31],'#899c90');for(let y=.45;y<h;y+=.45)for(let j=-1;j<=1;j++)box(g,[x+j*.31,y,z+.608],[.18,.21,.018],'#638c92');});
 for(const[x,z]of[[-3.3,-1],[3.2,.9],[-3.1,2.1],[2.9,-2.4]]){rod(g,[x,.1,z],[x,.7,z],.04,'#8d7d59');ball(g,[x,.9,z],.3,'#789a76',{roughness:.8});}
 const van=vehicle(g,-3,.32),bike=vehicle(g,-3,-.37,true);view.setLabels([{text:'The same parcel',pos:[-2,2.4,-1.8],tone:'light-label'},{text:s.name,pos:[0,.2,3.3],tone:'green'}]);view.setTick(t=>{const u=t%18;van.position.x=-3+Math.min(1,u/s.vanTotal)*5.5;bike.position.x=-3+Math.min(1,u/s.bikeTotal)*5.5;});
 }
 [0,1,2].forEach(i=>ui.on('region'+i,()=>{region=i;parking=[7,3,1][i];draw();}));ui.input('parking',v=>{parking=v;draw();});ui.on('next',()=>{parking=parking<4?7:0;draw();});ui.on('reset',()=>{region=0;parking=0;draw();});ui.sequence(i=>{region=i<2?0:2;parking=[0,7,1,1][i];draw();});draw();return ui;
}
export function mountInteraction(root){
 let paired=false,distributed=false;const ui=exhibit(root,{theme:'conversation-world',title:'Eight messages. Two different conversations.',intro:'A group total cannot tell you who is actually being reached.',controls:`${btn('pairs','Reveal individual accounts')}${btn('redistribute','Redistribute the same eight replies')}`,math:'<p>The concentrated pattern has recipient counts [6,1,1,0]; the distributed pattern has [2,2,2,2]. Both contain exactly eight messages. Line thickness and moving markers encode counts, not inferred sentiment or effectiveness.</p>',boundary:'All accounts and messages are fictional. The original research studies paired lexical, linguistic and psycholinguistic characteristics. Descriptive interaction cannot establish causal persuasion.'});
 const view=ui.stage({background:'#edf0ed',camera:[7,6.3,8.8],target:[0,.25,0]});let moving=[];
 function draw(){const s=interactionExample(distributed);ui.state({...s,paired,distributed});ui.read.innerHTML=`<h3>The count did not change.</h3>${stat('Messages',8)}${stat('Recipients reached',paired?s.distinctRecipients:'Hidden')}${stat('Largest recipient share',paired?Math.max(...s.recipientCounts)/8*100+'%':'Hidden')}<div class="recipient-bars">${s.recipientCounts.map((n,i)=>`<div><span>B${i+1}</span><i><b style="width:${paired?n/8*100:0}%"></b></i><strong>${paired?n:'?'}</strong></div>`).join('')}</div>`;ui.story(!paired?'From above, the patterns look identical.':distributed?'Same eight replies. Nobody left out.':'Six of eight replies reach one account.',!paired?'The aggregate flattens people into a single total. Open the network to see whose interactions are hidden.':'The unit of analysis changes what you can know. Pair structure reveals concentration that the group total erases.',!paired?'Reveal the individual accounts':distributed?'Concentrate the replies':'Keep the count. Change the recipients.');if(!view)return;clear(view.content);moving=[];const g=view.content,labels=[];
 if(!paired){for(const x of[-2.3,2.3]){mesh(g,new T.CylinderGeometry(1.0,1.1,.23,64),'#d8dfd5',[x,.12,0]);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;ball(g,[x+Math.cos(a)*.5,.4,Math.sin(a)*.5],.13,x<0?'#75a6a2':'#c3a58a');}labels.push({text:'8 messages',pos:[x,1.05,0],tone:'light-label'});}line(g,[[-1.2,.5,0],[0,1.1,0],[1.2,.5,0]],'#719e96',.10);}
 else{for(let side=0;side<2;side++)for(let i=0;i<4;i++){const x=side?2.3:-2.3,z=(i-1.5)*1.05;mesh(g,new T.CylinderGeometry(.30,.33,.12,48),side?'#d9c9b6':'#a4c8bf',[x,.08,z]);ball(g,[x,.36,z],.18,side?'#b99579':'#669d8f');labels.push({text:(side?'B':'A')+(i+1)+(side?' · '+s.recipientCounts[i]:''),pos:[x,.8,z],tone:'light-label'});}s.pairs.forEach(([a,b,n],i)=>{const points=[[-2.3,.4,(a-1.5)*1.05],[0,.7+Math.abs(a-b)*.16,(a+b-3)*.525],[2.3,.4,(b-1.5)*1.05]];line(g,points,'#79aa9b',.012+n*.01);const curve=new T.CatmullRomCurve3(points.map(V));for(let j=0;j<n;j++){const p=ball(g,points[0],.045,'#558f7d');moving.push({p,curve,offset:j/n+i*.16});}});}
 view.setLabels(labels);view.setTick(t=>moving.forEach(o=>o.p.position.copy(o.curve.getPoint((t*.22+o.offset)%1))));
 }
 ui.on('pairs',()=>{paired=!paired;draw();});ui.on('redistribute',()=>{paired=true;distributed=!distributed;draw();});ui.on('next',()=>{if(!paired)paired=true;else distributed=!distributed;draw();});ui.on('reset',()=>{paired=false;distributed=false;draw();});ui.sequence(i=>{paired=i>0;distributed=i>1;draw();});draw();return ui;
}
